Repository openshift/kubernetes, pull requests merged in 2019-08, with the labels that each got.

#73 UPSTREAM: <drop>: revert UPSTREAM: carry>: kubectl: allow version injection
  pkg/kubectl/cmd/version/patch_version.go
  pkg/kubectl/cmd/version/version.go
Labels: size/S

#74 UPSTREAM: 76161: use server-side printing in
  pkg/kubectl/cmd/get/BUILD
  pkg/kubectl/cmd/get/get.go
  pkg/kubectl/cmd/get/get_test.go
  pkg/kubectl/cmd/get/sorter.go
  pkg/kubectl/cmd/get/table_printer.go
  pkg/kubectl/scheme/BUILD
  pkg/kubectl/scheme/install.go
  pkg/printers/humanreadable.go
  staging/src/k8s.io/apimachinery/pkg/apis/meta/v1beta1/register.go
Labels: kind/api-change, size/L

#75 Bug 1735404 - UPSTREAM:80827: 'kubectl get' count binaryData keys on ConfigMap
  pkg/printers/internalversion/printers.go
Labels: size/XS

#76 Bug 1708280 - UPSTREAM: 77681: Fix handling empty result when invoking kubectl get
  pkg/kubectl/cmd/get/get.go
  pkg/kubectl/cmd/get/get_test.go
Labels: approved, size/M

#77 Bug 1737657 - UPSTREAM: 80436: refactors to kubernetes CP command
  pkg/kubectl/cmd/cp/BUILD
  pkg/kubectl/cmd/cp/cp.go
  pkg/kubectl/cmd/cp/cp_test.go
Labels: size/L

#78 UPSTREAM: 76161: use server-side printing in
  pkg/kubectl/cmd/get/BUILD
  pkg/kubectl/cmd/get/get.go
  pkg/kubectl/cmd/get/get_test.go
  pkg/kubectl/cmd/get/sorter.go
  pkg/kubectl/cmd/get/table_printer.go
  pkg/kubectl/scheme/BUILD
  pkg/kubectl/scheme/install.go
  pkg/printers/humanreadable.go
  staging/src/k8s.io/apimachinery/pkg/apis/meta/v1beta1/register.go
Labels: kind/api-change, size/L

#79 UPSTREAM: 81229: kubectl: eliminate unnecessary blank ending line
  pkg/kubectl/cmd/get/get.go
  pkg/kubectl/cmd/get/get_test.go
Labels: approved, size/L
