Repository openshift/kubernetes, pull requests merged in 2020-10, with the labels that each got.

#380 Bug 1881144: UPSTREAM: 95003: Fail a test on pre-provisioned Cinder volume deletion error
  test/e2e/storage/drivers/in_tree.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#379 Bug 1882750: UPSTREAM: <carry>: watch-termination: avoid false positives of NonGracefulTermination events
  cmd/watch-termination/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#378 Bug 1879057: e2e: skip write/read cache when running Block-mode RWX PVC tests
  test/e2e/framework/pod/create.go
  test/e2e/storage/testsuites/multivolume.go
  test/e2e/storage/utils/utils.go
  test/utils/image/manifest.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#355 Bug 1848358: Show error in status if preserve unknown fields is true for nonstructural schemas
  staging/src/k8s.io/apiextensions-apiserver/pkg/controller/nonstructuralschema/BUILD
  staging/src/k8s.io/apiextensions-apiserver/pkg/controller/nonstructuralschema/nonstructuralschema_controller.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/controller/nonstructuralschema/nonstructuralschema_controller_test.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/validation_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, kind/api-change, kind/bug, lgtm

#336 Bug 1874583: fix kube-apiserver termination event(s) validation failures
  cmd/kube-apiserver/app/server.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, kind/bug, lgtm

#385 Bug 1884697: UPSTREAM: 95261: test: e2e: fix race in pods test
  test/e2e/node/pods.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#393 bug 1884035: set lastterminationstate for container status even when CRI fails to return termination (or any) data
  pkg/kubelet/kubelet_pods.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#406 Bug 1887292: UPSTREAM: 95245: Mask Ceph RBD adminSecrets in logs when logLevel >= 4
  pkg/volume/rbd/rbd_util.go
Labels: approved, lgtm

#403 bug 1888663: wait for oauth-apiserver accessibility
  openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  openshift-kube-apiserver/openshiftkubeapiserver/sdn_readyz_wait.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#411 Bug 1888041: UPSTREAM: 95561: kubelet container status calculation doesn't handle suddenly missing data properly
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#382 Fix networking-related test exclusions
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
  openshift-hack/test-kubernetes-e2e.sh
  test/e2e/network/network_policy.go
Labels: approved, lgtm

#408 Bug 1868527: Fix vsphere disk detach failing
  pkg/volume/vsphere_volume/attacher.go
  pkg/volume/vsphere_volume/attacher_test.go
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/virtualmachine.go
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#413 Bug 1887026: UPSTREAM: 95451: Fix fcpath
  pkg/volume/fc/fc_util.go
  pkg/volume/fc/fc_util_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#418 Bug 1889891: UPSTREAM: 94774: Fix misusage of RLock in timeCache lru.Cache.Get()
  pkg/kubelet/time_cache.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#422 Add component to OWNERS
  OWNERS
Labels: approved, lgtm

#405 UPSTREAM: 95495: remove secondary client retries in e2e tests
  test/e2e/apps/daemon_set.go
  test/e2e/cloud/gcp/addon_update.go
  test/e2e/e2e.go
  test/e2e/framework/ingress/ingress_utils.go
  test/e2e/framework/network/BUILD
  test/e2e/framework/network/utils.go
  test/e2e/framework/node/wait.go
  test/e2e/framework/pod/resource.go
  test/e2e/framework/pod/wait.go
  test/e2e/framework/ssh/BUILD
  test/e2e/framework/ssh/ssh.go
  test/e2e/framework/util.go
  test/e2e/scheduling/priorities.go
  test/integration/framework/perf_utils.go
  test/integration/framework/util.go
  test/utils/BUILD
  test/utils/create_resources.go
  test/utils/delete_resources.go
  test/utils/update_resources.go
Labels: approved, lgtm

#425 Bug 1879607: UPSTREAM: 95252: Kube-proxy: Perf-fix: Shrink INPUT chain
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#395 Bug 1884041: UPSTREAM: 95233: Add error text to kube-system wait error
  test/e2e/framework/pod/wait.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#427 Bug 1891459: UPSTREAM: 95867: Log PodExec stdout + stderr
  test/e2e/storage/host_path_type.go
  test/e2e/storage/persistent_volumes-local.go
  test/e2e/storage/testsuites/snapshottable.go
  test/e2e/storage/testsuites/volume_io.go
  test/e2e/storage/utils/utils.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
