Repository openshift/kubernetes, pull requests merged in 2020-11, with the labels that each got.

#291 Bug 1816812: Allow test images to be in a single mirror
  test/utils/image/manifest.go
  test/utils/image/manifest_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#434 Revert "UPSTREAM: 95252: Kube-proxy: Perf-fix: Shrink INPUT chain"
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_test.go
Labels: approved, lgtm

#432 Bug 1887278: UPSTREAM: 95236: vsphere: improve logging message on node cache refresh event
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#439 UPSTREAM: <carry>: stop overriding flags that are explicitly set
  openshift-kube-apiserver/openshiftkubeapiserver/flags.go
Labels: approved, lgtm

#442 UPSTREAM: 95252: Kube-proxy: Perf-fix: Shrink INPUT chain
  cmd/kube-proxy/app/server_patch.go
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_openshift.go
  pkg/proxy/iptables/proxier_test.go
  pkg/proxy/userspace/proxier_openshift.go
Labels: approved, lgtm

#441 Bug 1870337: UPSTREAM: 96310: PV e2e: fix race in NFS recycling test
  test/e2e/storage/persistent_volumes.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, kind/bug, kind/flake, lgtm

#383 Bug 1862643: UPSTREAM: 96120: kubelet: Expose a simple Get-WinEvent shim on the kubelet logs endpoint
  pkg/kubelet/BUILD
  pkg/kubelet/kubelet_server_journal.go
  pkg/kubelet/kubelet_server_journal_linux.go
  pkg/kubelet/kubelet_server_journal_others.go
  pkg/kubelet/kubelet_server_journal_test.go
  pkg/kubelet/kubelet_server_journal_windows.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, kind/feature, lgtm

#448 UPSTREAM: revert: <drop>: don't use dynamic tokens for KCM
  cmd/kube-controller-manager/app/controllermanager.go
Labels: approved, lgtm

#459 Revert "UPSTREAM: revert: <drop>: don't use dynamic tokens for KCM"
  cmd/kube-controller-manager/app/controllermanager.go
Labels: approved, lgtm

#456 UPSTREAM 95002: no stack on panic timeout
  cmd/controller-manager/app/serve.go
  cmd/kube-scheduler/app/server.go
  pkg/kubeapiserver/server/insecure_handler.go
  staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
  staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go
  staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
  staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go
Labels: approved, lgtm

#444 scc-admission: add audit annotations with reason
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/types.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/util/sort/bypriority.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/util/sort/byrestrictions.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#455 UPSTREAM: 96571: Use the busybox shim image constant
  test/integration/etcd/data.go
Labels: approved, lgtm

#440 Bug 1877681: UPSTREAM: 95174: Don't add empty AZ labels to OpenStack pre-provisioned PVs
  staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, kind/bug, lgtm

#447 OCPCLOUD-914: UPSTREAM: 94526: Add vCenter info metric
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/connection.go
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/vsphere_metrics.go
Labels: approved, lgtm

#460 Bug 1893776: UPSTREAM: 96054: Allow debugging kubelet image pull times
  pkg/kubelet/metrics/metrics.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#462 Bug 1897754: HPA: Ignore deleted pods.
  pkg/controller/podautoscaler/replica_calculator.go
  pkg/controller/podautoscaler/replica_calculator_test.go
Labels: approved, lgtm

#450 UPSTREAM: <carry>: Skip "subPath should be able to unmount" NFS test
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, kind/bug, kind/failing-test, lgtm

#451 Bug 1893972: UPSTREAM: 96144: Skip the sig-storage e2e test as early as possible
  test/e2e/storage/testsuites/base.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#461 Bug 1884800: Reduce volume name length for vsphere
  pkg/volume/vsphere_volume/vsphere_volume_util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#452 UPSTREAM: 94693: test/e2e: Busybox image is not being templatized
  test/e2e/generated/bindata.go
  test/e2e/kubectl/kubectl.go
  test/e2e/testing-manifests/kubectl/busybox-cronjob.yaml.in
  test/e2e/testing-manifests/kubectl/busybox-pod.yaml.in
Labels: approved, lgtm

#472 Bug 1873114: Nodes goes into NotReady state (VMware)
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/client-go/transport/cache.go
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/csi-translation-lib/go.mod
  staging/src/k8s.io/csi-translation-lib/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.mod
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.mod
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.mod
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.mod
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.mod
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.mod
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.mod
  staging/src/k8s.io/sample-controller/go.sum
  vendor/github.com/openshift/library-go/pkg/config/client/client_config.go
  vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
  vendor/github.com/openshift/library-go/pkg/network/dialer.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update
