Repository openshift/kubernetes, pull requests merged in 2020-09, with the labels that each got.

#330 bug 1874919: UPSTREAM: 94423: debugger scheduler plugin
  cmd/kube-scheduler/app/server_test.go
  pkg/scheduler/algorithmprovider/BUILD
  pkg/scheduler/algorithmprovider/registry.go
  pkg/scheduler/algorithmprovider/registry_test.go
  pkg/scheduler/apis/config/testing/compatibility_test.go
  pkg/scheduler/framework/plugins/BUILD
  pkg/scheduler/framework/plugins/debugger/BUILD
  pkg/scheduler/framework/plugins/debugger/debugger.go
  pkg/scheduler/framework/plugins/registry.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, kind/feature, lgtm

#331 BUG 1875041: UPSTREAM: 94134: Make similar buckets for api and etcd request duration histogram
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, kind/bug, lgtm

#332 Bug 1875841: watch-termination: fix deletion race and write non-graceful message also to termination.log
  cmd/watch-termination/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#335 Bug 1821661: UPSTREAM: 94614: e2e: fix deployment non-unique env vars to avoid SSA error
  test/e2e/apps/deployment.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#333 Bug 1867103: UPSTREAM: 93777: e2e storage: avoid flaky test failure when watch dies
  test/e2e/storage/BUILD
  test/e2e/storage/csi_mock_volume.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#338 Bug 1875046: Undiagnosed panic detected in pod: openshift-kube-apiserver_kube-apiserver: runtime.go:76: invalid memory address or nil pointer dereference
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#344 Bug 1877001: UPSTREAM: 92878: cleanup: print warning message only if the function does not finish within 30 seconds
  pkg/volume/volume_linux.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#343 UPSTREAM: 89885: Bug 1850149: Include / prefix in the instance ID output
  staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_instances.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#318 Bug 1854434: UPSTREAM: 94112: Remove canonicalization of endpoints by endpoints controller for better comparison
  pkg/controller/endpoint/endpoints_controller.go
  pkg/controller/endpoint/endpoints_controller_test.go
  pkg/registry/core/endpoint/BUILD
  pkg/registry/core/endpoint/strategy.go
  test/integration/BUILD
  test/integration/endpoints/BUILD
  test/integration/endpoints/endpoints_test.go
  test/integration/endpoints/main_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#327 Bug 1874584: UPSTREAM: <carry>: retry etcd errors
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient_test.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#349 Bug 1873043: Commit test/e2e/generated/bindata.go
  hack/make-rules/clean.sh
  test/e2e/generated/.gitignore
  test/e2e/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#334 Bug 1875194: UPSTREAM: 94609: Use namespace flag passed to RunKubectl* methods
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
  test/e2e/apps/statefulset.go
  test/e2e/examples.go
  test/e2e/framework/ingress/ingress_utils.go
  test/e2e/framework/kubectl/kubectl_utils.go
  test/e2e/framework/util.go
  test/e2e/kubectl/kubectl.go
  test/e2e/storage/testsuites/subpath.go
  test/e2e/storage/vsphere/vsphere_utils.go
  test/e2e/upgrades/cassandra.go
  test/e2e/upgrades/etcd.go
  test/e2e/upgrades/mysql.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#347 Bug 1867929: Reduce offline volume expansion flake
  pkg/controller/volume/expand/BUILD
  pkg/controller/volume/expand/expand_controller.go
  pkg/controller/volume/expand/expand_controller_test.go
  test/e2e/storage/testsuites/volume_expand.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#337 Bug 1873043: Enable k8s-e2e-gcp-serial
  openshift-hack/test-kubernetes-e2e.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#340 Bug 1877338: UPSTREAM: 94653: Tolerate NotFound errors when deleting snapshots
  test/e2e/storage/testsuites/snapshottable.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#351 Bug 1873043: Commit openapi definitions
  pkg/generated/openapi/.gitignore
  pkg/generated/openapi/zz_generated.openapi.go
  test/e2e/generated/.gitignore
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#350 Bug 1877791: Release lock on KCM and KS termination
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-scheduler/app/server.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#348 Bug 1878163: Build with golang 1.15
  hack/lib/golang.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  openshift-hack/images/tests/Dockerfile.rhel
  openshift-hack/lib/constants.sh
  openshift-hack/lib/deps.sh
  openshift-hack/test-go.sh
  openshift-hack/test-integration.sh
  openshift-hack/verify.sh
  openshift.spec
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#352 bug 1880279: [e2e] scheduling: Pod should avoid nodes that have avoidPod annotation: fail when not all pods are properly deleted
  test/e2e/scheduling/priorities.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#345 bug 1874920: Revert "bug 1874919: UPSTREAM: 94423: debugger scheduler plugin"
  cmd/kube-scheduler/app/server_test.go
  pkg/scheduler/algorithmprovider/BUILD
  pkg/scheduler/algorithmprovider/registry.go
  pkg/scheduler/algorithmprovider/registry_test.go
  pkg/scheduler/apis/config/testing/compatibility_test.go
  pkg/scheduler/framework/plugins/BUILD
  pkg/scheduler/framework/plugins/debugger/BUILD
  pkg/scheduler/framework/plugins/debugger/debugger.go
  pkg/scheduler/framework/plugins/registry.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#356 Bug 1880941: kube-apiserver: log non-probe requests before ready
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/config_test.go
  staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
  staging/src/k8s.io/apiserver/pkg/server/healthz.go
  staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go
  staging/src/k8s.io/apiserver/pkg/server/healthz/healthz_test.go
  staging/src/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#360 Bug 1873043: Add rebase instructions
  REBASE.openshift.md
  openshift-hack/commit-tag.png
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#362 Bug 1880363: UPSTREAM: 94888: apiextensions: prune array type without items in published OpenAPI
  staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/v2/BUILD
  staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/v2/conversion.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/v2/conversion_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#357 Bug 1866814: UPSTREAM: 94773: count of etcd object should be limited to the specified resource
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, kind/bug, lgtm

#367 Bug 1877793: Force releasing the lock on exit for KS
  cmd/kube-scheduler/app/server.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#370 Bug 1878091: UPSTREAM: 94712: avoid potential secret leaking while reading .dockercfg
  pkg/credentialprovider/config.go
  pkg/credentialprovider/config_test.go
  staging/src/k8s.io/kubectl/pkg/cmd/get/sorter.go
  staging/src/k8s.io/kubectl/pkg/cmd/get/sorter_test.go
Labels: approved, lgtm

#368 Bug 1881225: UPSTREAM: <carry>: apiserver: create hasBeenReadyCh channel
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#365 Bug 1881238: UPSTREAM: 94903: Take into account latency incurred in server filters
  staging/src/k8s.io/apiserver/pkg/audit/request.go
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/BUILD
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/audit.go
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/request_received_time.go
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/request_received_time_test.go
  staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  staging/src/k8s.io/apiserver/pkg/endpoints/request/BUILD
  staging/src/k8s.io/apiserver/pkg/endpoints/request/received_time.go
  staging/src/k8s.io/apiserver/pkg/endpoints/request/received_time_test.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, kind/bug, lgtm

#371 Bug 1881688: UPSTREAM: 94984: check readyz before adding endpoint for kube-apiserver
  pkg/master/controller.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#373 Bug 1866836: UPSTREAM: 95009: Remove ext2 + ext3 tests
  test/e2e/storage/drivers/in_tree.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#374 Bug 1882446: Fix pre-readyz request message without ?verbose
  staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#375 Bug 1879837: UPSTREAM: 94986: drop managed fields from audit entries
  staging/src/k8s.io/apiserver/pkg/audit/request.go
  staging/src/k8s.io/apiserver/pkg/audit/request_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, kind/bug, lgtm

#366 Bug 1873043: Update README.openshift to reflect transition to openshift/kubernetes
  README.openshift.md
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#376 Bug 1883196: kube-apiserver: silence own loopback requests before /readyz success
  staging/src/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#377 Bug 1873043: Stop annotating origin tests with [Suite:openshift]
  openshift-hack/e2e/annotate/annotate.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
