Repository openshift/kubernetes, pull requests merged in 2020-08, with the labels that each got.

#294 Add custom resource validation for network spec
  openshift-kube-apiserver/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  openshift-kube-apiserver/admission/customresourcevalidation/network/BUILD
  openshift-kube-apiserver/admission/customresourcevalidation/network/validate_network_config.go
Labels: approved, kind/feature, lgtm

#299 UPSTREAM: 93429: e2e: examples: fix test image reference
  test/e2e/generated/bindata.go
  test/fixtures/doc-yaml/user-guide/secrets/secret-pod.yaml.in
Labels: approved, lgtm

#301 UPSTREAM: <carry>: Strip unnecessary security contexts on Windows
  pkg/kubelet/kuberuntime/kuberuntime_container_windows.go
  pkg/kubelet/kuberuntime/kuberuntime_sandbox.go
  test/e2e/windows/security_context.go
Labels: approved, lgtm

#303 Bug 1861631: UPSTREAM: 85983: fix metrics kubelet_running_pod_count
  pkg/kubelet/pleg/generic.go
  pkg/kubelet/pleg/generic_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#306 UPSTREAM: 93658: test/e2e: fail test rather than flooding logs if PVC watch is closed prematurely
  test/e2e/storage/csi_mock_volume.go
Labels: approved, kind/failing-test, lgtm

#305 oauth-token-authn: switch to sha256~ prefix
  openshift-kube-apiserver/authentication/oauth/bootstrapauthenticator.go
  openshift-kube-apiserver/authentication/oauth/tokenauthenticator.go
  openshift-kube-apiserver/authentication/oauth/tokenauthenticator_test.go
Labels: approved, lgtm

#293 UPSTREAM: <carry>: add readyz check for openshift apiserver availability
  openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  openshift-kube-apiserver/openshiftkubeapiserver/sdn_readyz_wait.go
Labels: approved, lgtm

#297 Switch to golang 1.14
  hack/lib/golang.sh
  hack/update-vendor.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  openshift-hack/images/tests/Dockerfile.rhel
  openshift-hack/lib/constants.sh
  openshift.spec
  staging/src/k8s.io/apiserver/pkg/apis/config/validation/validation_test.go
Labels: approved, kind/api-change, lgtm

#308 UPSTREAM: <carry>: only create valid LateConnections/GracefulTermination events
  staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
Labels: approved, lgtm

#298 Misc post rebase cleanup
  cmd/kube-controller-manager/app/patch.go
  cmd/kube-controller-manager/app/patch_informers_openshift.go
  cmd/watch-termination/main.go
  go.mod
  go.sum
  openshift-hack/images/hyperkube/Dockerfile.rhel
  openshift-kube-apiserver/admission/authorization/restrictusers/restrictusers.go
  openshift-kube-apiserver/admission/autoscaling/clusterresourceoverride/admission.go
  openshift-kube-apiserver/admission/autoscaling/runonceduration/admission.go
  openshift-kube-apiserver/admission/network/externalipranger/externalip_admission.go
  openshift-kube-apiserver/admission/network/restrictedendpoints/endpoint_admission.go
  openshift-kube-apiserver/admission/scheduler/podnodeconstraints/admission.go
  openshift-kube-apiserver/authentication/oauth/timeoutvalidator.go
  openshift-kube-apiserver/configdefault/kubecontrolplane_default.go
  pkg/kubelet/kuberuntime/convert.go
  pkg/registry/certificates/certificates/strategy.go
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/controllers/node/BUILD
  staging/src/k8s.io/cloud-provider/controllers/node/node_controller_test.go
  staging/src/k8s.io/cloud-provider/controllers/nodelifecycle/node_lifecycle_controller_test.go
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/accept.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/rules/accept.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/rules/rules.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/matcher.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/util/sort/byrestrictions.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: kind/api-change, lgtm, vendor-update

#320 bug 1868750: UPSTREAM: <drop>: don't use dynamic tokens for KCM
  cmd/kube-controller-manager/app/controllermanager.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#295 BUG 1858871: UPSTREAM: 93478: kubelet: eviction: remove unexpected output from TestGetReclaimableThreshold
  pkg/kubelet/eviction/helpers_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#319 BUG 1863009: vSphere provision failure on ocp46
  staging/src/k8s.io/legacy-cloud-providers/vsphere/nodemanager.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#323 Bug 1855500: UPSTREAM: 94204: Add impersonated user to system:authenticated group
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/impersonation_test.go
  test/cmd/authorization.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
