Repository openshift/kubernetes, pull requests merged in 2020-12, with the labels that each got.

#469 UPSTREAM: 95252: Kube-proxy: Perf-fix: Shrink INPUT chain
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_test.go
Labels: approved, lgtm

#470 UPSTREAM: 95252: Kube-proxy: Perf-fix: Shrink INPUT chain
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_test.go
Labels: approved, lgtm

#466 Bug 1901208: Nodes goes into NotReady state (VMware)
  go.mod
  go.sum
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/client-go/transport/cache.go
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/csi-translation-lib/go.mod
  staging/src/k8s.io/csi-translation-lib/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.mod
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.mod
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.mod
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.mod
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.mod
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.mod
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.mod
  staging/src/k8s.io/sample-controller/go.sum
  vendor/github.com/openshift/library-go/pkg/config/client/client_config.go
  vendor/github.com/openshift/library-go/pkg/network/dialer.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#474 Bug 1903248: UPSTREAM: 87461: kubelet: ensure pod UIDs are unique
  pkg/kubelet/config/common.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#481 Bug 1770017: kubelet: do not rerun init containers if any main containers have status
  pkg/kubelet/kuberuntime/kuberuntime_container.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#488 Fix vendoring of shared libraries missed by 1.20 rebase.
  go.mod
  go.sum
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  vendor/modules.txt
Labels: approved, lgtm, vendor-update
