Repository openshift/kubernetes, pull requests merged in 2021-08, with the labels that each got.

#854 Bug 1957133: do not throw error when we can't get canonical path
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backports/validated-commits

#879 Bug 1981775: Bump apiserver libary go 4.7
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apimachinery/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/cluster-bootstrap/go.sum
  staging/src/k8s.io/code-generator/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/cri-api/go.sum
  staging/src/k8s.io/csi-translation-lib/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/mount-utils/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/accept.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#881 Bug 1973766: 4.7: Do not throw error when we can't get canonical path
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backports/validated-commits

#860 Bug 1980118: UPSTREAM: <carry>: drop the warning to use --keep-annotations
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission.go
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#887 Bug 1994643: UPSTREAM: <carry>: use lifeCycleSignals for isTerminating
  cmd/kube-apiserver/app/server.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/patch_config.go
Labels: approved, lgtm, kind/cleanup, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent, backports/validated-commits

#891 Bug 1986306: Kubectl client kubectl wait should ignore not found error with --for=delete
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#877 Bug 1982868: UPSTREAM: <carry>: admission/managementcpusoverride: cover the roll-back case
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission.go
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#889 Bug 1994643: UPSTREAM: 104281: send retry-after until the apiserver is ready
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/config_test.go
  staging/src/k8s.io/apiserver/pkg/server/filters/waitgroup.go
  staging/src/k8s.io/apiserver/pkg/server/filters/with_retry_after.go
  staging/src/k8s.io/apiserver/pkg/server/filters/with_retry_after_test.go
  staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
  staging/src/k8s.io/apiserver/pkg/server/genericapiserver_graceful_termination_test.go
  staging/src/k8s.io/apiserver/pkg/server/lifecycle_signals.go
  staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go
Labels: approved, kind/feature, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent, backports/validated-commits

#898 Bug 1997465: UPSTREAM: 104466: bump k8s.io/util to get fix for LRU cache
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/mount-utils/go.mod
  staging/src/k8s.io/mount-utils/go.sum
  staging/src/k8s.io/pod-security-admission/go.mod
  staging/src/k8s.io/pod-security-admission/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.sum
  vendor/k8s.io/utils/clock/clock.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits

#906 Bug 1994643: UPSTREAM: <carry>: send Retry-After when not ready with a caller opt in
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/filters/patch_optin_retry.go
  staging/src/k8s.io/apiserver/pkg/server/patch_config.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent

#907 Bug 1994643: UPSTREAM: <carry>: sets X-OpenShift-Internal-If-Not-Ready HTTP Header for GC and Namespace controllers
  cmd/kube-controller-manager/app/config/patch.go
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-controller-manager/app/options/options.go
  cmd/kube-controller-manager/app/patch.go
  cmd/kube-controller-manager/app/patch_test.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent

#915 Bug 1948089: openshift-apiserver should not set Available=False APIServicesAvailable on update
  staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-high

#920 Bug 1997657: UPSTREAM: 104577: kubelet: Admission must exclude completed pods and avoid races
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/pod_workers.go
  pkg/kubelet/pod_workers_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#908 Bug 1994927: Revert "Remove Endpoints write access from aggregated edit role"
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#909 Bug 1992016: UPSTREAM: <carry>: add OPENSHIFT_MAX_HOUSEKEEPING_INTERVAL_DURATION and OPENSHIFT_EVICTION_MONITORING_PERIOD_DURATION
  cmd/kubelet/app/options/globalflags_linux.go
  pkg/kubelet/cadvisor/cadvisor_linux.go
  pkg/kubelet/kubelet.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
