Repository openshift/kubernetes, pull requests merged in 2021-11, with the labels that each got.

#1030 Bug 2018516: 4.9: bump(github.com/openshift/*): make go.{mod,sum} point to 1.22.1
  go.mod
  go.sum
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/cluster-bootstrap/go.mod
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/csi-translation-lib/go.mod
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.mod
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.mod
  staging/src/k8s.io/kube-scheduler/go.mod
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.mod
  staging/src/k8s.io/pod-security-admission/go.mod
  staging/src/k8s.io/pod-security-admission/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.mod
  staging/src/k8s.io/sample-controller/go.mod
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1014 Bug 2000216: Image policy should mutate DeploymentConfigs, StatefulSets, and new CronJobs
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/apis/imagepolicy/v1/defaults.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagereferencemutators/pods.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1031 UPSTREAM: <carry>: update rebase doc
  REBASE.openshift.md
Labels: approved, lgtm, backports/validated-commits

#1022 Bug 2002759: UPSTREAM: <carry>: verify required http2 cipher suites
  openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver.go
  openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1033 Bug 2018442: Image policy should mutate DeploymentConfigs, StatefulSets, and new CronJobs
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/apis/imagepolicy/v1/defaults.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/matcher.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1038 Bug 2021936: Read k8s version from hyperkube Dockerfile
  openshift-hack/lib/build/version.sh
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#988 Bug 2007495: UPSTREAM: 105213: remove StartedPodsErrorsTotal metrice message
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/kubelet/metrics/metrics.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#1051 Bug 2022811: UPSTREAM: 106382: defer close the rotated log open
  pkg/kubelet/kuberuntime/logs/logs.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#563 Bug 1926724: UPSTREAM: 98028: add auto update for priority & fairness bootstrap configuration objects
  pkg/registry/flowcontrol/ensurer/flowschema.go
  pkg/registry/flowcontrol/ensurer/flowschema_test.go
  pkg/registry/flowcontrol/ensurer/prioritylevelconfiguration.go
  pkg/registry/flowcontrol/ensurer/prioritylevelconfiguration_test.go
  pkg/registry/flowcontrol/ensurer/strategy.go
  pkg/registry/flowcontrol/rest/storage_flowcontrol.go
  pkg/registry/flowcontrol/rest/storage_flowcontrol_test.go
  staging/src/k8s.io/api/flowcontrol/v1beta1/types.go
  staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go
  staging/src/k8s.io/apimachinery/pkg/util/wait/wait_test.go
  staging/src/k8s.io/apiserver/pkg/apis/flowcontrol/bootstrap/default.go
Labels: kind/bug, approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, qe-approved, backport-risk-assessed

#1050 Bug 2020644: Image policy should mutate DeploymentConfigs, StatefulSets, and new CronJobs
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/apis/imagepolicy/v1/defaults.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, backport-risk-assessed

#1059 Bug 2023779: Fix patch 104847
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/pod_workers.go
  pkg/kubelet/pod_workers_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1049 Bug 1978528: UPSTREAM: <carry>: bump cadvisor for 2957, 2999 and 2979 upstream patches
  go.mod
  go.sum
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  vendor/github.com/google/cadvisor/container/crio/factory.go
  vendor/github.com/google/cadvisor/container/factory.go
  vendor/github.com/google/cadvisor/container/libcontainer/handler.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-low

#1062 UPSTREAM: <carry>: delay queuing deletion for PV to allow nodes some time to unmount
  pkg/controller/volume/persistentvolume/pv_controller.go
  pkg/controller/volume/persistentvolume/pv_controller_base.go
Labels: approved, lgtm

#1040 Rebase Automation Script
  REBASE.openshift.md
  openshift-hack/rebase.sh
Labels: approved, kind/feature, lgtm, backports/validated-commits

#1052 [4.10] Bug 2017276: UPSTREAM: 105934: Don't guess SELinux support on error
  pkg/volume/csi/csi_mounter.go
  pkg/volume/util/hostutil/fake_hostutil.go
  pkg/volume/util/hostutil/hostutil_linux.go
  pkg/volume/util/hostutil/hostutil_linux_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits, qe-approved, backport-risk-assessed

#1053 [4.9] Bug 2022740: UPSTREAM: 106259: Don't guess SELinux support on error
  pkg/volume/csi/csi_mounter.go
  pkg/volume/util/hostutil/fake_hostutil.go
  pkg/volume/util/hostutil/hostutil_linux.go
  pkg/volume/util/hostutil/hostutil_linux_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, backport-risk-assessed

#1069 Bug 2017027: UPSTREAM: <drop>: bump apiserver-library-go
  go.mod
  go.sum
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/matcher.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1065 Bug 2008532: Fix subpath sources check
  pkg/volume/util/subpath/subpath_linux.go
  pkg/volume/util/subpath/subpath_linux_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, backports/validated-commits, backport-risk-assessed

#1039 UPSTREAM: <drop>: remove creation of openshift-infra ns and recycler SA
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-controller-manager/app/patch_recycler.go
Labels: approved, lgtm, backports/validated-commits

#1073 Bug 2022188: Image policy should mutate DeploymentConfigs, StatefulSets, and new CronJobs
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/kubectl/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/apis/imagepolicy/v1/defaults.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, backport-risk-assessed

#1066 Bug 2024967: Fix subpath unmount error
  pkg/volume/util/subpath/subpath_linux.go
  pkg/volume/util/subpath/subpath_linux_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backports/validated-commits, backport-risk-assessed
