Repository openshift/kubernetes, pull requests merged in 2021-07, with the labels that each got.

#839 Bug 1977383: Update resource quota test for compatibility with service ca configmap publishing
  test/e2e/apimachinery/resource_quota.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#841 Bug 1977920: Ensure scc compatibility with BoundServiceAccountTokenVolume
  go.mod
  go.sum
  pkg/security/podsecuritypolicy/util/util_test.go
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/cluster-bootstrap/go.mod
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/csi-translation-lib/go.mod
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.mod
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.mod
  staging/src/k8s.io/kube-scheduler/go.mod
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.mod
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.mod
  staging/src/k8s.io/sample-controller/go.mod
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/util/util.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#837 UPSTREAM: 103385: Fix Multi-AZ test
  test/e2e/framework/node/resource.go
  test/e2e/storage/ubernetes_lite_volumes.go
Labels: approved, backports/validated-commits, lgtm

#842 Bug 1977924: [release-4.8] Ensure scc compatibility with BoundServiceAccountTokenVolume
  go.mod
  go.sum
  pkg/security/podsecuritypolicy/util/util_test.go
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/cluster-bootstrap/go.mod
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/csi-translation-lib/go.mod
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.mod
  staging/src/k8s.io/kube-proxy/go.mod
  staging/src/k8s.io/kube-scheduler/go.mod
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/metrics/go.mod
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-cli-plugin/go.mod
  staging/src/k8s.io/sample-controller/go.mod
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/util/util.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm, vendor-update

#843 Bug 1977383: [release-4.7] Fix watch conformance test
  test/e2e/apimachinery/BUILD
  test/e2e/apimachinery/watch.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#831 UPSTREAM: <carry>: add CSI migration feature gates for GCE PD and Azure Disk
  pkg/features/patch_kube_features.go
  pkg/volume/csimigration/patch_adc_plugin_manager.go
Labels: approved, lgtm

#846 UPSTREAM: <drop>: bump(apiserver-library-go)
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/accept.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#834 Bug 1977383: [release-4.7] Ensure service ca configmap is created in all namespaces
  cmd/kube-controller-manager/app/certificates.go
  cmd/kube-controller-manager/app/controllermanager.go
  openshift-kube-controller-manager/servicecacertpublisher/metrics.go
  openshift-kube-controller-manager/servicecacertpublisher/metrics_test.go
  openshift-kube-controller-manager/servicecacertpublisher/publisher.go
  openshift-kube-controller-manager/servicecacertpublisher/publisher_test.go
  pkg/security/podsecuritypolicy/util/util.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-role-bindings.yaml
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#691 Bug 1951727: Speed up PV provisioning for vsphere driver (ocp-4.6)
  staging/src/k8s.io/legacy-cloud-providers/vsphere/shared_datastore.go
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/virtualmachine.go
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved, vendor-update

#822 UPSTREAM: <drop>: remove the openshift authenticator from the apiserver
  go.mod
  openshift-kube-apiserver/authentication/oauth/bootstrapauthenticator.go
  openshift-kube-apiserver/authentication/oauth/expirationvalidator.go
  openshift-kube-apiserver/authentication/oauth/expirationvalidator_test.go
  openshift-kube-apiserver/authentication/oauth/interfaces.go
  openshift-kube-apiserver/authentication/oauth/rankedset/rankedset.go
  openshift-kube-apiserver/authentication/oauth/rankedset/rankedset_test.go
  openshift-kube-apiserver/authentication/oauth/timeoutvalidator.go
  openshift-kube-apiserver/authentication/oauth/tokenauthenticator.go
  openshift-kube-apiserver/authentication/oauth/tokenauthenticator_test.go
  openshift-kube-apiserver/authentication/oauth/uidvalidator.go
  pkg/kubeapiserver/authenticator/config.go
  pkg/kubeapiserver/authenticator/patch_authenticator.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/fake/doc.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/fake/fake_oauth_client.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/fake/fake_oauthaccesstoken.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/fake/fake_oauthauthorizetoken.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/fake/fake_oauthclient.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/fake/fake_oauthclientauthorization.go
  vendor/github.com/openshift/client-go/oauth/clientset/versioned/typed/oauth/v1/fake/fake_useroauthaccesstoken.go
  vendor/github.com/openshift/library-go/pkg/authentication/bootstrapauthenticator/bootstrap.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#807 produce events for readyz going true
  pkg/controlplane/controller.go
  pkg/controlplane/instance.go
  pkg/controlplane/patch.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
  test/integration/events/events_test.go
Labels: approved, lgtm, vendor-update

#806 UPSTREAM: <carry>: annotate audit events for requests during unready phase and graceful termination phase
  staging/src/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
Labels: approved, backports/unvalidated-commits, vendor-update

#852 UPSTREAM: <carry>: add a way to inject a vulnerable, legacy service-c…
  openshift-kube-controller-manager/servicecacertpublisher/publisher.go
Labels: approved, lgtm

#817 Bug 1981477: Do not throw error when we can't get canonical path
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go
Labels: approved, backports/validated-commits, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#857 [release-4.7] bug 1981634: UPSTREAM: <drop>: use the legacy service-ca.crt content for clusters started in 4.7 or before
  openshift-kube-controller-manager/servicecacertpublisher/publisher.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#864 Bug 1981770: UPSTREAM: <drop>: bump(apiserver-library-go)
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/accept.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update
