Repository openshift/kubernetes, pull requests merged in 2021-09, with the labels that each got.

#894 Bug 1981784: UPSTREAM: <drop>: bump(apiserver-library-go)
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apimachinery/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/cluster-bootstrap/go.sum
  staging/src/k8s.io/code-generator/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/cri-api/go.sum
  staging/src/k8s.io/csi-translation-lib/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/accept.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#925 Bug 2000451: UPSTREAM: <drop>: Disable broken sig-storage test
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#904 Bug 1996779: Fix bug with goroutine capturing loop variable
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere_util.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#899 Bug 1996689: Tighten up RestrictedEndpointsAdmission
  openshift-kube-apiserver/admission/network/restrictedendpoints/endpoint_admission.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#930 Bug 1966521: userspace: Don't sync every iptables rule on every service change
  pkg/proxy/iptables/proxier_openshift.go
  pkg/proxy/userspace/proxier.go
  pkg/proxy/userspace/proxier_openshift.go
Labels: approved, lgtm, bugzilla/severity-high

#893 Bugzilla 2001763: UPSTREAM: <carry>: 104437: run etcd healthcheck in the background and…
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/patch_etcd3.go
Labels: approved, lgtm, vendor-update

#948 Bug 2003269: UPSTREAM: 104817: kubelet: Rejected pods should be filtered from admission
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, backports/validated-commits

#950 UPSTREAM: <drop>: bump openshift, k8s to 1.22.1
  go.mod
  go.sum
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/cluster-bootstrap/go.mod
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/csi-translation-lib/go.mod
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.mod
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.mod
  staging/src/k8s.io/kube-scheduler/go.mod
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.mod
  staging/src/k8s.io/pod-security-admission/go.mod
  staging/src/k8s.io/pod-security-admission/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.mod
  staging/src/k8s.io/sample-controller/go.mod
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/oauth/v1/generated.proto
  vendor/github.com/openshift/api/oauth/v1/types.go
  vendor/github.com/openshift/api/oauth/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#952 Bug 2002290: [4.8] userspace: Don't sync every iptables rule on every service change
  pkg/proxy/iptables/proxier_openshift.go
  pkg/proxy/userspace/proxier.go
  pkg/proxy/userspace/proxier_openshift.go
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-high, backports/unvalidated-commits

#939 [release-4.6] Bug 1989061: don't apply defaultAllowPrivilegeEscalation:false when container is privileged
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#940 Bug 1993754: UPSTREAM: 104347: Pass additional flags to subpath mount to avoid fla…
  pkg/volume/util/subpath/subpath_linux.go
  staging/src/k8s.io/mount-utils/fake_mounter.go
  staging/src/k8s.io/mount-utils/mount.go
  staging/src/k8s.io/mount-utils/mount_linux.go
  staging/src/k8s.io/mount-utils/mount_linux_test.go
  staging/src/k8s.io/mount-utils/mount_unsupported.go
  staging/src/k8s.io/mount-utils/mount_windows.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, backports/validated-commits

#957 UPSTREAM: <carry>: add control plane to allowed roles
  staging/src/k8s.io/kubelet/pkg/apis/well_known_labels.go
Labels: approved, lgtm, vendor-update

#938 Bug 1999133: kubelet: Handle UID reuse in pod worker
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/pod_workers.go
  test/e2e_node/mirror_pod_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#965 Bug 2005182: UPSTREAM: <carry>: update list of deprecated apis to be removed
  openshift-kube-apiserver/filters/deprecatedapirequest/deprecated.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#953 Bug 2002291: [4.7]: userspace: Don't sync every iptables rule on every…
  pkg/proxy/iptables/proxier_openshift.go
  pkg/proxy/userspace/proxier.go
  pkg/proxy/userspace/proxier_openshift.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high, backports/unvalidated-commits

#964 [release-4.9] BUG 2005108: UPSTREAM: 104847: Handle UID reuse in pod worker
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/pod_workers.go
  test/e2e_node/mirror_pod_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved, backports/validated-commits

#941 Bug 1993753: UPSTREAM: 104348: Pass additional flags to subpath mount to avoid fla…
  pkg/volume/util/subpath/subpath_linux.go
  staging/src/k8s.io/mount-utils/fake_mounter.go
  staging/src/k8s.io/mount-utils/mount.go
  staging/src/k8s.io/mount-utils/mount_linux.go
  staging/src/k8s.io/mount-utils/mount_linux_test.go
  staging/src/k8s.io/mount-utils/mount_unsupported.go
  staging/src/k8s.io/mount-utils/mount_windows.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, qe-approved

#942 Bug 1993752: UPSTREAM: 104340: Pass additional flags to subpath mount to avoid fla…
  cmd/kubelet/app/server.go
  pkg/volume/util/subpath/BUILD
  pkg/volume/util/subpath/subpath_fake_mounter.go
  pkg/volume/util/subpath/subpath_linux.go
  pkg/volume/util/subpath/subpath_linux_test.go
  pkg/volume/util/subpath/subpath_mount.go
  pkg/volume/util/subpath/subpath_mount_linux.go
  pkg/volume/util/subpath/subpath_mount_unsupported.go
  pkg/volume/util/subpath/subpath_mount_windows.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, qe-approved

#963 UPSTREAM: <carry>: openshift-hack/images/os/Dockerfile: Add io.openshift.build.versions, etc.
  openshift-hack/images/os/Dockerfile
Labels: approved, lgtm

#959 etcd-client starts retrying transient errors from the etcd cluster
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
Labels: approved, lgtm, vendor-update

#961 Add CSI migration feature gates for vSphere and Azure File
  pkg/features/patch_kube_features.go
  pkg/volume/csimigration/patch_adc_plugin_manager.go
Labels: approved, lgtm

#905 Remove Error Message for Unsupported Volume Test
  test/e2e/storage/testsuites/volumemode.go
Labels: approved, lgtm, backports/validated-commits

#971 Bug 1965368: UPSTREAM: <drop>: bump(apiserver-library-go)
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/quota/clusterresourcequota/admission.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#980 Bug 2000754: UPSTREAM: 104865: e2e iperf2 change threshold to 10MBps = 80 Mbps
  test/e2e/network/networking_perf.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#984 UPSTREAM: <carry>: allow SCC to be disabled on a per-namespace basis
  openshift-kube-apiserver/admission/admissionenablement/admission_config.go
  openshift-kube-apiserver/admission/namespaceconditions/decorator.go
Labels: approved, lgtm
