Repository openshift/kubernetes, pull requests merged in 2021-03, with the labels that each got.

#599 UPSTREAM: 96984: APF e2e: wait for steady state before proceeding
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  test/e2e/apimachinery/BUILD
  test/e2e/apimachinery/flowcontrol.go
Labels: approved, backports/unvalidated-commits, lgtm

#588 use hardcoded authorizer for metrics
  go.mod
  go.sum
  openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/apiserver/pkg/server/options/authorization.go
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.mod
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  vendor/github.com/openshift/library-go/pkg/authorization/hardcodedauthorizer/metrics.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#608 UPSTREAM: 91295: kubectl explain: detect resource group in case there…
  staging/src/k8s.io/kubectl/pkg/cmd/explain/explain.go
  staging/src/k8s.io/kubectl/pkg/explain/explain.go
Labels: approved, backports/validated-commits, lgtm, vendor-update

#598 UPSTREAM: <carry>: allow kubelet to self-authorize metrics scraping
  cmd/kubelet/app/auth.go
  cmd/kubelet/app/patch_auth.go
Labels: approved, lgtm, vendor-update

#609 UPSTREAM: <carry>: provide events, messages, and bodies for probe failures of important pods
  pkg/kubelet/prober/patch_prober.go
  pkg/kubelet/prober/prober.go
  pkg/probe/http/http.go
  pkg/probe/http/patch_http.go
Labels: approved, lgtm

#628 UPSTREAM: 96856: e2e network policy enclose IPv6 destinations
  test/e2e/network/network_policy.go
Labels: approved, backports/validated-commits, lgtm

#596 Bug 1933624: 4.6: UPSTREAM: 96751: Lower the frequency of volume plugin deprecation warning
  pkg/volume/BUILD
  pkg/volume/plugins.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#626 Ensure multi-az test is run in the serial job
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
  test/e2e/scheduling/ubernetes_lite.go
Labels: approved, backports/validated-commits, lgtm

#606 improves the apiserver graceful shutdown procedure
  cmd/kube-apiserver/app/server.go
Labels: approved, lgtm, vendor-update

#616 UPSTREAM: <carry>: kube-apiserver: ignore SIGTERM/INT after the first one
  cmd/kube-apiserver/app/server.go
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-scheduler/app/server.go
  cmd/kubelet/app/server.go
  staging/src/k8s.io/apiextensions-apiserver/main.go
  staging/src/k8s.io/apiserver/pkg/server/signal.go
  staging/src/k8s.io/kube-aggregator/main.go
Labels: approved, lgtm, vendor-update

#637 upstream: 99817: Fix zero-value custom resource validation with go1.16
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiextensions-apiserver/test/integration/validation_test.go
  staging/src/k8s.io/apimachinery/go.mod
  staging/src/k8s.io/apimachinery/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/cluster-bootstrap/go.sum
  staging/src/k8s.io/code-generator/go.mod
  staging/src/k8s.io/code-generator/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/cri-api/go.sum
  staging/src/k8s.io/csi-translation-lib/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/mount-utils/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.sum
  vendor/k8s.io/kube-openapi/pkg/schemaconv/smd.go
  vendor/k8s.io/kube-openapi/pkg/util/util.go
  vendor/k8s.io/kube-openapi/pkg/validation/validate/type.go
  vendor/modules.txt
Labels: approved, backports/validated-commits, lgtm, vendor-update

#602 UPSTREAM: 98305: kube-proxy: clear conntrack entries after rules are in place
  pkg/proxy/iptables/BUILD
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_test.go
Labels: backports/validated-commits

#639 Bug 1942630: UPSTREAM: 96789: Choosing the right source VIP for local endpoints
  pkg/proxy/winkernel/proxier.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#634 Bug 1941000: get AZ of cinder volume from cinder and not from metadata
  staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#629 UPSTREAM: <carry>: rate limit initial watch storm from kubelets on apiserver restart
  openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain.go
  openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain_test.go
Labels: approved, lgtm
