Repository openshift/kubernetes, pull requests merged in 2021-06, with the labels that each got.

#749 Add "local-with-fallback" externalTrafficPolicy hack
  pkg/proxy/iptables/proxier.go
Labels: approved, backports/unvalidated-commits, lgtm

#783 Bug 1948311: UPSTREAM: 102107: client-go: add retry logic for Watch and Stream
  staging/src/k8s.io/client-go/rest/request.go
  staging/src/k8s.io/client-go/rest/request_test.go
  staging/src/k8s.io/client-go/rest/with_retry.go
  staging/src/k8s.io/client-go/rest/with_retry_test.go
Labels: approved, backports/validated-commits, bugzilla/severity-urgent, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#737 Bug 1958329: UPSTREAM: 97428: add more context to log after a request times out
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/finisher/finisher.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/finisher/finisher_test.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest_test.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/update.go
  staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go
  staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#770 Bug 1953127: UPSTREAM: <drop>: work around broken NetPol DNS rules
  test/e2e/network/netpol/network_policy.go
  test/e2e/network/netpol/policies.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#786 Bug 1946479: UPSTREAM: 101950: Make watch order conformance test reliable
  test/e2e/apimachinery/watch.go
Labels: approved, backports/validated-commits, bugzilla/valid-bug, lgtm

#779 Bug 1958371: UPSTREAM: 98424: register all pending pod deletions and check for kill
  pkg/kubelet/cm/BUILD
  pkg/kubelet/cm/devicemanager/BUILD
  pkg/kubelet/cm/devicemanager/device_plugin_stub.go
  pkg/kubelet/cm/fake_container_manager.go
  pkg/kubelet/cm/fake_pod_container_manager.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#773 Bug 1964492: UPSTREAM: 102171: Implement support for watch initialization in P&F
  openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain.go
  openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain_test.go
  staging/src/k8s.io/apiserver/pkg/server/filters/maxinflight.go
  staging/src/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go
  staging/src/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher_whitebox_test.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher_test.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/apf_context.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#736 Bug 1927397: UPSTREAM: 98028: add auto update for priority & fairness bootstrap configuration objects
  pkg/registry/flowcontrol/ensurer/flowschema.go
  pkg/registry/flowcontrol/ensurer/flowschema_test.go
  pkg/registry/flowcontrol/ensurer/prioritylevelconfiguration.go
  pkg/registry/flowcontrol/ensurer/prioritylevelconfiguration_test.go
  pkg/registry/flowcontrol/ensurer/strategy.go
  pkg/registry/flowcontrol/rest/storage_flowcontrol.go
  pkg/registry/flowcontrol/rest/storage_flowcontrol_test.go
  staging/src/k8s.io/api/flowcontrol/v1beta1/types.go
  staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go
  staging/src/k8s.io/apimachinery/pkg/util/wait/wait_test.go
  staging/src/k8s.io/apiserver/pkg/apis/flowcontrol/bootstrap/default.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#681 Bug 1967745: Add DNS custom resource admission
  openshift-kube-apiserver/admission/customresourcevalidation/attributes.go
  openshift-kube-apiserver/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  openshift-kube-apiserver/admission/customresourcevalidation/dns/validate_dns.go
  openshift-kube-apiserver/admission/customresourcevalidation/dns/validate_dns_test.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/doc.go
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
  vendor/github.com/openshift/api/operator/v1/types_config.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_csi_snapshot.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_kubestorageversionmigrator.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_scheduler.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#583 UPSTREAM: <carry>: kubelet: add ehashman as reviewer
  pkg/kubelet/DOWNSTREAM_OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#784 Bug 1966410: UPSTREAM: <carry>: apiserver: add system_client=kube-{apiserver,cm,s} to apiserver_request_total
  staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  staging/src/k8s.io/apiserver/pkg/server/healthz/healthz_test.go
  test/instrumentation/testdata/stable-metrics-list.yaml
  test/integration/metrics/metrics_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#785 Bug 1967591: UPSTREAM: <carry>: do not mutate pods when it has a container with both CPU request and limit
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission.go
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#792 Bug 1948311: UPSTREAM: 102606: Bring back "client-go: add retry logic for Watch and Stream" and fix test flake
  staging/src/k8s.io/client-go/rest/request_test.go
Labels: approved, backports/validated-commits, bugzilla/severity-urgent, bugzilla/valid-bug, kind/failing-test, kind/flake, lgtm, vendor-update

#790 Bug 1965545: vendor: bump runc to rc95 + "unit exists" fix
  go.mod
  go.sum
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/common.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#794 Bug 1966410: kube-apiserver: add system_client=cluster-policy-controller to apiserver_request_total
  staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
Labels: approved, bugzilla/valid-bug, lgtm, vendor-update

#796 Bug 1969626: UPSTREAM: 102587: kubelet: Revert "Cleanup portforward streams after their usage"
  pkg/kubelet/cri/streaming/portforward/httpstream.go
  pkg/kubelet/cri/streaming/portforward/httpstream_test.go
  staging/src/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  staging/src/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  staging/src/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection_test.go
  staging/src/k8s.io/client-go/tools/portforward/portforward_test.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#798 Bug 1950010: UPSTREAM: <carry>: apirequestcount: smear out CR updates over interval
  openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller.go
Labels: approved, backports/validated-commits, bugzilla/valid-bug, lgtm

#740 Bug 1959420: fix a 4.6 test flake
  test/e2e/framework/service/jig.go
Labels: approved, backports/validated-commits, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#788 Bug 1954509: UPSTREAM: multiple: Fix corruption of FibreChannel volumes
  go.mod
  go.sum
  pkg/volume/fc/attacher.go
  pkg/volume/fc/fc.go
  pkg/volume/iscsi/iscsi.go
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/code-generator/examples/go.sum
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/mount-utils/go.mod
  staging/src/k8s.io/mount-utils/go.sum
  staging/src/k8s.io/mount-utils/mount_helper_unix.go
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.sum
  vendor/k8s.io/utils/io/read.go
  vendor/k8s.io/utils/mount/README.md
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#731 BUG 1927359: Add support for gathering metrics from CSI block-mode volumes
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  pkg/kubelet/kubelet_volumes.go
  pkg/kubelet/kubelet_volumes_test.go
  pkg/kubelet/server/server_test.go
  pkg/kubelet/server/stats/handler.go
  pkg/kubelet/server/stats/testing/mock_stats_provider.go
  pkg/kubelet/server/stats/volume_stat_calculator.go
  pkg/kubelet/server/stats/volume_stat_calculator_test.go
  pkg/volume/awsebs/aws_ebs_block.go
  pkg/volume/azuredd/azure_dd_block.go
  pkg/volume/cinder/cinder_block.go
  pkg/volume/csi/csi_block.go
  pkg/volume/csi/csi_plugin.go
  pkg/volume/fc/fc.go
  pkg/volume/gcepd/gce_pd_block.go
  pkg/volume/iscsi/iscsi.go
  pkg/volume/local/local.go
  pkg/volume/metrics_block.go
  pkg/volume/metrics_block_test.go
  pkg/volume/metrics_errors.go
  pkg/volume/metrics_nil.go
  pkg/volume/metrics_nil_test.go
  pkg/volume/rbd/rbd.go
  pkg/volume/volume.go
  pkg/volume/vsphere_volume/vsphere_volume_block.go
  test/e2e/storage/volume_metrics.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, kind/bug, lgtm

#802 Bug 1950993: UPSTREAM: <drop>: bump cadvisor for 2868 upstream patch
  go.mod
  go.sum
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  vendor/github.com/google/cadvisor/container/common/helpers.go
  vendor/github.com/google/cadvisor/manager/manager.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#804 Bug 1971745: only chown if non-windows machine with projected volumes
  pkg/volume/util/atomic_writer.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#810 UPSTREAM: <carry>: crd: add ClusterOperator condition message table column
  go.mod
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd_test.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/tableconvertor/patch_clusteroperators.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/tableconvertor/tableconvertor.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/tableconvertor/tableconvertor_test.go
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.mod
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#813 Bug 1971808: fix local-with-fallback
  pkg/proxy/iptables/proxier.go
Labels: approved, backports/unvalidated-commits, bugzilla/invalid-bug, bugzilla/severity-high

#818 UPSTREAM: <carry>: update rebase doc
  REBASE.openshift.md
Labels: approved, lgtm

#825 Bug 1975283: update Multi-AZ Cluster Volumes test name
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, kind/bug, kind/failing-test, lgtm

#824 UPSTREAM: <carry>: update rebase doc
  REBASE.openshift.md
Labels: approved, lgtm

#832 Bug 1976379: UPSTREAM: <carry>: Reject the pod creation when we can not decide the cluster type
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission.go
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#823 UPSTREAM: 103050: Bug 1975325: Fix NodeAuthenticator tests in dual stack
  test/e2e/auth/node_authn.go
Labels: approved, backports/validated-commits, bugzilla/severity-medium, bugzilla/valid-bug, kind/bug, lgtm
