Repository openshift/kubernetes, pull requests merged in 2021-10, with the labels that each got.

#989 UPSTREAM: 103783: Only use dualstack if the node and config supports it
  cmd/kube-proxy/app/server.go
  cmd/kube-proxy/app/server_others.go
  cmd/kube-proxy/app/server_windows.go
  pkg/proxy/winkernel/proxier.go
  pkg/proxy/winkernel/proxier_test.go
Labels: backports/unvalidated-commits

#993 Bug 2010348: UPSTREAM: 105352: revert pie build mode
  hack/lib/golang.sh
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, backports/validated-commits

#999 Bug 1997478: Ensure terminal pods maintain terminal status
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_pods_test.go
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/status/status_manager_test.go
  test/e2e/node/pods.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, backports/validated-commits

#1000 [release-4.9] Bug 2011050: Ensure terminal pods maintain terminal status
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_pods_test.go
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/status/status_manager_test.go
  test/e2e/node/pods.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved, backports/validated-commits

#1007 Bug 2011513: kubelet: do not arbitrarily create a podSyncStatus for finished pods
  pkg/kubelet/pod_workers.go
  pkg/kubelet/pod_workers_test.go
  test/e2e_node/restart_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent
