Repository openshift/kubernetes, pull requests merged in 2021-04, with the labels that each got.

#644 UPSTREAM: 97295: Fix staticcheck in test/integration/{examples,framework}
  hack/.staticcheck_failures
  test/integration/examples/apiserver_test.go
  test/integration/framework/etcd.go
  test/integration/framework/test_server.go
Labels: approved, backports/validated-commits, lgtm

#648 Revert "UPSTREAM: 97295: Fix staticcheck in test/integration/{examples,framework}"
  hack/.staticcheck_failures
  test/integration/examples/apiserver_test.go
  test/integration/framework/etcd.go
  test/integration/framework/test_server.go
Labels: approved, backports/validated-commits, lgtm

#638 KS with preferred host support
  cmd/kube-scheduler/app/config/config.go
  cmd/kube-scheduler/app/config/patch.go
  cmd/kube-scheduler/app/options/options.go
  cmd/kube-scheduler/app/options/patch.go
  cmd/kube-scheduler/app/patch.go
  cmd/kube-scheduler/app/server.go
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/apiserver/pkg/server/options/authentication.go
  staging/src/k8s.io/apiserver/pkg/server/options/authorization.go
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  vendor/github.com/openshift/library-go/pkg/config/client/transport.go
  vendor/github.com/openshift/library-go/pkg/monitor/health/metrics.go
  vendor/github.com/openshift/library-go/pkg/monitor/health/options.go
  vendor/github.com/openshift/library-go/pkg/monitor/health/prober.go
  vendor/github.com/openshift/library-go/pkg/monitor/health/target_resolver.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#651 UPSTREAM: <carry>: Disable CSI migration on OpenStack Cinder
  pkg/features/kube_features.go
Labels: approved, lgtm

#652 UPSTREAM: <carry>: bump tag version
  REBASE.openshift.md
  openshift-hack/images/hyperkube/Dockerfile.rhel
Labels: approved, lgtm

#601 <carry>: enable CSI migration gates in Attach/Detach controller
  pkg/controller/volume/attachdetach/attach_detach_controller.go
  pkg/features/patch_kube_features.go
  pkg/volume/csimigration/patch_adc_plugin_manager.go
  pkg/volume/csimigration/plugin_manager.go
Labels: approved, lgtm

#633 UPSTREAM: <carry>: Add Dockerfile to build pause image
  build/pause/Dockerfile.Rhel
Labels: approved, bugzilla/valid-bug, lgtm

#656 BUG 1948703: UPSTREAM: 100678: apf: exempt probes /healthz /livez /readyz
  staging/src/k8s.io/apiserver/pkg/apis/flowcontrol/bootstrap/default.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#665 bug 1934085: UPSTREAM: 100128: [sig-scheduling] SchedulerPreemption|SchedulerPredicates|SchedulerPriorities: adjust some e2e tests to run in a single node cluster scenario
  test/e2e/scheduling/predicates.go
  test/e2e/scheduling/preemption.go
  test/e2e/scheduling/priorities.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#672 Bug 1949721: UPSTREAM: 99237: Use the audit ID of a request for better correlation
  cmd/kube-scheduler/app/server.go
  staging/src/k8s.io/apiserver/pkg/audit/request.go
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/audit.go
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/audit_test.go
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/with_auditid.go
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/with_auditid_test.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/helpers.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/trace_util.go
  staging/src/k8s.io/apiserver/pkg/endpoints/request/auditid.go
  staging/src/k8s.io/apiserver/pkg/endpoints/request/auditid_test.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go
  staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
  staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go
  staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go
  staging/src/k8s.io/controller-manager/app/serve.go
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy_test.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#674 Bug 1949050: UPSTREAM: 101147: Limit image spec's hash length
  test/utils/image/manifest.go
  test/utils/image/manifest_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#642 Bug 1945856: 99729:Only system-node-critical pods should be OOM Killed last
  pkg/kubelet/qos/policy.go
  pkg/kubelet/qos/policy_test.go
  pkg/kubelet/types/pod_update.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#675 bug 1949306: UPSTREAM: <carry>: DeprecatedAPIRequestHandler unit tests
  openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller_test.go
  openshift-kube-apiserver/filters/deprecatedapirequest/request_counts_test.go
  openshift-kube-apiserver/filters/deprecatedapirequest/update_func.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#627 Bug 1949661: UPSTREAM: <carry>: management pinning annotations
  pkg/kubelet/cm/cpumanager/cpu_manager.go
  pkg/kubelet/cm/qos_container_manager_linux.go
  pkg/kubelet/config/file_linux.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_node_status.go
  pkg/kubelet/managed/cpu_shares.go
  pkg/kubelet/managed/managed.go
  pkg/kubelet/managed/managed_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#673 Bug 1934400: bump(apiserver-library-go): scc-admission: don't apply defaultAllowPrivilegeEscalation:false when container is privileged
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#682 Bug 1951042: fix crash when killing container fails
  pkg/kubelet/kuberuntime/kuberuntime_container.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#684 bug 1949306: UPSTREAM: <carry>: keep apirequestcounts for non-persisted users between updates
  go.mod
  go.sum
  openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller.go
  openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller_test.go
  openshift-kube-apiserver/filters/deprecatedapirequest/deprecated.go
  openshift-kube-apiserver/filters/deprecatedapirequest/request_counts.go
  openshift-kube-apiserver/filters/deprecatedapirequest/request_counts_test.go
  openshift-kube-apiserver/filters/deprecatedapirequest/update_func.go
  openshift-kube-apiserver/filters/deprecatedapirequest/v1helpers/helpers.go
  openshift-kube-apiserver/filters/deprecatedapirequest_filter.go
  openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.mod
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  vendor/github.com/openshift/api/apiserver/v1/apiserver.openshift.io_apirequestcount.yaml
  vendor/github.com/openshift/api/apiserver/v1/register.go
  vendor/github.com/openshift/api/apiserver/v1/types_apirequestcount.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/apiserver/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/typed/apiserver/v1/apirequestcount.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/typed/apiserver/v1/apiserver_client.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/typed/apiserver/v1/generated_expansion.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#687 Bug 1951558: UPSTREAM: 101093: Fix startupProbe behaviour changed
  pkg/kubelet/prober/worker.go
  pkg/kubelet/prober/worker_test.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#696 Bug 1949050: UPSTREAM: 101337: Remove Limits from scheduling e2e balanced pod reso…
  test/e2e/scheduling/priorities.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#693 Bug 1949050: UPSTREAM: 101287: Fail fast when image is specified w/o tag
  test/e2e/generated/bindata.go
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  test/utils/image/manifest.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#661 Bug 1937299: Fix mounting partitions on NVMe devices
  pkg/volume/awsebs/aws_util.go
Labels: approved, backports/validated-commits, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#683 Bug 1951467: fix loop bug for verify attached volume
  pkg/volume/util/operationexecutor/operation_executor.go
Labels: approved, backports/validated-commits, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#667 Bug 1944631: openshift authenticator: don't allow old-style tokens
  openshift-kube-apiserver/authentication/oauth/bootstrapauthenticator.go
  openshift-kube-apiserver/authentication/oauth/expirationvalidator_test.go
  openshift-kube-apiserver/authentication/oauth/tokenauthenticator.go
  openshift-kube-apiserver/authentication/oauth/tokenauthenticator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#694 Bug 1945104: UPSTREAM: 101186: Fix RBAC of generic ephemeral volumes controller
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#699 Bug 1952333: UPSTREAM: 101306: Additional CVE-2021-3121 fix
  staging/src/k8s.io/apimachinery/pkg/api/resource/quantity_proto.go
Labels: approved, backports/validated-commits, bugzilla/severity-medium, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#662 Bug 1948953: UPSTREAM: <carry>: Set informer for openstack
  plugin/pkg/admission/storage/persistentvolume/label/admission.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#654 Bug 1948311: UPSTREAM: 100959: DelegatingAuthenticationOptions: TokenReview reques…
  cmd/kube-controller-manager/app/options/options_test.go
  staging/src/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go
  staging/src/k8s.io/apiserver/pkg/server/options/authentication.go
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook_v1_test.go
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook_v1beta1_test.go
  staging/src/k8s.io/cloud-provider/options/options_test.go
Labels: approved, backports/validated-commits, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#632 UPSTREAM: <carry>: Provide a new admission plugin to mutate management pods CPUs requests
  openshift-kube-apiserver/admission/admissionenablement/register.go
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission.go
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission_test.go
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/doc.go
Labels: approved, bugzilla/valid-bug, lgtm

#655 Bug 1953127: Re-enable [Feature:NetworkPolicy] tests which were wrongly disabled in rebase
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#647 Bug 1953555: UPSTREAM: <carry>: Skip GlusterFS tests
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#704 Bug 1927263: UPSTREAM: 99336: kubelet: improve the node informer sync check
  pkg/kubelet/config/apiserver.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_getters.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#715 bug 1954638: UPSTREAM: <carry>: apirequest count with empty .status.removedInRelease
  openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller_test.go
  openshift-kube-apiserver/filters/deprecatedapirequest/deprecated.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#685 Bug 1951585: Addresses build error pause
  build/pause/Dockerfile.Rhel
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, kind/bug, lgtm

#689 bug 1954634: UPSTREAM: <carry>: honor max users
  openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller_test.go
  openshift-kube-apiserver/filters/deprecatedapirequest/update_func.go
  openshift-kube-apiserver/filters/deprecatedapirequest/v1helpers/helpers.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#697 Bug 1952917: UPSTREAM: 100228: For LoadBalancer Service type don't create a HNS policy for empty or invalid external loadbalancer IP
  pkg/proxy/winkernel/proxier.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#719 Bug 1954972: openshift-kube-apiserver/admission: fix featuregates resource name
  openshift-kube-apiserver/admission/customresourcevalidation/features/validate_features.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#709 Bug 1952224: kubelet: do not cleanup volumes if pod is being killed
  pkg/kubelet/kubelet_test.go
  pkg/kubelet/kubelet_volumes.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#700 UPSTREAM: 101280: Bug 1913974: Force NodeUnstageVolume to finish for all distros
  test/e2e/storage/testsuites/snapshottable.go
Labels: approved, backports/validated-commits, bugzilla/severity-medium, bugzilla/valid-bug, kind/bug, lgtm
