Repository openshift/kubernetes, pull requests merged in 2021-02, with the labels that each got.

#541 Bug 1920368: UPSTREAM: 98019: specify the container CPU set during the creation
  pkg/kubelet/cm/BUILD
  pkg/kubelet/cm/container_manager_linux.go
  pkg/kubelet/cm/cpumanager/cpu_manager.go
  pkg/kubelet/cm/cpumanager/cpu_manager_test.go
  pkg/kubelet/cm/cpumanager/fake_cpu_manager.go
  pkg/kubelet/cm/cpuset/cpuset.go
  pkg/kubelet/cm/fake_internal_container_lifecycle.go
  pkg/kubelet/cm/internal_container_lifecycle.go
  pkg/kubelet/cm/internal_container_lifecycle_linux.go
  pkg/kubelet/cm/internal_container_lifecycle_unsupported.go
  pkg/kubelet/cm/internal_container_lifecycle_windows.go
  pkg/kubelet/dockershim/helpers_linux.go
  pkg/kubelet/kuberuntime/kuberuntime_container.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#545 Bug 1896558: Revert undesired multi az skip
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, backports/unvalidated-commits, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#546 Bug 1917803: UPSTREAM: 98187: Skip PD tests on 1 node cluster
  test/e2e/storage/pd.go
Labels: approved, backports/validated-commits, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#510 Bug 1894645: UPSTREAM: 89885: SQUASH: Fix cinder crash
  staging/src/k8s.io/legacy-cloud-providers/openstack/openstack.go
Labels: approved, backports/unvalidated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#551 Bug 1915085: UPSTREAM: 98424: register all pending pod deletions and check for kill
  pkg/kubelet/cm/BUILD
  pkg/kubelet/cm/fake_container_manager.go
  pkg/kubelet/cm/fake_pod_container_manager.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#549 BUG 1924870: UPSTREAM: 96901: plumb context with request deadline
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  pkg/kubeapiserver/server/insecure_handler.go
  staging/src/k8s.io/apiserver/pkg/audit/BUILD
  staging/src/k8s.io/apiserver/pkg/endpoints/apiserver_test.go
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/BUILD
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/request_deadline.go
  staging/src/k8s.io/apiserver/pkg/endpoints/filters/request_deadline_test.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest_test.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/update.go
  staging/src/k8s.io/apiserver/pkg/server/BUILD
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go
  staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go
  staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
  test/e2e/apimachinery/BUILD
  test/e2e/apimachinery/request_timeout.go
  test/integration/apiserver/admissionwebhook/timeout_test.go
Labels: approved, backports/unvalidated-commits, bugzilla/severity-high, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#547 Bug 1896558: Balance nodes in scheduling e2e
  test/e2e/scheduling/ubernetes_lite.go
Labels: approved, backports/validated-commits, bugzilla/severity-medium, bugzilla/valid-bug, kind/flake, lgtm

#555 Bug 1925493: Enable snapshot tests
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, backports/unvalidated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#557 Bug 1926285: UPSTREAM: <carry>: ignore not found errors in status messages
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
Labels: approved, backports/unvalidated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#558 Bug 1926484: UPSTREAM: <carry>: kube-apiserver: ignore SIGTERM/INT after the first one
  cmd/kube-apiserver/app/server.go
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-scheduler/app/server.go
  cmd/kubelet/app/server.go
  staging/src/k8s.io/apiextensions-apiserver/main.go
  staging/src/k8s.io/apiserver/pkg/server/signal.go
  staging/src/k8s.io/kube-aggregator/main.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#564 Bug 1927391: UPSTREAM: 98939: fixes race in TestSyncPodsDeletesWhenSourcesAreReady
  pkg/kubelet/kubelet_test.go
Labels: approved, backports/unvalidated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#428 BUG 1891107: UPSTREAM: 95259: allocate service-account flowschema to global-default
  staging/src/k8s.io/apiserver/pkg/apis/flowcontrol/bootstrap/default.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, kind/api-change, kind/bug, lgtm

#513 Bug 1876918: Move deferred taint cleanup call to ensure all are removed
  test/e2e/framework/node/resource.go
  test/e2e/scheduling/priorities.go
Labels: approved, backports/validated-commits, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#309 Bug 1897918: UPSTREAM: 93861: apiserver: add --permit-address-sharing flag to listen with SO_REUSEADDR
  staging/src/k8s.io/apiserver/pkg/server/options/serving.go
  staging/src/k8s.io/apiserver/pkg/server/options/serving_unix.go
  staging/src/k8s.io/apiserver/pkg/server/options/serving_windows.go
Labels: approved, backports/unvalidated-commits, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#573 add failure details for SCC not used
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/kubectl/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/modules.txt
Labels: approved, backports/unvalidated-commits, lgtm, vendor-update

#572 Bug 1929012: UPSTREAM: 96984: APF e2e: wait for steady state before proceeding
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  test/e2e/apimachinery/BUILD
  test/e2e/apimachinery/flowcontrol.go
Labels: approved, backports/unvalidated-commits, bugzilla/severity-medium, bugzilla/valid-bug, group-lead-approved, lgtm

#574 Bug 1919737: UPSTREAM: <carry>: Prefer local endpoint for cluster DNS service
  pkg/proxy/iptables/proxier.go
Labels: backports/unvalidated-commits, bugzilla/invalid-bug, bugzilla/severity-urgent, kind/bug

#578 UPSTREAM: 98956: Fix race when KillPod followed by IsPodPendingTermining
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_test.go
Labels: approved, backports/validated-commits, lgtm

#580 Bug 1908378: kubelet: fix create sandbox delete pod race
  pkg/kubelet/kuberuntime/fake_kuberuntime_manager.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
  staging/src/k8s.io/cri-api/pkg/apis/testing/fake_runtime_service.go
Labels: approved, backports/unvalidated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#526 Bug 1916489: (e2e/scheduler) Ensure minimum memory limit in createBalancedPodForNodes
  test/e2e/scheduling/priorities.go
Labels: approved, backports/validated-commits, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#584 Bug 1931103: UPSTREAM: 96958: kubelet: remove periodic messages from log-level 2
  pkg/kubelet/cm/container_manager_linux.go
  pkg/kubelet/nodestatus/setters.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#587 UPSTREAM: 99199: delay serving CRD creates for a few seconds for HA consistency
  staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
Labels: approved, lgtm, vendor-update

#593 Bug 1885717: UPSTREAM: 98742: Sync completed pods until their containers have been terminated
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_test.go
Labels: approved, backports/validated-commits, bugzilla/severity-low, bugzilla/valid-bug, kind/bug, lgtm

#594 Bug 1932097: UPSTREAM: 98571: kubelet: Stop probing a pod during graceful shutdown
  pkg/kubelet/prober/worker.go
  pkg/kubelet/prober/worker_test.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm
