Repository openshift/kubernetes, pull requests merged in 2021-05, with the labels that each got.

#717 Bug 1954770: UPSTREAM: 99095: Prevent Kubelet stuck in DiskPressure when imagefs minreclaim is set
  pkg/kubelet/eviction/eviction_manager.go
  pkg/kubelet/eviction/eviction_manager_test.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#723 Bug 1953555: UPSTREAM: <carry>: Skip GlusterFS tests
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#706 Bug 1952666: UPSTREAM: <carry>: management workloads enhancement 741(uint64)
  pkg/kubelet/cm/cpumanager/cpu_manager.go
  pkg/kubelet/cm/qos_container_manager_linux.go
  pkg/kubelet/config/file.go
  pkg/kubelet/config/file_linux.go
  pkg/kubelet/managed/managed.go
  pkg/kubelet/managed/managed_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#716 Bug 1954696: UPSTREAM: <carry>: add apirequestcount useragent
  openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller.go
  openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller_test.go
  openshift-kube-apiserver/filters/deprecatedapirequest/request_counts.go
  openshift-kube-apiserver/filters/deprecatedapirequest/request_counts_test.go
  openshift-kube-apiserver/filters/deprecatedapirequest/update_func.go
  openshift-kube-apiserver/filters/deprecatedapirequest_filter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#729 Bug 1949612: UPSTREAM: 101708: Fix log spam for du failure on pod etc-hosts metrics
  pkg/kubelet/stats/host_stats_provider.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, kind/bug, lgtm

#711 UPSTREAM: 98305: kube-proxy: clear conntrack
  pkg/proxy/iptables/BUILD
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_test.go
Labels: backports/validated-commits

#733 Bug 1956898: UPSTREAM: 99748: kubelet: fix log files being overwritten on containe…
  pkg/kubelet/kuberuntime/kuberuntime_container.go
  pkg/kubelet/kuberuntime/kuberuntime_container_test.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#732 Bug 1956895: UPSTREAM: 101593: kubelet: change cgroup move message to log level 3
  pkg/kubelet/cm/container_manager_linux.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#721 Bug 1955231: UPSTREAM: 101345: kubelet: improve the node informer sync check
  pkg/kubelet/config/apiserver.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_getters.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#735 bug 1957502: UPSTREAM: <carry>: correct apirequestcount lock
  openshift-kube-apiserver/filters/deprecatedapirequest/request_counts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#692 Bug 1951815: UPSTREAM: 99393: kubelet: reduce configmap and secret watch
  pkg/kubelet/configmap/configmap_manager.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/secret/secret_manager.go
  pkg/kubelet/util/manager/watch_based_manager.go
  pkg/kubelet/util/manager/watch_based_manager_test.go
  test/integration/kubelet/watch_manager_test.go
Labels: approved, backports/validated-commits, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#708 Bug 1923847: openshift-kube-apiserver: use github.com/openshift/apiserver-library-go/pkg/labelselector
  go.mod
  go.sum
  openshift-kube-apiserver/admission/scheduler/nodeenv/admission.go
  openshift-kube-apiserver/admission/scheduler/nodeenv/admission_test.go
  openshift-kube-apiserver/admission/scheduler/nodeenv/labelselector/labelselector_test.go
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/labelselector/labelselector.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#741 Bug 1959471: Conformance tests (sysctls) may not be excluded
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, backports/validated-commits, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#701 Bug 1884800: Reduce names of vsphere volumes even further
  pkg/volume/vsphere_volume/vsphere_volume_util.go
Labels: approved, backports/validated-commits, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#635 Bug 1942141: fixes cinder PV labelling
  plugin/pkg/admission/storage/persistentvolume/label/admission.go
  staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#690 Bug 1951726: Speed up PV provisioning for vsphere driver (ocp-4.7)
  staging/src/k8s.io/legacy-cloud-providers/vsphere/shared_datastore.go
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/virtualmachine.go
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#743 UPSTREAM: 101067: Bug 1946459: fix nfs storage ipv6 add square brackets
  pkg/volume/nfs/nfs.go
  pkg/volume/nfs/nfs_test.go
Labels: approved, backports/validated-commits, bugzilla/severity-medium, bugzilla/valid-bug, kind/bug, lgtm

#752 Bug 1960780: UPSTREAM: <carry>: Use policyv1beta1
  test/e2e/framework/service/jig.go
  test/e2e/upgrades/network/services.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#565 Bug 1945091: Don't force-disable IPv6, dual-stack, and SCTP tests
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
  openshift-hack/test-kubernetes-e2e.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#669 Bug 1948311: Handle 429 errors from watch requests in reflector
  staging/src/k8s.io/client-go/tools/cache/reflector.go
  staging/src/k8s.io/client-go/tools/cache/reflector_test.go
Labels: approved, backports/validated-commits, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#738 Bug 1952460: UPSTREAM: 101488: e2e/network/firewall: don't assume nodes are exposed externally
  test/e2e/network/firewall.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#636 Bug 1942146: Fix labels of Cinder PVs
  plugin/pkg/admission/storage/persistentvolume/label/admission.go
  staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, vendor-update

#759 Bug 1963079: KCM with preferred host support
  cmd/kube-controller-manager/app/config/patch.go
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-controller-manager/app/options/options.go
  cmd/kube-controller-manager/app/patch.go
  staging/src/k8s.io/controller-manager/pkg/clientbuilder/client_builder_dynamic.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#760 UPSTREAM: 102089: Bug 1961644: Add Node IP IPv6 formatting in NodeAuthenticator tests
  test/e2e/auth/node_authn.go
Labels: approved, backports/validated-commits, bugzilla/severity-medium, bugzilla/valid-bug, kind/bug, lgtm

#762 Bug 1939968: UPSTREAM: 102001: Ref counting is only applicable to Remote endpoints
  pkg/proxy/winkernel/proxier.go
Labels: backports/validated-commits, bugzilla/invalid-bug, bugzilla/severity-high

#764 UPSTREAM: <carry>: Fix dns endpoints hack (to be squashed)
  pkg/proxy/iptables/proxier.go
Labels: approved, backports/unvalidated-commits

#767 Bug 1964197: UPSTREAM: 102224: Fix expired unit test certs
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy_test.go
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/README.md
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/client-ca-key.pem
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/client-ca.pem
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/client-key.pem
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/client.pem
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/generate.client-ca.json
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/generate.client.json
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/generate.profiles.json
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/generate.server-ca.json
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/generate.server.json
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/generate.sh
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/server-ca-key.pem
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/server-ca.pem
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/server-key.pem
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata/server.pem
Labels: approved, backports/validated-commits, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, vendor-update

#768 UPSTREAM: <carry>: update rebase doc
  REBASE.openshift.md
Labels: approved, bugzilla/valid-bug, lgtm

#771 Bug 1960205: UPSTREAM: <carry>: verbosity of managed workloads logging
  pkg/kubelet/cm/cpumanager/cpu_manager.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, kind/bug, lgtm

#769 Bug 1913974: UPSTREAM: 102021: Update snapshotting tests to use volumeHandle for CSI volumes when waiting for NodeUnpublish
  test/e2e/storage/testsuites/snapshottable.go
Labels: approved, backports/validated-commits, bugzilla/severity-medium, bugzilla/valid-bug, kind/bug, lgtm

#756 Bug 1961925: UPSTREAM: <carry>: Does not prevent pod creation because of no nodes reason when it runs under the regular cluster
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission.go
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission_test.go
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/initializers.go
  openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/build.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/console.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/image.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/network.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/project.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/scheduler.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/build.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/console.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/image.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/network.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/project.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/scheduler.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#763 Bug 1963263: UPSTREAM: 102000: Ref counting is only applicable to Remote endpoints
  pkg/proxy/winkernel/proxier.go
Labels: approved, backports/validated-commits, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
