Repository openshift/kubernetes, pull requests merged in 2021-12, with the labels that each got.

#1079 UPSTREAM: <drop>: revert to go1.16
  .ci-operator.yaml
Labels: approved, backports/unvalidated-commits

#1054 [4.8] Bug 2022741: UPSTREAM: 106260: Don't guess SELinux support on error
  pkg/kubelet/volumemanager/cache/actual_state_of_world.go
  pkg/volume/csi/csi_mounter.go
  pkg/volume/util/hostutil/fake_hostutil.go
  pkg/volume/util/hostutil/hostutil_linux.go
  pkg/volume/util/hostutil/hostutil_linux_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, qe-approved, backport-risk-assessed

#1078 UPSTREAM: 105910: retry PV create in e2e-test on API quota failure
  test/e2e/autoscaling/cluster_size_autoscaling.go
  test/e2e/framework/pv/pv.go
  test/e2e/framework/timeouts.go
  test/e2e/storage/flexvolume_mounted_volume_resize.go
  test/e2e/storage/flexvolume_online_resize.go
  test/e2e/storage/framework/volume_resource.go
  test/e2e/storage/nfs_persistent_volume-disruptive.go
  test/e2e/storage/persistent_volumes-gce.go
  test/e2e/storage/persistent_volumes-local.go
  test/e2e/storage/persistent_volumes.go
  test/e2e/storage/ubernetes_lite_volumes.go
  test/e2e/storage/volume_metrics.go
  test/e2e/storage/vsphere/persistent_volumes-vsphere.go
Labels: approved, lgtm, backports/validated-commits

#1037 Bug 2021629: UPSTREAM: <carry>: api request counts for current hour are incorrect
  openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller.go
  openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller_test.go
  openshift-kube-apiserver/filters/deprecatedapirequest/request_counts.go
  openshift-kube-apiserver/filters/deprecatedapirequest/update_func.go
  openshift-kube-apiserver/filters/deprecatedapirequest/v1helpers/helpers.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/typed/apiserver/v1/fake/doc.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/typed/apiserver/v1/fake/fake_apirequestcount.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/typed/apiserver/v1/fake/fake_apiserver_client.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1055 [4.7] Bug 2022720: UPSTREAM: 106261: Don't guess SELinux support on error
  pkg/kubelet/volumemanager/cache/actual_state_of_world.go
  pkg/volume/csi/csi_mounter.go
  pkg/volume/util/hostutil/BUILD
  pkg/volume/util/hostutil/fake_hostutil.go
  pkg/volume/util/hostutil/hostutil_linux.go
  pkg/volume/util/hostutil/hostutil_linux_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, qe-approved, backport-risk-assessed

#1056 [4.6] Bug 2023306: UPSTREAM: 106261: Don't guess SELinux support on error
  pkg/kubelet/volumemanager/cache/actual_state_of_world.go
  pkg/volume/csi/csi_mounter.go
  pkg/volume/util/hostutil/BUILD
  pkg/volume/util/hostutil/fake_hostutil.go
  pkg/volume/util/hostutil/hostutil_linux.go
  pkg/volume/util/hostutil/hostutil_linux_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, qe-approved, backport-risk-assessed

#1092 [release-4.8] Bug 2032325: UPSTREAM: <carry>: api request counts for current hour are incorrect
  openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller.go
  openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller_test.go
  openshift-kube-apiserver/filters/deprecatedapirequest/request_counts.go
  openshift-kube-apiserver/filters/deprecatedapirequest/update_func.go
  openshift-kube-apiserver/filters/deprecatedapirequest/v1helpers/helpers.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/typed/apiserver/v1/fake/doc.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/typed/apiserver/v1/fake/fake_apirequestcount.go
  vendor/github.com/openshift/client-go/apiserver/clientset/versioned/typed/apiserver/v1/fake/fake_apiserver_client.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, backport-risk-assessed

#1067 Bug 2024995: Fix subpath source check
  pkg/volume/util/subpath/subpath_linux.go
  pkg/volume/util/subpath/subpath_linux_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backports/validated-commits, qe-approved, backport-risk-assessed

#1068 Bug 2024996: Fix subpath source check
  pkg/volume/util/subpath/subpath_linux.go
  pkg/volume/util/subpath/subpath_linux_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backports/validated-commits, qe-approved, backport-risk-assessed
