Repository openshift/kubernetes, pull requests merged in 2021-01, with the labels that each got.

#490 Bug 1897603: UPSTREAM: 96673: Fix Cinder volume detection on OpenStack Train
  staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#505 add sjenning and mrunalp to approvers and reviewers
  pkg/kubelet/OWNERS
Labels: approved, lgtm

#489 Bug 1903346: UPSTREAM: 97013: Fix FibreChannel volume plugin corrupting filesystem on detach
  pkg/volume/fc/attacher.go
  pkg/volume/fc/fc.go
  pkg/volume/fc/fc_test.go
  pkg/volume/fc/fc_util.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#492 Bug 1896244: UPSTREAM: 96467: Add GinkgoRecover to a local storage go routine
  test/e2e/storage/persistent_volumes-local.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#500 Bug 1908389: UPSTREAM: 97635: Cherry pick 443 and 448 from cloud provider azure
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer_test.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_standard.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_standard_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, kind/bug, kind/failing-test, lgtm, vendor-update

#507 Bug 1913096: UPSTREAM: 97006: kubelet: Fix cadvisor machine metrics
  pkg/kubelet/kubelet.go
  pkg/kubelet/server/server.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#508 Bug 1912563: UPSTREAM: 97323: fix the deadlock in priority and fairness config controller
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/BUILD
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/controller_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#509 Bug 1912563: UPSTREAM: 97206: clean up executing request on panic
  staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
  staging/src/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#491 Bug 1895329: UPSTREAM: 96751: Lower the frequency of volume plugin deprecation warning
  pkg/volume/BUILD
  pkg/volume/plugins.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#493 Bug 1908407: UPSTREAM: 95269: Fix panic when kubelet register if a node object already exists with no Status.Capacity or Status.Allocatable
  pkg/kubelet/kubelet_node_status.go
  pkg/kubelet/kubelet_node_status_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#516 BUG 1913525: UPSTREAM: 97820: handle webhook authenticator and authorizer error
  staging/src/k8s.io/apiserver/pkg/util/webhook/webhook_test.go
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
  staging/src/k8s.io/apiserver/plugin/pkg/authorizer/webhook/webhook.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#515 Bug 1899760: UPSTREAM: 96754: reduce buckets for etcd_request_duration_seconds
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#512 Bug 1877812: UPSTREAM: 96889: Fix loopback device lookup
  pkg/volume/util/volumepathhandler/volume_path_handler_linux.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#483 adds a unit test for checking if graceful shutdown of HTTP2 server works
  staging/src/k8s.io/apiserver/pkg/server/graceful_shutdown_test.go
Labels: approved, lgtm

#487 UPSTREAM: <carry>: (squash) Add detail to rebase doc
  REBASE.openshift.md
Labels: approved, lgtm

#494 Bug 1903999: Httplog response code is always zero
  staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go
  staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, vendor-update

#520 Bug 1915582: UPSTREAM: 97860: move all variables in sampleAndWaterMarkHistograms::innerSet
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/metrics/sample_and_watermark.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, kind/bug, lgtm, vendor-update

#523 Bug 1908880: UPSTREAM: 97980: kubelet: revert checking sandbox deletion
  pkg/kubelet/BUILD
  pkg/kubelet/container/runtime.go
  pkg/kubelet/container/testing/fake_runtime.go
  pkg/kubelet/container/testing/runtime_mock.go
  pkg/kubelet/cri/remote/fake/fake_runtime.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_pods_test.go
  pkg/kubelet/kuberuntime/kuberuntime_container.go
  pkg/kubelet/kuberuntime/kuberuntime_gc.go
  pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
  pkg/kubelet/kuberuntime/kuberuntime_sandbox.go
  pkg/kubelet/kuberuntime/kuberuntime_sandbox_test.go
  pkg/kubelet/pod_sandbox_deleter.go
  pkg/kubelet/pod_sandbox_deleter_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#502 Bug 1912564: UPSTREAM: 97206: clean up executing request on panic
  staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, kind/bug, lgtm

#415 Bug 1841119: UPSTREAM: <carry>: kube-controller-manager: allow running bare kube-controller-manager
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-controller-manager/app/patch.go
  cmd/kube-controller-manager/app/patch_flags.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#501 Bug 1912564: UPSTREAM: 97323: fix the deadlock in priority and fairness config controller
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/BUILD
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/controller_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, kind/bug, lgtm

#445 Bug 1889420: Add dangling volume check for vsphere
  staging/src/k8s.io/legacy-cloud-providers/vsphere/nodemanager.go
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere_util.go
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere_volume_map.go
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere_volume_map_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, vendor-update

#530 bug 1915945: UPSTREAM: 96990: Increase preemption timeout from 1 minute to 2 minutes
  test/e2e/scheduling/predicates.go
  test/e2e/scheduling/preemption.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#527 Bug 1899941: Override termination grace period on annotation
  pkg/kubelet/kuberuntime/kuberuntime_container.go
Labels: approved, lgtm

#518 Bug 1915247: UPSTREAM: 97915: kube-aggregator: fix apiservice availability gauge
  staging/src/k8s.io/kube-aggregator/pkg/controllers/status/BUILD
  staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
  staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller_test.go
  staging/src/k8s.io/kube-aggregator/pkg/controllers/status/metrics.go
  staging/src/k8s.io/kube-aggregator/pkg/controllers/status/metrics_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#531 Bug 1882750: UPSTREAM: 98103: kubelet: Delete static pod gracefully and fix mirrorPodTerminationMap leak
  pkg/kubelet/kubelet.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#521 Bug 1915583: UPSTREAM: 97860: move all variables in sampleAndWaterMarkHistograms::innerSet
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/metrics/sample_and_watermark.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, kind/bug, lgtm

#534 bug 1870342: UPSTREAM: 94684: e2e: Pod should avoid nodes that have avoidPod annotation: clean remaining pods
  test/e2e/scheduling/predicates.go
  test/e2e/scheduling/priorities.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#537 Add DOWNSTREAM_OWNERS as preparation for https://github.com/kubernetes/test-infra/pull/20482
  DOWNSTREAM_OWNERS
  pkg/kubelet/DOWNSTREAM_OWNERS
Labels: approved, lgtm

#525 Bug 1896558: Skip multiaz e2e
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#480 Bug 1894916: Panic output due to timeouts in kube apiserver
  cmd/cloud-controller-manager/app/options/options_test.go
  cmd/controller-manager/app/serve.go
  cmd/kube-controller-manager/app/options/options_test.go
  cmd/kube-scheduler/app/server.go
  pkg/kubeapiserver/server/insecure_handler.go
  staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
  staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go
  staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
  staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go
  staging/src/k8s.io/apiserver/pkg/server/options/authentication.go
  staging/src/k8s.io/apiserver/pkg/server/options/authorization.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#522 Bug 1868645: UPSTREAM: 94087: kubelet: node sync at least once
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_getters.go
  pkg/kubelet/kubelet_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
