Repository openshift/kubernetes, pull requests merged in 2022-06, with the labels that each got.

#1261 Bug 2086092: UPSTREAM: 108284: fix: exclude non-ready nodes and deleted nodes from azure load balancers
  staging/src/k8s.io/legacy-cloud-providers/azure/azure.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_test.go
Labels: kind/bug, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent, backports/validated-commits

#1281 UPSTREAM: <carry>: provide unique reason for pod probe event during t…
  pkg/kubelet/prober/patch_prober.go
Labels: approved, lgtm

#1214 Bug 2063971: UPSTREAM: 104151: delete stale UDP conntrack entries for loadbalancer IPs
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_test.go
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-high, backports/validated-commits

#1282 Bug 2094954: UPSTREAM: 110258: Fix pod eviction ip
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  pkg/api/v1/pod/util.go
  pkg/api/v1/pod/util_test.go
  pkg/controller/endpoint/endpoints_controller.go
  pkg/controller/endpoint/endpoints_controller_test.go
  pkg/controller/endpointslice/reconciler.go
  pkg/controller/util/endpoint/controller_utils.go
  pkg/controller/util/endpoint/controller_utils_test.go
  pkg/kubelet/status/status_manager.go
  test/e2e/network/service.go
  test/e2e/node/pods.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1229 Bug 2065749: UPSTREAM: 109103: cpu/memory manager containerMap memory leak
  pkg/kubelet/cm/containermap/container_map.go
  pkg/kubelet/cm/cpumanager/cpu_manager.go
  pkg/kubelet/cm/memorymanager/memory_manager.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1287 Bug 2087685: Worker Latency Profiles: Config node object validation for extreme profile transition
  openshift-kube-apiserver/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  openshift-kube-apiserver/admission/customresourcevalidation/node/restrict_extreme_worker_latency_profile.go
  openshift-kube-apiserver/admission/customresourcevalidation/node/restrict_extreme_worker_latency_profile_test.go
Labels: kind/bug, approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#1285 Bug 2089933: Backport 110191 Re-enable Kubelet Pod Readiness Probes on Termination and Pod probes should be handled by pod worker
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  pkg/api/v1/pod/util.go
  pkg/api/v1/pod/util_test.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/prober/prober_manager.go
  pkg/kubelet/status/generate.go
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/status/status_manager_test.go
  test/e2e/common/node/container_probe.go
  test/e2e/network/service.go
  test/e2e_node/node_probe.go
  test/e2e_node/node_shutdown_linux_test.go
  test/utils/image/manifest.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1288 Bug 2078778: UPSTREAM: 110408: apiserver: printers should use int64
  pkg/printers/internalversion/printers.go
  pkg/printers/internalversion/printers_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1290 Bug 2086519: get SCC admission default securityContext.runAsNonRoot to true on positive UIDs
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent

#1283 Bug 2063414: UPSTREAM: 109441: kubelet: parseResolvConf: Handle "search ."
  pkg/kubelet/network/dns/dns.go
  pkg/kubelet/network/dns/dns_test.go
Labels: kind/bug, approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits
