Repository openshift/kubernetes, pull requests merged in 2022-04, with the labels that each got.

#1231 Bug 2069311: UPSTREAM: <carry>: use hardcoded rest mapper from library-go
  go.mod
  go.sum
  pkg/kubeapiserver/admission/patch_restmapper.go
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/pod-security-admission/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  vendor/github.com/openshift/library-go/pkg/client/openshiftrestmapper/hardcoded_restmapper.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, backport-risk-assessed

#1230 Bug 2066865: Skip azure topology tests
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#1172 Bug 2051985: UPSTREAM: <carry>: An APIRequestCount without dots in the name can cause a panic
  openshift-kube-apiserver/admission/customresourcevalidation/apirequestcount/validate_apirequestcount.go
  openshift-kube-apiserver/admission/customresourcevalidation/apirequestcount/validate_apirequestcount_test.go
  openshift-kube-apiserver/admission/customresourcevalidation/attributes.go
  openshift-kube-apiserver/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller.go
  openshift-kube-apiserver/filters/deprecatedapirequest/apiaccess_count_controller_test.go
  openshift-kube-apiserver/filters/deprecatedapirequest_filter.go
Labels: kind/bug, approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#1239 Bug 2073153: golang toolchain unsupported parsers tag
  openshift-hack/test-go.sh
  openshift-hack/test-integration.sh
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, backport-risk-assessed

#1170 [release-4.9] Bug 2050632: UPSTREAM: <drop>: Give warning when ipFamilyPolicy implicitly set
  pkg/registry/core/service/storage/patch_rest.go
  pkg/registry/core/service/storage/rest.go
  test/integration/dualstack/dualstack_warnings_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#1225 Bug 1999325: Backport 107821 and 107831
  pkg/kubelet/kubelet.go
  pkg/kubelet/pod/pod_manager.go
  pkg/kubelet/util/manager/cache_based_manager.go
  pkg/kubelet/util/manager/cache_based_manager_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#1245 Bug 2063953: UPSTREAM: <carry>: use hardcoded rest mapper from library-go
  go.mod
  go.sum
  pkg/kubeapiserver/admission/patch_restmapper.go
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  vendor/github.com/openshift/library-go/pkg/client/openshiftrestmapper/hardcoded_restmapper.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, qe-approved, backport-risk-assessed

#1243 Bug 2075621: UPSTREAM: 109487: Disable JobTrackingWithFinalizers due to unresolved bug
  pkg/features/kube_features.go
  test/integration/job/job_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1234 [release-4.7][ART-3664] Bug 2043804: IPs with leading zeros are still valid in the apiserver
  openshift-hack/images/hyperkube/Dockerfile.rhel
  openshift-hack/test-go.sh
  openshift-hack/test-integration.sh
  test/integration/apiserver/cve_2021_29923_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, qe-approved, backport-risk-assessed

#1244 [release-4.10] Bug 2075831: UPSTREAM: 109487: Disable JobTrackingWithFinalizers due to unresolved…
  pkg/features/kube_features.go
  test/integration/job/job_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, backport-risk-assessed
