Repository openshift/kubernetes, pull requests merged in 2022-05, with the labels that each got.

#1213 Bug 2063970: UPSTREAM: 104149: delete stale UDP conntrack entries for loadbalancer IPs
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_test.go
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-high, backports/validated-commits

#1251 Bug 2062459: Identify if there are multiple schedulers running
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1242 [release-4.9] Bug 2075704: Backport 107821 and 107831
  pkg/kubelet/kubelet.go
  pkg/kubelet/pod/pod_manager.go
  pkg/kubelet/util/manager/cache_based_manager.go
  pkg/kubelet/util/manager/cache_based_manager_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backports/validated-commits, backport-risk-assessed

#1266 [release-4.9] Bug 2075704: Revert Backport 107821 and 107831
  pkg/kubelet/kubelet.go
  pkg/kubelet/pod/pod_manager.go
  pkg/kubelet/util/manager/cache_based_manager.go
  pkg/kubelet/util/manager/cache_based_manager_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#1235 [release-4.6][ART-3664] Bug 2043805: IPs with leading zeros are still valid in the apiserver
  openshift-hack/images/hyperkube/Dockerfile.rhel
  openshift-hack/test-go.sh
  openshift-hack/test-integration.sh
  test/integration/apiserver/cve_2021_29923_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, backport-risk-assessed

#1267 [release-4.9] Bug 2075704: Backport 107821 and 107831
  pkg/kubelet/kubelet.go
  pkg/kubelet/pod/pod_manager.go
  pkg/kubelet/util/manager/cache_based_manager.go
  pkg/kubelet/util/manager/cache_based_manager_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backports/validated-commits, backport-risk-assessed

#1268 Bug 2086519: UPSTREAM: <carry>: e2e-framework: don't autosync PodSecurity labels
  test/e2e/framework/framework.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#1269 Fixes probe readiness shutdowns
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go
  pkg/kubelet/prober/prober_manager.go
  pkg/kubelet/prober/testing/fake_manager.go
  test/e2e_node/node_probe.go
Labels: approved, lgtm, bugzilla/valid-bug
