Repository openshift/kubernetes, pull requests merged in 2022-02, with the labels that each got.

#1138 Bug 2044438: UPSTREAM: 107637: backport inotify fix to 4.9
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/mount-utils/go.mod
  staging/src/k8s.io/mount-utils/go.sum
  staging/src/k8s.io/pod-security-admission/go.mod
  staging/src/k8s.io/pod-security-admission/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.sum
  vendor/k8s.io/utils/clock/clock.go
  vendor/k8s.io/utils/inotify/inotify_linux.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#977 bug 1979671: UPSTREAM <carry>: Remove pod warning annotation when workload partitioning is disabled
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission.go
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission_test.go
Labels: kind/bug, approved, lgtm, ok-to-test, vendor-update, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#1156 UPSTREAM: 107847: service REST: Call Decorator(old) on update path
  pkg/registry/core/service/storage/storage.go
  test/integration/service/upgrade_test.go
Labels: kind/bug, approved, lgtm, backports/validated-commits

#1157 Bug 2040533: UPSTREAM: 107900: Pods that have terminated before starting should not block startup
  pkg/kubelet/pod_workers.go
  pkg/kubelet/pod_workers_test.go
  test/e2e_node/mirror_pod_grace_period_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, backports/validated-commits

#1167 Bug 2050247: UPSTREAM: 107902: Merge pull request #107902 from xueqzhan/automated-…
  test/e2e/network/service.go
  test/e2e/network/util.go
Labels: kind/bug, approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low, staff-eng-approved, backports/validated-commits, backport-risk-assessed

#1108 Bug 2039377: UPSTREAM: 89885: SQUASH: Retry fetching clouds.conf
  staging/src/k8s.io/legacy-cloud-providers/openstack/openstack.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1169 [release-4.10] Bug 2050250: Upstream 107900 static pod fix
  pkg/kubelet/pod_workers.go
  pkg/kubelet/pod_workers_test.go
  test/e2e_node/mirror_pod_grace_period_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved, backports/validated-commits, backport-risk-assessed

#1176 Bug 2040533: UPSTREAM: <drop>: Ignore container notfound error while getPodstatuses
  pkg/kubelet/kuberuntime/kuberuntime_container.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent

#1181 Bug 2050250: UPSTREAM: 108164: Ignore container notfound error while getPodstatuses
  pkg/kubelet/kuberuntime/kuberuntime_container.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved

#1184 Bug 2040715: upstream 108149: do not return early in the node informer when there is no change
  staging/src/k8s.io/legacy-cloud-providers/azure/azure.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_test.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent

#1183 Bug 2040715: UPSTREAM 108149: fix: do not return early in the node informer when there is no change
  staging/src/k8s.io/legacy-cloud-providers/azure/azure.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_test.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved, backports/validated-commits, backport-risk-assessed

#1190 Bug 2040715: UPSTREAM: 108284: fix: exclude non-ready nodes from azure load balancer
  staging/src/k8s.io/legacy-cloud-providers/azure/azure.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_test.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent

#1195 Bug 2056948: UPSTREAM: 108284: fix: exclude non-ready nodes from azure load balancer
  staging/src/k8s.io/legacy-cloud-providers/azure/azure.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_test.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved, backport-risk-assessed

#1188 Sdn 4.10 kubernetes 1.23.4
  cmd/kube-proxy/app/server_openshift.go
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_openshift.go
  pkg/proxy/userspace/proxier.go
  pkg/proxy/userspace/proxier_openshift.go
Labels: backports/unvalidated-commits
