Repository openshift/kubernetes, pull requests merged in 2022-03, with the labels that each got.

#1203 [release-4.8] Bug 2060494: Backports inotify leak fix into kubelet
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/mount-utils/go.mod
  staging/src/k8s.io/mount-utils/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.sum
  vendor/k8s.io/utils/clock/clock.go
  vendor/k8s.io/utils/inotify/inotify_linux.go
  vendor/k8s.io/utils/internal/third_party/forked/golang/LICENSE
  vendor/k8s.io/utils/internal/third_party/forked/golang/PATENTS
  vendor/k8s.io/utils/internal/third_party/forked/golang/net/ip.go
  vendor/k8s.io/utils/internal/third_party/forked/golang/net/parse.go
  vendor/k8s.io/utils/net/ipnet.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/parse.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backports/validated-commits, backport-risk-assessed

#1205 [release-4.7] Bug 2060528: Backport inotify patch to 4.7
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/mount-utils/go.mod
  staging/src/k8s.io/mount-utils/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.sum
  vendor/k8s.io/utils/clock/clock.go
  vendor/k8s.io/utils/inotify/inotify_linux.go
  vendor/k8s.io/utils/internal/third_party/forked/golang/LICENSE
  vendor/k8s.io/utils/internal/third_party/forked/golang/PATENTS
  vendor/k8s.io/utils/internal/third_party/forked/golang/net/ip.go
  vendor/k8s.io/utils/internal/third_party/forked/golang/net/parse.go
  vendor/k8s.io/utils/io/read.go
  vendor/k8s.io/utils/mount/README.md
  vendor/k8s.io/utils/net/ipnet.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/parse.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#1173 [release-4.8][ART-3664] Bug 2043808: IPs with leading zeros are still valid in the apiserver
  openshift-hack/images/hyperkube/Dockerfile.rhel
  test/integration/apiserver/cve_2021_29923_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, backport-risk-assessed

#1197 Bug 2034958: enable "Conntrack should be able to preserve UDP traffic when initial…
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: kind/bug, kind/failing-test, approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-unspecified, backports/validated-commits

#1202 [release-4.6] Bug 2060538: Backports inotify leak fix into kubelet
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/csi-translation-lib/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.sum
  vendor/k8s.io/utils/clock/clock.go
  vendor/k8s.io/utils/inotify/inotify_linux.go
  vendor/k8s.io/utils/internal/third_party/forked/golang/LICENSE
  vendor/k8s.io/utils/internal/third_party/forked/golang/PATENTS
  vendor/k8s.io/utils/internal/third_party/forked/golang/net/ip.go
  vendor/k8s.io/utils/internal/third_party/forked/golang/net/parse.go
  vendor/k8s.io/utils/io/read.go
  vendor/k8s.io/utils/mount/OWNERS
  vendor/k8s.io/utils/mount/README.md
  vendor/k8s.io/utils/mount/mount_windows.go
  vendor/k8s.io/utils/net/ipnet.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/parse.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#1201 UPSTREAM:<carry>:Unskip OCP SDN related tests
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits

#1210 Bug 2062459: Generate event when cache update is failed
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#1215 Bug 2063938: UPSTREAM: <carry>: use hardcoded rest mapper from library-go
  go.mod
  pkg/kubeapiserver/admission/patch_restmapper.go
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-controller-manager/go.mod
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/pod-security-admission/go.mod
  staging/src/k8s.io/sample-apiserver/go.mod
  vendor/github.com/openshift/library-go/pkg/client/openshiftrestmapper/hardcoded_restmapper.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-high

#897 Bug 1945329: enable should drop INVALID conntrack entries test
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1199 Bug 2022507: Backport 108366: OutofCpu Fixes
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_test.go
  pkg/kubelet/pod_workers.go
  pkg/kubelet/pod_workers_test.go
  pkg/kubelet/runonce.go
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/status/status_manager_test.go
  pkg/kubelet/status/testing/fake_pod_deletion_safety.go
  pkg/kubelet/status/testing/mock_pod_status_provider.go
  test/e2e/apps/job.go
  test/e2e/node/pods.go
  test/e2e_node/node_shutdown_linux_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1110 Bug 1957668: UPSTREAM: <carry>: use console-public config map for console redirect
  openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain.go
  vendor/github.com/openshift/library-go/pkg/apiserver/httprequest/httprequest.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#1226 UPSTREAM: 106454: test/e2e: fix e2e tests for restricted policy
  test/e2e/scheduling/priorities.go
Labels: approved, lgtm, backports/validated-commits

#1221 [release-4.10] Bug 2065774: Backport 108723 OutofCpu Fixes
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_test.go
  pkg/kubelet/pod_workers.go
  pkg/kubelet/pod_workers_test.go
  pkg/kubelet/runonce.go
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/status/status_manager_test.go
  pkg/kubelet/status/testing/fake_pod_deletion_safety.go
  pkg/kubelet/status/testing/mock_pod_status_provider.go
  test/e2e/apps/job.go
  test/e2e/node/pods.go
  test/e2e_node/node_shutdown_linux_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1222 [release-4.9] Bug 2065786: Backport 108366 OutofCpu Fixes
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_test.go
  pkg/kubelet/pod_workers.go
  pkg/kubelet/pod_workers_test.go
  pkg/kubelet/runonce.go
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/status/status_manager_test.go
  pkg/kubelet/status/testing/fake_pod_deletion_safety.go
  pkg/kubelet/status/testing/mock_pod_status_provider.go
  test/e2e/apps/job.go
  test/e2e/node/pods.go
  test/e2e_node/node_shutdown_linux_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1204 UPSTREAM: <carry>: update list of deprecated apis
  openshift-kube-apiserver/filters/deprecatedapirequest/deprecated.go
Labels: kind/bug, approved, lgtm, backports/validated-commits

#1218 bump apiserver-library-go
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/seccomp/strategy.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/seccomp/types.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/seccomp/withseccomp.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, backports/validated-commits

#1227 UPSTREAM: 106454: test/e2e: fix e2e tests for restricted policy
  test/e2e/scheduling/ubernetes_lite.go
  test/e2e/storage/volume_metrics.go
Labels: approved, lgtm, backports/validated-commits
