Repository openshift/kubernetes, pull requests merged in 2022-10, with the labels that each got.

#1385 Branch SDN-4.10-1.24.4: Do not force DNS service endpoints to be local when endpoint isnt ready
  pkg/proxy/iptables/proxier.go
Labels: lgtm, backports/unvalidated-commits

#1387 Branch sdn-4.8-kubernetes-1.21.1: Do not force DNS service endpoints to be local
  pkg/proxy/iptables/proxier.go
Labels: backports/unvalidated-commits

#1386 Branch sdn-4.9-kubernetes-1.22.0-rc.0: Do not force DNS service endpoints to be local
  pkg/proxy/iptables/proxier.go
Labels: backports/unvalidated-commits

#1388 UPSTREAM: <carry>: allow annotating with a specific suite
  openshift-hack/e2e/annotate/annotate.go
Labels: approved, lgtm, backports/validated-commits

#1391 Bug 2041317: Fix replica calculation at start of HPA scaling policy period
  pkg/controller/podautoscaler/horizontal.go
  pkg/controller/podautoscaler/horizontal_test.go
Labels: kind/bug, approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#1394 UPSTREAM: 113135: Wait for pod not running or gone in storage tests
  test/e2e/framework/pod/wait.go
  test/e2e/storage/ubernetes_lite_volumes.go
Labels: approved, lgtm, backports/validated-commits

#1340 UPSTREAM: <carry>: Bug 2098054: tag AWS security group at creation
  staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
  staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#1396 UPSTREAM: 113208: Set default test timeouts first, only then modify the required ones
  test/e2e/storage/drivers/in_tree.go
Labels: approved, lgtm, backports/validated-commits

#1398 UPSTREAM: <carry>: Wait for default service account in node authorizer test
  test/e2e/auth/node_authn.go
  test/e2e/auth/node_authz.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug

#1400 OCPBUGS-2774: UPSTREAM: 112807 Fix Load balancer services with xTP local
  staging/src/k8s.io/cloud-provider/controllers/service/controller.go
  staging/src/k8s.io/cloud-provider/controllers/service/controller_test.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits, jira/severity-critical, jira/valid-bug
