Repository openshift/kubernetes, pull requests merged in 2022-01, with the labels that each got.

#1098 Bug 2034705: UPSTREAM 107136: Don't log vSphere configuration data in storage e2e tests
  test/e2e/storage/vsphere/config.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#1096 Bug 2001442: empty termination.log file for the kube-apiserver has too permissive mode
  cmd/watch-termination/main.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1115 Bug 2026380: Image policy should mutate DeploymentConfigs, StatefulSets, and new CronJobs
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/apis/imagepolicy/v1/defaults.go
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagepolicy.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, qe-approved, backport-risk-assessed

#1114 Bug 1933144: hardens the aggregated API e2e tests in an HA setup
  test/e2e/apimachinery/aggregator.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1129 Bug 2042493: UPSTREAM: <carry>: Fix conformance and serial tests by stopping node cordoning
  openshift-hack/conformance-k8s.sh
  openshift-hack/test-kubernetes-e2e.sh
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1121 Bug 2039414: UPSTREAM: <carry>: allows for switching KS to talk to Kube API over localhost-squash to other
  cmd/kube-scheduler/app/patch.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1124 Bug 2042493: UPSTREAM 107564: kube-apiserver integration test: allow IPs with leading zeros on the API
  test/integration/apiserver/cve_2021_29923_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1122 Bug 2041641: Backport k8s.io/utils fix for a memory leak within the inotify utilities
  go.mod
  go.sum
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apimachinery/go.mod
  staging/src/k8s.io/apimachinery/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/cluster-bootstrap/go.sum
  staging/src/k8s.io/code-generator/examples/go.sum
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/csi-translation-lib/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/mount-utils/go.mod
  staging/src/k8s.io/mount-utils/go.sum
  staging/src/k8s.io/pod-security-admission/go.mod
  staging/src/k8s.io/pod-security-admission/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.sum
  vendor/k8s.io/utils/clock/clock.go
  vendor/k8s.io/utils/clock/testing/fake_clock.go
  vendor/k8s.io/utils/inotify/inotify_linux.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent

#1099 Bug 2004542: UPSTREAM: 89885: SQUASH: Retry fetching clouds.conf
  staging/src/k8s.io/legacy-cloud-providers/openstack/openstack.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1112 Bug 2038968: Restore upstream feature gates
  pkg/features/kube_features.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1119 Bug 2040793: Fix ordering issues with snapshot e2e
  test/e2e/storage/testsuites/snapshottable.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#1123 Bug 2042169: UPSTREAM: <carry>: remove egressnetworkpolicies from gc ignored resources
  cmd/kube-controller-manager/app/patch_gc.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits

#1104 Bug 2022824: Fix the leak of vSphere client sessions
  test/e2e/storage/drivers/in_tree.go
Labels: kind/bug, approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1130 Bug 2039539: UPSTREAM: <drop>: revert upstream PR 106306
  staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  test/instrumentation/testdata/stable-metrics-list.yaml
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent

#1140 Bug 2040533: UPSTREAM: 107695: kubelet: fix podstatus not containing pod full name
  pkg/kubelet/pod_workers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#1136 Bug 2041583: UPSTREAM: <carry>: set correctly static pods CPUs when workload partitioning is disabled
  pkg/kubelet/cm/cpumanager/cpu_manager.go
  pkg/kubelet/managed/managed.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1125 Bug 2040338: UPSTREAM: <carry>: remove egressnetworkpolicies from gc ignored resources
  cmd/kube-controller-manager/app/patch_gc.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backports/validated-commits, backport-risk-assessed

#1143 Bug 2039539: Revert "UPSTREAM: <drop>: revert upstream PR 106306"
  staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  test/instrumentation/testdata/stable-metrics-list.yaml
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent, backports/validated-commits

#1153 Bug 2044824: UPSTREAM: 107786: Ensure the execHostnameTest() compares hostnames
  test/e2e/network/service.go
  test/e2e/network/util.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low, backports/validated-commits
