Repository openshift/kubernetes, pull requests merged in 2022-11, with the labels that each got.

#1404 OCPBUGS-3084: UPSTREAM: 113481: kubelet: fix pod log line corruption when using timestamps and long lines
  pkg/kubelet/kuberuntime/logs/logs.go
  pkg/kubelet/kuberuntime/logs/logs_test.go
Labels: approved, lgtm, bugzilla/valid-bug, backports/validated-commits, jira/valid-bug

#1401 OCPBUGS-2946: Revert: 1340: tag AWS security group at creation
  staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
  staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits, qe-approved, jira/severity-critical, jira/valid-bug

#1405 OCPBUGS-3071: 4.12: revert: 1340: tag AWS security group at creation
  staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
  staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits, jira/severity-critical, jira/valid-bug

#1406 UPSTREAM: <drop>: Bump library-go.
  go.mod
  go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/pod-security-admission/go.mod
  staging/src/k8s.io/pod-security-admission/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#1411 OCPBUGS-3093: Tag AWS security groups at creation
  staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
  staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits, qe-approved, jira/valid-bug

#1412 OCPBUGS-3094: Tag AWS security groups at creation
  staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
  staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits, jira/valid-bug

#1415 [release-4.10] OCPBUGS-3434: UPSTREAM: 113517: kubelet: fix pod log line corruption when using timestamps and long lines
  pkg/kubelet/kuberuntime/logs/logs.go
  pkg/kubelet/kuberuntime/logs/logs_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug

#1402 Bug OCPBUGS-2991: Disable expansion in SC, if driver does not support it
  test/e2e/storage/testsuites/ephemeral.go
Labels: approved, lgtm, bugzilla/valid-bug, backports/validated-commits, jira/severity-important, jira/valid-bug

#1395 bug 2117374: UPSTREAM: <drop>: update apiserver-library-go to add message about wo…
  go.mod
  go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent

#1403 Bug OCPBUGS-2927: Disable expansion in SC, if driver does not support it
  test/e2e/storage/testsuites/ephemeral.go
Labels: approved, lgtm, bugzilla/valid-bug, backports/validated-commits, jira/severity-important, jira/valid-bug

#1416 OCPBUGS-3499: UPSTREAM: <carry>: Add validation plugin for CRD-based route parity.
  openshift-kube-apiserver/admission/customresourcevalidation/attributes.go
  openshift-kube-apiserver/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  openshift-kube-apiserver/admission/customresourcevalidation/route/validate_route.go
  vendor/github.com/openshift/library-go/pkg/route/validation/validation.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits, jira/valid-bug

#1423 [release-4.12] OCPBUGS-3503: UPSTREAM: <drop>: Bump library-go.
  go.mod
  go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/pod-security-admission/go.mod
  staging/src/k8s.io/pod-security-admission/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits, jira/valid-bug

#1419 OCPBUGS-3501: UPSTREAM: <carry>: Add host assignment plugin for CRD-based routes.
  openshift-kube-apiserver/admission/admissionenablement/register.go
  openshift-kube-apiserver/admission/route/apis/hostassignment/doc.go
  openshift-kube-apiserver/admission/route/apis/hostassignment/register.go
  openshift-kube-apiserver/admission/route/apis/hostassignment/types.go
  openshift-kube-apiserver/admission/route/apis/hostassignment/v1/doc.go
  openshift-kube-apiserver/admission/route/apis/hostassignment/v1/register.go
  openshift-kube-apiserver/admission/route/apis/hostassignment/v1/types.go
  openshift-kube-apiserver/admission/route/apis/hostassignment/v1/zz_generated.conversion.go
  openshift-kube-apiserver/admission/route/apis/hostassignment/v1/zz_generated.deepcopy.go
  openshift-kube-apiserver/admission/route/apis/hostassignment/zz_generated.deepcopy.go
  openshift-kube-apiserver/admission/route/hostassignment/admission.go
  vendor/github.com/openshift/library-go/pkg/authorization/authorizationutil/subject.go
  vendor/github.com/openshift/library-go/pkg/authorization/authorizationutil/util.go
  vendor/github.com/openshift/library-go/pkg/route/hostassignment/assignment.go
  vendor/github.com/openshift/library-go/pkg/route/hostassignment/plugin.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits, jira/valid-bug

#1410 UPSTREAM: <carry>: Ensure balanced brackets in annotated test names
  openshift-hack/e2e/annotate/annotate.go
  openshift-hack/e2e/annotate/annotate_test.go
Labels: approved, lgtm, backports/validated-commits
