Repository openshift/kubernetes, pull requests merged in 2022-08, with the labels that each got.

#1338 Bug 2117569: UPSTREAM: 110888: feat: fix a bug thaat not all event be ignored by gc controller
  cmd/kube-controller-manager/app/options/options_test.go
  pkg/controller/garbagecollector/graph_builder.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, backports/validated-commits

#1314 Bug 2104344: Fix resizing of ephemeral volumes
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backports/validated-commits, backport-risk-assessed

#1349 UPSTREAM: 111789: Update Netpol e2e tests to use framework CreateName…
  test/e2e/network/netpol/kubemanager.go
  test/e2e/network/netpol/model.go
  test/e2e/network/netpol/network_policy.go
  test/e2e/network/netpol/probe.go
  test/e2e/network/netpol/reachability.go
  test/e2e/network/netpol/test_helper.go
Labels: approved, lgtm, backports/validated-commits

#1344 Bug 2118318: UPSTREAM: 110939: don't quota events.k8s.io events by default
  pkg/quota/v1/install/registry.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backports/validated-commits

#1307 UPSTREAM: 110039: Add readinessProbe to aggregated api service test
  test/e2e/apimachinery/aggregator.go
Labels: approved, lgtm, backports/validated-commits

#1350 UPSTREAM: <carry>: Update kubensenter to use exec instead of subprocess
  openshift-hack/images/hyperkube/kubensenter
  openshift-hack/kubensenter.env
Labels: approved, lgtm, kind/cleanup

#1356 OCPBUGS-647: SDN branch: Fix Prefer local endpoints for cluster DNS service
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_test.go
Labels: backports/unvalidated-commits, jira/invalid-bug, jira/severity-moderate
