Repository openshift/kubernetes, pull requests merged in 2022-07, with the labels that each got.

#1303 Bug 2094012: UPSTREAM: 110652: fix: --chunk-size with selector returns missing result
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go
  test/integration/apiserver/apiserver_test.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, bugzilla/severity-urgent, backports/validated-commits

#1295 UPSTREAM: <carry>: Remove reserved CPUs from default set
  pkg/kubelet/cm/cpumanager/policy_static.go
Labels: approved, lgtm

#1296 Bug 2082773: Fix resizing of ephemeral volumes
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium, backports/validated-commits, qe-approved

#1091 Bug 2081194: UPSTREAM: <carry>: update list of deprecated apis
  openshift-kube-apiserver/filters/deprecatedapirequest/deprecated.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, backports/validated-commits

#1263 Bug 2104928: UPSTREAM: 109932: fix: exclude non-ready nodes and deleted nodes from azure load balancers
  staging/src/k8s.io/legacy-cloud-providers/azure/azure.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_test.go
Labels: kind/bug, approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backports/validated-commits, backport-risk-assessed

#1321 [release 4.9] Bug Bug 2106962: UPSTREAM: <carry>: use correct base image for testing
  openshift-hack/images/os/Dockerfile
  openshift-hack/images/os/install.sh
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, backport-risk-assessed

#1316 [release-4.9] Bug 2105663: UPSTREAM: <carry>: update list of deprecated apis
  openshift-kube-apiserver/filters/deprecatedapirequest/deprecated.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, backport-risk-assessed

#1256 Bug 2083554: UPSTREAM: 109933: fix: exclude non-ready nodes and deleted nodes from azure load balancers
  staging/src/k8s.io/legacy-cloud-providers/azure/azure.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_test.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backports/validated-commits, backport-risk-assessed

#1317 [release-4.8] Bug 2105664: UPSTREAM: <carry>: update list of deprecated apis
  openshift-kube-apiserver/filters/deprecatedapirequest/deprecated.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, backport-risk-assessed

#1325 [release-4.9] Bug 2106655: UPSTREAM: 109103: cpu/memory manager containerMap memory leak
  pkg/kubelet/cm/containermap/container_map.go
  pkg/kubelet/cm/cpumanager/cpu_manager.go
  pkg/kubelet/cm/memorymanager/memory_manager.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backports/validated-commits, backport-risk-assessed

#1330 trt-393: add plugin name to caches not synchronized error
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/quota/clusterresourcequota/admission.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update

#1257 Bug 2083557: UPSTREAM: 109935: fix: exclude non-ready nodes and deleted nodes from azure load balancers
  staging/src/k8s.io/legacy-cloud-providers/azure/azure.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_test.go
Labels: kind/bug, approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#1333 UPSTREAM: 111306: Make scheduling e2e tests run PSa-restricted pods
  test/e2e/scheduling/predicates.go
Labels: approved, lgtm, backports/validated-commits

#1327 Add kubensenter to the openshift RPM
  hack/make-rules/update.sh
  hack/update-kubensenter.sh
  hack/verify-kubensenter.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  openshift-hack/images/hyperkube/kubensenter
  openshift-hack/kubensenter.env
  openshift-hack/update-kubensenter.sh
  openshift-hack/verify-kubensenter.sh
  openshift.spec
Labels: approved, kind/feature, lgtm, vendor-update
