Repository openshift/kubernetes, pull requests merged in 2022-09, with the labels that each got.

#1359 UPSTREAM: 110639: endpointslices: node missing on Pod scenario
  pkg/controller/endpointslice/endpointslice_controller.go
  pkg/controller/endpointslice/endpointslice_controller_test.go
  pkg/controller/endpointslice/metrics/cache.go
  pkg/controller/endpointslice/metrics/cache_test.go
  pkg/controller/endpointslice/reconciler.go
  pkg/controller/endpointslice/reconciler_test.go
  pkg/controller/util/endpointslice/endpointslice_tracker.go
  pkg/controller/util/endpointslice/endpointslice_tracker_test.go
Labels: approved, lgtm, backports/validated-commits

#1351 [release 4.11] Bug 2117424: UPSTREAM: <carry>: Remove reserved CPUs from default set
  pkg/kubelet/cm/cpumanager/policy_static.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#1346 UPSTREAM: <carry>: optionally enable retry after until apiserver is ready
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/filters/with_not_ready_patch.go
  staging/src/k8s.io/apiserver/pkg/server/filters/with_not_ready_patch_test.go
  staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go
Labels: approved, lgtm, vendor-update, backports/validated-commits

#1358 OCPBUGS-718: UPSTREAM: 112267: aws: skip health rules if they are a subnet of the client rule
  staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits, jira/severity-moderate, jira/valid-bug

#1366 UPSTREAM: <carry>: Dockerfile: use centos:stream9
  openshift-hack/images/os/Dockerfile
Labels: approved, lgtm, backports/validated-commits

#1375 OCPBUGS-1540: UPSTREAM: 112267: aws: skip health rules if they are a subnet of the client rule
  staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-moderate, jira/valid-bug
