Repository openshift/kubernetes, pull requests merged in 2023-10, with the labels that each got.

#1724 OCPBUGS-19666: kubelet/cm: use MkdirAll when creating cpuset to ignore file exists error
  pkg/kubelet/cm/cgroup_manager_linux.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1703 Update builder & base images
  .ci-operator.yaml
  build/pause/Dockerfile.Rhel
  openshift-hack/images/hyperkube/Dockerfile.rhel
  openshift-hack/images/os/install.sh
  openshift-hack/images/tests/Dockerfile.rhel
Labels: approved, lgtm, vendor-update, backports/validated-commits

#1713 [4.14] OCPBUGS-19401: UPSTREAM: <carry>: vendor: bump cadvisor and runc to 1.1.9
  go.mod
  go.sum
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/kms/go.mod
  staging/src/k8s.io/kms/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/memory.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/common.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/v1.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/v2.go
  vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/factory_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/intelrdt/intelrdt.go
  vendor/github.com/opencontainers/runc/libcontainer/mount_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/process_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/patchbpf/enosys_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1731 Revert #1703 "Update builder & base images"
  .ci-operator.yaml
  build/pause/Dockerfile.Rhel
  openshift-hack/images/hyperkube/Dockerfile.rhel
  openshift-hack/images/os/install.sh
  openshift-hack/images/tests/Dockerfile.rhel
Labels: approved, lgtm, backports/validated-commits

#1732 Revert #1731 "Revert #1703 "Update builder & base images""
  .ci-operator.yaml
  build/pause/Dockerfile.Rhel
  openshift-hack/images/hyperkube/Dockerfile.rhel
  openshift-hack/images/os/install.sh
  openshift-hack/images/tests/Dockerfile.rhel
Labels: approved, lgtm, backports/validated-commits

#1734 OCPBUGS-20096: bump pause image to RHEL9
  build/pause/Dockerfile.Rhel
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1735 Do not allow nodes to set forbidden openshift labels
  cmd/kubelet/app/options/options.go
  plugin/pkg/admission/noderestriction/admission.go
  staging/src/k8s.io/kubelet/pkg/apis/well_known_labels.go
  staging/src/k8s.io/kubelet/pkg/apis/well_known_openshift_labels.go
Labels: kind/bug, approved, lgtm, vendor-update

#1736 [release-4.14] OCPBUGS-20115: Do not allow nodes to set forbidden openshift labels
  cmd/kubelet/app/options/options.go
  plugin/pkg/admission/noderestriction/admission.go
  staging/src/k8s.io/kubelet/pkg/apis/well_known_labels.go
  staging/src/k8s.io/kubelet/pkg/apis/well_known_openshift_labels.go
Labels: kind/bug, approved, lgtm, vendor-update, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1746 [release-4.13] OCPBUGS-20114: UPSTREAM: <carry>: Do not allow nodes to set forbidden openshift labels
  cmd/kubelet/app/options/options.go
  plugin/pkg/admission/noderestriction/admission.go
  staging/src/k8s.io/kubelet/pkg/apis/well_known_labels.go
  staging/src/k8s.io/kubelet/pkg/apis/well_known_openshift_labels.go
Labels: kind/bug, approved, lgtm, vendor-update, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1769 openshift-hack: Fix sporadic 141 errors in build-rpms
  openshift-hack/build-rpms.sh
Labels: kind/bug, approved, lgtm, kind/flake, backports/validated-commits

#1771 STOR-1278: Fixes for SELinux mount context metrics
  pkg/kubelet/volumemanager/cache/desired_state_of_wold_selinux_metrics.go
  pkg/kubelet/volumemanager/cache/desired_state_of_world.go
  pkg/kubelet/volumemanager/cache/desired_state_of_world_test.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#1747 [release-4.12] OCPBUGS-20113: UPSTREAM: <carry>: Do not allow nodes to set forbidden openshift labels
  cmd/kubelet/app/options/options.go
  plugin/pkg/admission/noderestriction/admission.go
  staging/src/k8s.io/kubelet/pkg/apis/well_known_labels.go
  staging/src/k8s.io/kubelet/pkg/apis/well_known_openshift_labels.go
Labels: kind/bug, approved, lgtm, vendor-update, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1788 Update REBASE.openshift.md
  REBASE.openshift.md
Labels: approved, lgtm, backports/validated-commits
