Repository openshift/kubernetes, pull requests merged in 2023-08, with the labels that each got.

#1630 OCPBUGS-15726: UPSTREAM: 118879: make apiservices.apiregistration.k8s.io discoverabl…
  api/openapi-spec/v3/apis__apiregistration.k8s.io__v1_openapi.json
  api/openapi-spec/v3/apis__apiregistration.k8s.io_openapi.json
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
  staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go
  staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator_test.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1657 OCPBUGS-17145: Increase service idle max timeout to 100 minutes
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer_test.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1654 OCPBUGS-15726: UPSTREAM: <carry>: merge v3 openapi discovery and specs for special groups
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go
  staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/patch_aggregator.go
  staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/patch_merge.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1493 OCPBUGS-7415: grant user:full scope to self-SARs
  pkg/registry/authorization/selfsubjectaccessreview/rest.go
  pkg/registry/authorization/selfsubjectaccessreview/rest_patch.go
  pkg/registry/authorization/selfsubjectaccessreview/rest_patch_test.go
  pkg/registry/authorization/selfsubjectaccessreview/rest_test.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, jira/severity-low, jira/valid-bug, jira/valid-reference

#1668 OCPBUGS-14301: UPSTREAM: 117249,118189: fix TopologyCache crashes
  pkg/controller/endpointslice/topologycache/topologycache.go
  pkg/controller/endpointslice/topologycache/topologycache_test.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1673 OCPBUGS-14301: UPSTREAM: 117245: Fix TopologyAwareHint not working when zone label is added after Node creation
  pkg/controller/endpointslice/endpointslice_controller.go
  pkg/controller/endpointslice/endpointslice_controller_test.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1672 OCPBUGS-17189: Update to Kubernetes 1.24.16
  .go-version
  CHANGELOG/CHANGELOG-1.24.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cmd/kubeadm/app/cmd/phases/workflow/runner_test.go
  go.mod
  hack/lib/golang.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/job/job_controller.go
  pkg/volume/git_repo/git_repo_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/api/core/v1/types.go
  staging/src/k8s.io/apimachinery/pkg/runtime/converter.go
  staging/src/k8s.io/apimachinery/pkg/runtime/converter_test.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/ready_test.go
  staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer.go
  staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_test.go
  staging/src/k8s.io/legacy-cloud-providers/gce/gce_util.go
  test/images/Makefile
  test/integration/job/job_test.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1628 [4.10] OCPBUGS-8735: UPSTREAM: <drop>: bump apiserver-library-go
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/matcher.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1681 OCPBUGS-18149: UPSTREAM: <carry>: retry etcd Unavailable errors
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient_test.go
Labels: approved, lgtm, vendor-update, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1682 OCPBUGS-18325: UPSTREAM: <carry>: Prefer local TCP endpoint for cluster DNS service
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_test.go
Labels: backports/unvalidated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference
