Repository openshift/kubernetes, pull requests merged in 2023-04, with the labels that each got.

#1482 OCPBUGS-7267: More fixes to SCC PSa extractor
  go.mod
  go.sum
  plugin/pkg/admission/security/podsecurity/patch_podspecextractor.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/patched_sc_accessors.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1527 OCPBUGS-11166: Bump to k8s 1.25.8
  .go-version
  CHANGELOG/CHANGELOG-1.25.md
  LICENSES/third_party/gimme/LICENSE
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  hack/.spelling_failures
  hack/jenkins/test-dockerized.sh
  hack/lib/golang.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/volume/attachdetach/util/util.go
  pkg/controller/volume/attachdetach/util/util_test.go
  pkg/controller/volume/persistentvolume/pv_controller.go
  pkg/controller/volume/persistentvolume/pv_controller_test.go
  pkg/proxy/winkernel/hns.go
  pkg/proxy/winkernel/hns_test.go
  pkg/proxy/winkernel/proxier.go
  pkg/proxy/winkernel/proxier_test.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins/volumebinding/binder.go
  pkg/scheduler/framework/runtime/framework.go
  pkg/scheduler/internal/queue/scheduling_queue.go
  pkg/scheduler/internal/queue/scheduling_queue_test.go
  pkg/scheduler/scheduler.go
  pkg/volume/csi/csi_mounter.go
  pkg/volume/csi/csi_mounter_test.go
  pkg/volume/csi/csi_plugin.go
  pkg/volume/csi/csi_plugin_test.go
  pkg/volume/testing/volume_host.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/kubectl/pkg/cmd/diff/diff.go
  staging/src/k8s.io/kubectl/pkg/cmd/diff/prune.go
  test/cmd/diff.sh
  test/e2e/apimachinery/flowcontrol.go
  test/e2e/storage/csi_inline.go
  test/images/Makefile
  third_party/gimme/LICENSE
  third_party/gimme/README.md
  third_party/gimme/gimme
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1531 OCPBUGS-11166: UPSTREAM: <carry>: Force using the go tooling from the system
  openshift-hack/lib/init.sh
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1536 OCPBUGS-11314: UPSTREAM: <carry>: Force using the go tooling from the system
  openshift-hack/lib/init.sh
  staging/src/k8s.io/apiextensions-apiserver/examples/client-go/pkg/client/clientset/versioned/fake/register.go
  staging/src/k8s.io/apiextensions-apiserver/examples/client-go/pkg/client/clientset/versioned/scheme/register.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/fake/register.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  staging/src/k8s.io/client-go/kubernetes/fake/register.go
  staging/src/k8s.io/client-go/kubernetes/scheme/register.go
  staging/src/k8s.io/code-generator/examples/HyphenGroup/clientset/versioned/fake/register.go
  staging/src/k8s.io/code-generator/examples/HyphenGroup/clientset/versioned/scheme/register.go
  staging/src/k8s.io/code-generator/examples/MixedCase/clientset/versioned/fake/register.go
  staging/src/k8s.io/code-generator/examples/MixedCase/clientset/versioned/scheme/register.go
  staging/src/k8s.io/code-generator/examples/apiserver/clientset/internalversion/fake/register.go
  staging/src/k8s.io/code-generator/examples/apiserver/clientset/versioned/fake/register.go
  staging/src/k8s.io/code-generator/examples/apiserver/clientset/versioned/scheme/register.go
  staging/src/k8s.io/code-generator/examples/crd/clientset/versioned/fake/register.go
  staging/src/k8s.io/code-generator/examples/crd/clientset/versioned/scheme/register.go
  staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go
  staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go
  staging/src/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/register.go
  staging/src/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme/register.go
  staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1alpha/api.pb.go
  staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1/api.pb.go
  staging/src/k8s.io/metrics/pkg/client/clientset/versioned/fake/register.go
  staging/src/k8s.io/metrics/pkg/client/clientset/versioned/scheme/register.go
  staging/src/k8s.io/sample-apiserver/pkg/generated/clientset/versioned/fake/register.go
  staging/src/k8s.io/sample-apiserver/pkg/generated/clientset/versioned/scheme/register.go
  staging/src/k8s.io/sample-controller/pkg/generated/clientset/versioned/fake/register.go
  staging/src/k8s.io/sample-controller/pkg/generated/clientset/versioned/scheme/register.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1485 Add wrapper which will allow running o/k tests as external binary in origin
  hack/lib/golang.sh
  openshift-hack/cmd/k8s-tests/k8s-tests.go
  openshift-hack/cmd/k8s-tests/provider.go
  openshift-hack/cmd/k8s-tests/runtest.go
  openshift-hack/cmd/k8s-tests/types.go
  openshift-hack/e2e/annotate/annotate.go
  openshift-hack/e2e/annotate/cmd/main.go
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
  openshift-hack/e2e/annotate/rules_test.go
  openshift-hack/e2e/namespace.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
Labels: approved, lgtm, backports/validated-commits

#1537 UPSTREAM: <carry>: add shutdown annotation to response header
  staging/src/k8s.io/apiserver/pkg/server/filters/with_early_late_annotations.go
  staging/src/k8s.io/apiserver/pkg/server/filters/with_early_late_annotations_test.go
Labels: approved, lgtm, vendor-update, backports/validated-commits

#1544 OCPBUGS-7268: Extractor more fixes 4.13
  go.mod
  go.sum
  plugin/pkg/admission/security/podsecurity/patch_podspecextractor.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/patched_sc_accessors.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1548 OCPBUGS-10829: UPSTREAM: 117310: kube-aggregator: correctly use client-go TLS cache with custom dialer
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy_test.go
  staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
  staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller_test.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits, jira/severity-important, jira/valid-bug, jira/valid-reference

#1549 OCPBUGS-11823: UPSTREAM: 117311: kube-aggregator: correctly use client-go TLS cache with custom dialer
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go
  staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy_test.go
  staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
  staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller_test.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1514 OCPBUGS-11146: Enable CSI migration configuration via env vars
  openshift-kube-apiserver/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
  openshift-kube-apiserver/admission/customresourcevalidation/operator/deny_delete_cluster_operator_resource.go
  openshift-kube-apiserver/admission/customresourcevalidation/operator/deny_delete_cluster_operator_resource_test.go
  pkg/controller/volume/attachdetach/attach_detach_controller.go
  pkg/features/kube_features.go
  pkg/features/patch_kube_features.go
  pkg/volume/csi/csi_plugin.go
  pkg/volume/csimigration/patch_adc_plugin_manager.go
  pkg/volume/csimigration/plugin_manager.go
  pkg/volume/csimigration/plugin_manager_test.go
  pkg/volume/vsphere_volume/vsphere_volume.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, backports/validated-commits, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
