Repository openshift/kubernetes, pull requests merged in 2023-09, with the labels that each got.

#1688 OCPBUGS-18608: UPSTREAM: <carry>: Force using host go always and use host libriaries
  hack/lib/golang.sh
Labels: approved, lgtm, backports/validated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1665 OCPBUGS-17654: cm: reorder setting of sched_load_balance for sandbox slice
  pkg/kubelet/cm/cgroup_manager_linux.go
Labels: kind/bug, approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1686 <carry>: Export cpu stats of ovs.slice via prometheus
  cmd/kubelet/app/server.go
Labels: kind/bug, approved, lgtm, acknowledge-critical-fixes-only

#1698 UPSTREAM: <carry>: disable test removed in 1.28
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits, acknowledge-critical-fixes-only

#1638 OCPBUGS-16080: UPSTREAM: <carry>: watch-termination: termination.log file
  cmd/watch-termination/main.go
Labels: approved, lgtm, backports/validated-commits, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1716 OCPBUGS-19452: UPSTREAM: 119317: change rolling update logic to exclude sunsetting nodes
  pkg/controller/daemon/update.go
  pkg/controller/daemon/update_test.go
  test/integration/daemonset/daemonset_test.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-important, jira/valid-bug, jira/valid-reference

#1714 UPSTREAM: 120817: e2e: bootstrap vsphere tests earlier
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apimachinery/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/cluster-bootstrap/go.sum
  staging/src/k8s.io/code-generator/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/cri-api/go.sum
  staging/src/k8s.io/csi-translation-lib/go.sum
  staging/src/k8s.io/dynamic-resource-allocation/go.sum
  staging/src/k8s.io/endpointslice/go.sum
  staging/src/k8s.io/kms/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/pod-security-admission/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.sum
  test/e2e/storage/drivers/in_tree.go
Labels: approved, lgtm, vendor-update, backports/validated-commits

#1717 [4.14] OCPBUGS-15531: UPSTREAM: 120786: change rolling update logic to exclude sunsetting nodes
  go.sum
  pkg/controller/daemon/update.go
  pkg/controller/daemon/update_test.go
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apimachinery/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/cluster-bootstrap/go.sum
  staging/src/k8s.io/code-generator/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/cri-api/go.sum
  staging/src/k8s.io/csi-translation-lib/go.sum
  staging/src/k8s.io/dynamic-resource-allocation/go.sum
  staging/src/k8s.io/kms/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/mount-utils/go.sum
  staging/src/k8s.io/pod-security-admission/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.sum
  test/integration/daemonset/daemonset_test.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1711 OCPBUGS-17534: UPSTREAM: <carry>: vendor: bump cadvisor and runc to 1.1.9
  go.mod
  go.sum
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/kms/go.mod
  staging/src/k8s.io/kms/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/memory.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/common.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/v1.go
  vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/factory_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/init_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/intelrdt/intelrdt.go
  vendor/github.com/opencontainers/runc/libcontainer/mount_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/process_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go
  vendor/github.com/opencontainers/runc/libcontainer/seccomp/patchbpf/enosys_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-bug, jira/valid-reference
