Repository openshift/kubernetes, pull requests merged in 2023-11, with the labels that each got.

#1781 SDN-4123: Sdn 4.15 kubernetes 1.28.3
  cmd/kube-proxy/app/server_openshift.go
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_openshift.go
  pkg/proxy/iptables/proxier_test.go
Labels: backports/unvalidated-commits, jira/valid-reference

#1783 [openshift-apiserver-4.15-kubernetes-1.28.3] UPSTREAM: <carry>: Enable UnauthenticatedHTTP2DOSMitigation by default
  pkg/features/kube_features.go
  staging/src/k8s.io/apiserver/pkg/features/kube_features.go
Labels: lgtm, backports/unvalidated-commits

#1784 [openshift-apiserver-4.14-kubernetes-1.27.7] UPSTREAM: <carry>: Enable UnauthenticatedHTTP2DOSMitigation by default
  pkg/features/kube_features.go
  staging/src/k8s.io/apiserver/pkg/features/kube_features.go
Labels: lgtm, backports/unvalidated-commits

#1785 [openshift-apiserver-4.13-kubernetes-1.26.10] UPSTREAM: <carry>: Enable UnauthenticatedHTTP2DOSMitigation by default
  pkg/features/kube_features.go
  staging/src/k8s.io/apiserver/pkg/features/kube_features.go
Labels: lgtm, backports/unvalidated-commits

#1786 [openshift-apiserver-4.12-kubernetes-1.25.15] UPSTREAM: <carry>: Enable UnauthenticatedHTTP2DOSMitigation by default
  pkg/features/kube_features.go
  staging/src/k8s.io/apiserver/pkg/features/kube_features.go
Labels: lgtm, backports/unvalidated-commits

#1748 [release-4.11] OCPBUGS-20112: UPSTREAM: <carry>: Do not allow nodes to set forbidden openshift labels
  cmd/kubelet/app/options/options.go
  plugin/pkg/admission/noderestriction/admission.go
  staging/src/k8s.io/kubelet/pkg/apis/well_known_labels.go
  staging/src/k8s.io/kubelet/pkg/apis/well_known_openshift_labels.go
Labels: kind/bug, approved, lgtm, vendor-update, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1790 OCPBUGS-16922: Remove skip flag for e2e tests related to AdmissionWebhookMatchConditions
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1800 OCPBUGS-22724: UPSTREAM: 121881: Use golang library instead of mklink
  staging/src/k8s.io/mount-utils/mount_windows.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1801 [release-4.14] OCPBUGS-23286: UPSTREAM: 121881: Use golang library instead of mklink
  staging/src/k8s.io/mount-utils/mount_windows.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1802 [release-4.13] OCPBUGS-23287: UPSTREAM: 121881: Use golang library instead of mklink
  staging/src/k8s.io/mount-utils/mount_windows.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1803 [release-4.12] OCPBUGS-23288: UPSTREAM: 121881: Use golang library instead of mklink
  staging/src/k8s.io/mount-utils/mount_windows.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1804 [release-4.11] OCPBUGS-23289: UPSTREAM: 121881: Use golang library instead of mklink
  staging/src/k8s.io/mount-utils/mount_windows.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1749 [release-4.10] OCPBUGS-20111: UPSTREAM: <carry>: Do not allow nodes to set forbidden openshift labels
  cmd/kubelet/app/options/options.go
  plugin/pkg/admission/noderestriction/admission.go
  staging/src/k8s.io/kubelet/pkg/apis/well_known_labels.go
  staging/src/k8s.io/kubelet/pkg/apis/well_known_openshift_labels.go
Labels: kind/bug, approved, lgtm, vendor-update, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1794 OCPBUGS-23073: .spec.numberOfUsersToReport is not correctly applied in some circumstances
  openshift-kube-apiserver/filters/apirequestcount/apiaccess_count_controller_test.go
  openshift-kube-apiserver/filters/apirequestcount/update_func.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1796 OCPBUGS-20122: Make kubelet set alpha.kubernetes.io/provided-node-ip unconditionally
  pkg/kubelet/nodestatus/setters.go
  pkg/kubelet/nodestatus/setters_test.go
Labels: kind/bug, approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference
