Repository openshift/kubernetes, pull requests merged in 2023-05, with the labels that each got.

#1561 OCPBUGS-2474: UPSTREAM: 116995: kubelet: Ensure pods that have not started track pendingUpdate
  pkg/kubelet/kubelet_pods_test.go
  pkg/kubelet/pod_workers.go
Labels: approved, lgtm, bugzilla/valid-bug, backports/validated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1555 OCPBUGS-10048: UPSTREAM: <carry>: add conditional shutdown response header
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/filters/with_early_late_annotations.go
  staging/src/k8s.io/apiserver/pkg/server/filters/with_early_late_annotations_test.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1569 OCPBUGS-11143: Azure: move to kube-proxy LB probes, don't detach masters when unready
  staging/src/k8s.io/legacy-cloud-providers/azure/azure.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer_test.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_test.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits, jira/severity-important, jira/valid-bug, jira/valid-reference

#1574 UPSTREAM: <carry>: move test rules from origin
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, bugzilla/valid-bug, backports/validated-commits, jira/valid-bug

#1579 OCPBUGS-11652: UPSTREAM: <carry>: Extend NodeLogQuery feature
  pkg/kubelet/kubelet_server_journal_linux.go
Labels: approved, lgtm, bugzilla/valid-bug, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1578 OCPBUGS-13854: UPSTREAM: 117371: kubelet: Don't reference the pod manager interface directly from components
  pkg/kubelet/eviction/eviction_manager.go
  pkg/kubelet/eviction/eviction_manager_test.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/kubelet_test.go
  pkg/kubelet/pod/mirror_client.go
  pkg/kubelet/pod/pod_manager.go
  pkg/kubelet/pod/pod_manager_test.go
  pkg/kubelet/pod/testing/mock_manager.go
  pkg/kubelet/pod_workers.go
  pkg/kubelet/prober/common_test.go
  pkg/kubelet/prober/prober_manager_test.go
  pkg/kubelet/prober/results/results_manager.go
  pkg/kubelet/prober/results/results_manager_test.go
  pkg/kubelet/prober/scale_test.go
  pkg/kubelet/prober/worker_test.go
  pkg/kubelet/runonce.go
  pkg/kubelet/runonce_test.go
  pkg/kubelet/stats/provider.go
  pkg/kubelet/status/fake_status_manager.go
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/status/status_manager_test.go
  pkg/kubelet/status/testing/mock_pod_status_provider.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go
  pkg/kubelet/volumemanager/volume_manager.go
  pkg/kubelet/volumemanager/volume_manager_test.go
  test/e2e/common/node/init_container.go
  test/e2e_node/mirror_pod_readiness_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1577 UPSTREAM: 117893: When expecting pods count only active ones
  test/e2e/apps/statefulset.go
  test/e2e/framework/statefulset/wait.go
Labels: approved, lgtm, bugzilla/valid-bug, backports/validated-commits, jira/valid-bug

#1584 Update test wrapper to match new k8s
  openshift-hack/cmd/k8s-tests/provider.go
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
  openshift-hack/e2e/namespace.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug

#1580 OCPBUGS-13747: 4.13: kubelet/cm: disable cpu load balancing on slices when using static cpu manager policy
  pkg/kubelet/cm/cgroup_manager_linux.go
  pkg/kubelet/cm/cgroup_manager_unsupported.go
  pkg/kubelet/cm/container_manager_linux.go
  pkg/kubelet/cm/types.go
Labels: kind/bug, approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference
