Repository openshift/kubernetes, pull requests merged in 2023-02, with the labels that each got.

#1450 UPSTREAM: 114994: kubelet: fix readiness probes with pod termination
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/pod/mirror_client.go
  pkg/kubelet/prober/prober_manager_test.go
  pkg/kubelet/prober/results/results_manager.go
  pkg/kubelet/prober/results/results_manager_test.go
  pkg/kubelet/prober/worker_test.go
  pkg/kubelet/status/status_manager.go
  pkg/kubelet/status/status_manager_test.go
  pkg/kubelet/status/testing/mock_pod_status_provider.go
  test/e2e_node/mirror_pod_readiness_test.go
Labels: approved, lgtm, backports/validated-commits

#1465 UPSTREAM: 115484: Don't explicitly set image version in tests
  test/e2e/node/security_context.go
Labels: approved, lgtm, backports/validated-commits

#1466 disable tests dependent on StackDriver
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits

#1469 UPSTREAM: 114027: make GetSubnetPrefix IP family agnostic
  test/e2e/framework/node/resource.go
  test/e2e/network/loadbalancer.go
Labels: approved, lgtm, backports/validated-commits

#1459 [4.11] OCPBUGS-6683: add message about possibly working with restricted SCC
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1454 AUTH-336: UPSTREAM: <carry>: PSa metrics: log platform namespaces in audit denies
  staging/src/k8s.io/pod-security-admission/metrics/metrics.go
  staging/src/k8s.io/pod-security-admission/metrics/metrics_test.go
Labels: approved, lgtm, vendor-update

#1475 OCPBUGS-7555: UPSTREAM: <carry>: add default kubelet sysctls within rpm
  openshift-hack/sysctls/50-kubelet.conf
  openshift.spec
Labels: approved, lgtm, bugzilla/valid-bug, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1458 UPSTREAM: <carry>: add new approvers
  DOWNSTREAM_OWNERS
Labels: approved, lgtm, backports/validated-commits

#1480 UPSTREAM: 115863: Remove global framework variable
  test/e2e/storage/drivers/in_tree.go
  test/e2e/storage/vsphere/bootstrap.go
  test/e2e/storage/vsphere/persistent_volumes-vsphere.go
  test/e2e/storage/vsphere/pv_reclaimpolicy.go
  test/e2e/storage/vsphere/pvc_label_selector.go
  test/e2e/storage/vsphere/vsphere_utils.go
  test/e2e/storage/vsphere/vsphere_volume_cluster_ds.go
  test/e2e/storage/vsphere/vsphere_volume_diskformat.go
  test/e2e/storage/vsphere/vsphere_volume_fstype.go
  test/e2e/storage/vsphere/vsphere_volume_ops_storm.go
Labels: approved, lgtm, backports/validated-commits

#1446 UPSTREAM: 113799: tests: network: Prefer internal IPs first
  test/e2e/framework/network/utils.go
Labels: kind/bug, approved, lgtm, backports/validated-commits

#1471 [4.12] OCPBUGS-5769: scc admission - seccomp profiles fix
  go.mod
  go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/seccomp/strategy.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1312 CNF-5901: admission hook change for workload partition on all clusters
  go.mod
  go.sum
  openshift-kube-apiserver/admission/admissionenablement/register.go
  openshift-kube-apiserver/admission/autoscaling/managednode/admission.go
  openshift-kube-apiserver/admission/autoscaling/managednode/admission_test.go
  openshift-kube-apiserver/admission/autoscaling/managednode/initializers.go
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission.go
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission_test.go
  openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference

#1490 OCPBUGS-7267: add SeccompProfile to Pod and Container accessors/mutators
  pkg/securitycontext/accessors.go
  pkg/securitycontext/accessors_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
