Repository openshift/kubernetes, pull requests merged in 2023-03, with the labels that each got.

#1489 AUTH-336: UPSTREAM: <carry>: PSa metrics: unset ocp_namespace on non-platform n…
  staging/src/k8s.io/pod-security-admission/metrics/metrics.go
  staging/src/k8s.io/pod-security-admission/metrics/metrics_test.go
Labels: approved, lgtm, vendor-update, jira/valid-reference

#1464 UPSTREAM: <carry>: update rebase doc
  REBASE.openshift.md
Labels: approved, lgtm, backports/validated-commits

#1499 OCPBUGS-8220: CSI Inline Volume admission plugin does not log object name correctly
  openshift-kube-apiserver/admission/storage/csiinlinevolumesecurity/admission.go
Labels: approved, lgtm, bugzilla/valid-bug, backports/validated-commits, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1456 OCPBUGS-10048: UPSTREAM: 115328: apiserver: annotate early (server not ready) and late (during shutdown) requests
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/filters/with_early_late_annotations.go
  staging/src/k8s.io/apiserver/pkg/server/filters/with_early_late_annotations_test.go
  staging/src/k8s.io/apiserver/pkg/server/lifecycle_signals.go
  staging/src/k8s.io/apiserver/pkg/server/lifecycle_signals_test.go
  staging/src/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
Labels: approved, kind/feature, lgtm, vendor-update, bugzilla/valid-bug, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1516 OCPBUGS-9985: Prefer local eps for DNS via TCP protocol
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_test.go
Labels: backports/unvalidated-commits, jira/invalid-bug, jira/severity-critical, jira/valid-reference

#1506 OCPBUGS-7359: Azure: move to kube-proxy LB probes, don't detach masters when unready
  staging/src/k8s.io/legacy-cloud-providers/azure/azure.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer_test.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_test.go
Labels: approved, lgtm, vendor-update, bugzilla/valid-bug, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference
