Repository openshift/kubernetes, pull requests merged in 2023-07, with the labels that each got.

#1623 OCPBUGS-13392: UPSTREAM: 118915: remove legacy NetworkPolicy tests
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  test/e2e/network/netpol/network_legacy.go
Labels: kind/bug, approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1624 UPSTREAM: 119107: Stop using deprecated API
  test/e2e/scheduling/predicates.go
Labels: approved, lgtm, backports/validated-commits

#1634 UPSTREAM: <drop>: hack/update-vendor.sh
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apimachinery/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/cluster-bootstrap/go.sum
  staging/src/k8s.io/code-generator/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/cri-api/go.sum
  staging/src/k8s.io/csi-translation-lib/go.sum
  staging/src/k8s.io/dynamic-resource-allocation/go.sum
  staging/src/k8s.io/kms/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/mount-utils/go.sum
  staging/src/k8s.io/pod-security-admission/go.sum
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.sum
Labels: approved, lgtm, vendor-update, backports/validated-commits

#1637 OCPBUGS-15866: UPSTREAM: <drop>: hack/update-vendor.sh
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apimachinery/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cli-runtime/go.sum
  staging/src/k8s.io/client-go/go.sum
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/cluster-bootstrap/go.sum
  staging/src/k8s.io/code-generator/go.mod
  staging/src/k8s.io/code-generator/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/cri-api/go.sum
  staging/src/k8s.io/csi-translation-lib/go.sum
  staging/src/k8s.io/dynamic-resource-allocation/go.sum
  staging/src/k8s.io/kms/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kube-proxy/go.sum
  staging/src/k8s.io/kube-scheduler/go.sum
  staging/src/k8s.io/kubectl/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/metrics/go.mod
  staging/src/k8s.io/metrics/go.sum
  staging/src/k8s.io/pod-security-admission/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  staging/src/k8s.io/sample-cli-plugin/go.sum
  staging/src/k8s.io/sample-controller/go.mod
  staging/src/k8s.io/sample-controller/go.sum
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1625 OCPBUGS-15866: remove readiness check for cache exclusion
  staging/src/k8s.io/legacy-cloud-providers/azure/azure.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_test.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1629 OCPBUGS-15726: UPSTREAM: 118881: fix openapi/v3 non local apiservices aggregation
  staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1643 [release-4.7] Fix mounted volume expansion tests
  openshift-hack/images/os/Dockerfile
  test/e2e/storage/flexvolume_mounted_volume_resize.go
  test/e2e/storage/mounted_volume_resize.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug

#1644 [release-4.6] Fix mounted volume expansion tests
  openshift-hack/images/os/Dockerfile
  test/e2e/storage/flexvolume_mounted_volume_resize.go
  test/e2e/storage/mounted_volume_resize.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug

#1627 [4.11] OCPBUGS-8736: UPSTREAM: <drop>: bump apiserver-library-go
  go.mod
  go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/matcher.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
