Repository openshift/kubernetes, pull requests merged in 2024-05, with the labels that each got.

#1959 API-1809: Provide SCC access via RBAC
  openshift-hack/e2e/namespace.go
Labels: approved, lgtm, jira/valid-reference

#1961 no-jira: UPSTREAM <carry>: add native build to installer image
  openshift-hack/images/installer-kube-apiserver-artifacts/Dockerfile.rhel
Labels: kind/bug, approved, lgtm, jira/valid-reference

#1958 [release-4.14] OCPBUGS-14373: Fix flaky HPA e2e tests by not failing on context cancelled (#117669)
  test/e2e/framework/autoscaling/autoscaling_utils.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1966 OCPBUGS-32934: UPSTREAM: 124795: e2e: DaemonSet maxSurge test should account for terminated pods
  test/e2e/apps/daemon_set.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1967 OCPBUGS-33574: bump openshift/library-go@e22d25a
  go.mod
  go.sum
  openshift-kube-apiserver/admission/customresourcevalidation/route/validation_opts.go
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/legacy-cloud-providers/go.sum
  staging/src/k8s.io/pod-security-admission/go.mod
  staging/src/k8s.io/pod-security-admission/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_testreporting.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/features/util.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_machineconfiguration.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/route/validation/validation.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, backports/validated-commits, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1978 UPSTREAM: <carry>: OCPBUGS-34102: force static build of linux binaries
  openshift-hack/images/installer-kube-apiserver-artifacts/Dockerfile.rhel
Labels: kind/bug, approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1972 OCPBUGS-33710: Bump k8s API to 1.29.5
  CHANGELOG/CHANGELOG-1.29.md
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kubeadm/app/phases/upgrade/postupgrade.go
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/proxy/topology.go
  pkg/scheduler/schedule_one.go
  pkg/scheduler/schedule_one_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/testing/wrappers.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics_test.go
  test/e2e/scheduling/predicates.go
  test/e2e/storage/utils/create.go
  test/e2e/testing-manifests/storage-csi/external-attacher/rbac.yaml
  test/e2e/testing-manifests/storage-csi/external-health-monitor/external-health-monitor-controller/rbac.yaml
  test/e2e/testing-manifests/storage-csi/external-provisioner/rbac.yaml
  test/e2e/testing-manifests/storage-csi/external-resizer/rbac.yaml
  test/e2e/testing-manifests/storage-csi/external-snapshotter/csi-snapshotter/rbac-csi-snapshotter.yaml
  test/e2e/testing-manifests/storage-csi/hostpath/README.md
  test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  test/e2e/testing-manifests/storage-csi/update-hostpath.sh
  test/instrumentation/documentation/documentation-list.yaml
  test/instrumentation/documentation/documentation.md
  test/integration/scheduler/filters/filters_test.go
  test/integration/scheduler/plugins/plugins_test.go
  test/utils/image/csi_manifests_test.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1969 OCPBUGS-33711: Bump to Kubernetes v1.28.10
  CHANGELOG/CHANGELOG-1.28.md
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/proxy/topology.go
  pkg/scheduler/schedule_one.go
  pkg/scheduler/schedule_one_test.go
  pkg/scheduler/testing/wrappers.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics_test.go
  staging/src/k8s.io/cloud-provider/cloud.go
  staging/src/k8s.io/cloud-provider/controllers/nodelifecycle/node_lifecycle_controller.go
  staging/src/k8s.io/cloud-provider/controllers/nodelifecycle/node_lifecycle_controller_test.go
  staging/src/k8s.io/cloud-provider/fake/fake.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController_test.go
  staging/src/k8s.io/legacy-cloud-providers/gce/gce_instances_test.go
  test/e2e/scheduling/predicates.go
  test/e2e/storage/utils/create.go
  test/e2e/testing-manifests/storage-csi/external-attacher/rbac.yaml
  test/e2e/testing-manifests/storage-csi/external-health-monitor/external-health-monitor-controller/rbac.yaml
  test/e2e/testing-manifests/storage-csi/external-provisioner/rbac.yaml
  test/e2e/testing-manifests/storage-csi/external-resizer/rbac.yaml
  test/e2e/testing-manifests/storage-csi/external-snapshotter/csi-snapshotter/rbac-csi-snapshotter.yaml
  test/e2e/testing-manifests/storage-csi/hostpath/README.md
  test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  test/e2e/testing-manifests/storage-csi/update-hostpath.sh
  test/instrumentation/documentation/documentation-list.yaml
  test/instrumentation/documentation/documentation.md
  test/integration/scheduler/filters/filters_test.go
  test/integration/scheduler/plugins/plugins_test.go
  test/utils/image/csi_manifests_test.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1970 OCPBUGS-33712: Bump to Kubernetes v1.27.14
  CHANGELOG/CHANGELOG-1.27.md
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/scheduler/schedule_one.go
  pkg/scheduler/schedule_one_test.go
  pkg/scheduler/testing/wrappers.go
  staging/src/k8s.io/cloud-provider/cloud.go
  staging/src/k8s.io/cloud-provider/controllers/nodelifecycle/node_lifecycle_controller.go
  staging/src/k8s.io/cloud-provider/controllers/nodelifecycle/node_lifecycle_controller_test.go
  staging/src/k8s.io/cloud-provider/fake/fake.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController_test.go
  staging/src/k8s.io/legacy-cloud-providers/gce/gce_instances_test.go
  test/e2e/scheduling/predicates.go
  test/e2e/storage/utils/create.go
  test/e2e/testing-manifests/storage-csi/external-attacher/rbac.yaml
  test/e2e/testing-manifests/storage-csi/external-health-monitor/external-health-monitor-controller/rbac.yaml
  test/e2e/testing-manifests/storage-csi/external-provisioner/rbac.yaml
  test/e2e/testing-manifests/storage-csi/external-resizer/rbac.yaml
  test/e2e/testing-manifests/storage-csi/external-snapshotter/csi-snapshotter/rbac-csi-snapshotter.yaml
  test/e2e/testing-manifests/storage-csi/hostpath/README.md
  test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  test/e2e/testing-manifests/storage-csi/update-hostpath.sh
  test/integration/scheduler/filters/filters_test.go
  test/integration/scheduler/plugins/plugins_test.go
  test/utils/image/csi_manifests_test.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1827 OCPBUGS-25331: UPSTREAM: <carry>: extend termination events
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
  staging/src/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1981 API-1783: UPSTREAM: <carry>: skip storage tests
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#1983 OCPBUGS-34593: UPSTREAM: 124933: [Scheduler] Use allNodes when calculating nextStartNodeIndex
  pkg/scheduler/schedule_one.go
  pkg/scheduler/schedule_one_test.go
  test/integration/scheduler/scheduler_test.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference
