Repository openshift/kubernetes, pull requests merged in 2024-02, with the labels that each got.

#1876 OCPBUGS-12210: Prevent partially filled HPA behaviors from crashing kube-controller-manager
  pkg/controller/podautoscaler/horizontal.go
  pkg/controller/podautoscaler/horizontal_test.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1881 OCPBUGS-29435: UPSTREAM: 123165: Add AudienceMatchPolicy and support multiple audien…
  pkg/features/kube_features.go
  staging/src/k8s.io/apiserver/pkg/apis/apiserver/types.go
  staging/src/k8s.io/apiserver/pkg/apis/apiserver/v1alpha1/types.go
  staging/src/k8s.io/apiserver/pkg/apis/apiserver/v1alpha1/zz_generated.conversion.go
  staging/src/k8s.io/apiserver/pkg/apis/apiserver/validation/validation.go
  staging/src/k8s.io/apiserver/pkg/apis/apiserver/validation/validation_test.go
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc_test.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1880 NO-JIRA: Clean carry patches
  hack/make-rules/verify.sh
  hack/verify-external-dependencies-version.sh
  hack/verify-govulncheck.sh
  hack/verify-openapi-spec.sh
  hack/verify-pkg-names.sh
  hack/verify-spelling.sh
  hack/verify-typecheck-providerless.sh
  openshift-hack/e2e/namespace.go
  staging/src/k8s.io/kubectl/pkg/cmd/config/config_test.go
  test/e2e/framework/framework.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference

#1888 OCPNODE-1892: Bump k8s to 1.29.2
  .go-version
  CHANGELOG/CHANGELOG-1.29.md
  api/openapi-spec/swagger.json
  api/openapi-spec/v3/api__v1_openapi.json
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cluster/gce/gci/configure-helper.sh
  cluster/images/etcd/Makefile
  cmd/kubeadm/app/cmd/init.go
  cmd/kubeadm/app/cmd/init_test.go
  cmd/kubeadm/app/cmd/phases/init/uploadconfig.go
  cmd/kubeadm/app/cmd/upgrade/node.go
  cmd/kubeadm/app/phases/kubelet/config.go
  cmd/kubeadm/app/phases/kubelet/config_test.go
  cmd/kubeadm/app/phases/upgrade/postupgrade.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/apis/core/types.go
  pkg/controller/volume/persistentvolume/pv_controller.go
  pkg/features/kube_features.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/proxy/endpoints.go
  pkg/proxy/endpoints_test.go
  pkg/proxy/endpointslicecache.go
  pkg/proxy/iptables/proxier.go
  pkg/proxy/service.go
  pkg/proxy/service_test.go
  pkg/scheduler/metrics/metrics.go
  pkg/volume/plugins.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/api/core/v1/generated.proto
  staging/src/k8s.io/api/core/v1/types.go
  staging/src/k8s.io/api/core/v1/types_swagger_doc_generated.go
  staging/src/k8s.io/apiserver/pkg/admission/plugin/validatingadmissionpolicy/controller_reconcile.go
  staging/src/k8s.io/component-base/metrics/prometheus/slis/metrics.go
  staging/src/k8s.io/component-helpers/storage/volume/helpers.go
  staging/src/k8s.io/component-helpers/storage/volume/helpers_test.go
  test/conformance/image/Makefile
  test/images/Makefile
  test/images/nonroot/BASEIMAGE
  test/images/pets/peer-finder/BASEIMAGE
  test/images/pets/redis-installer/BASEIMAGE
  test/images/pets/zookeeper-installer/BASEIMAGE
  test/images/regression-issue-74839/BASEIMAGE
  test/images/resource-consumer/BASEIMAGE
  test/instrumentation/testdata/stable-metrics-list.yaml
  test/integration/apiserver/cel/validatingadmissionpolicy_test.go
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference

#1882 OCPBUGS-29437: Upstream: <carry>: RPM: Split apiserver, scheduler, k-c-m, kubelet into subpackages
  openshift.spec
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1899 OCPBUGS-10996: Fix race condition between resizer and kubelet
  pkg/kubelet/volumemanager/reconciler/reconciler_test.go
  pkg/volume/csi/expander.go
  pkg/volume/testing/testing.go
  pkg/volume/util/operationexecutor/operation_generator.go
  pkg/volume/util/types/types.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-moderate, jira/valid-bug, jira/valid-reference
