Repository openshift/kubernetes, pull requests merged in 2024-08, with the labels that each got.

#2032 OCPBUGS-19802: Bump 4.16 runc
  go.mod
  go.sum
  pkg/kubelet/cm/container_manager_linux.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/userns/inuserns/inuserns_linux.go
  pkg/kubelet/userns/inuserns/inuserns_others.go
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/memory.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/memory.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/stats.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/validate/rootless.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/validate/validator.go
  vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/userns/userns_maps.c
  vendor/github.com/opencontainers/runc/libcontainer/userns/userns_maps_linux.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#2040 NO-JIRA: UPSTREAM: 126213: add test about container metrics from cadvisor
  test/e2e_node/container_metrics_test.go
  test/e2e_node/resource_metrics_test.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2038 OCPBUGS-37620: Bump 1.30.3
  .go-version
  CHANGELOG/CHANGELOG-1.30.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/endpoint/endpoints_controller.go
  pkg/controller/endpoint/endpoints_controller_test.go
  pkg/controller/endpoint/endpoints_tracker.go
  pkg/controller/endpoint/endpoints_tracker_test.go
  pkg/controller/job/job_controller_test.go
  pkg/controller/job/success_policy.go
  pkg/controller/job/success_policy_test.go
  pkg/controller/volume/persistentvolume/pv_controller.go
  pkg/scheduler/internal/queue/scheduling_queue.go
  pkg/scheduler/internal/queue/scheduling_queue_test.go
  pkg/securitycontext/util.go
  pkg/volume/git_repo/git_repo.go
  pkg/volume/git_repo/git_repo_test.go
  staging/publishing/rules.yaml
  test/e2e/apimachinery/aggregator.go
  test/e2e/apimachinery/openapiv3.go
  test/images/Makefile
  test/integration/endpoints/endpoints_test.go
  test/integration/scheduler/plugins/plugins_test.go
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, jira/valid-bug, jira/valid-reference

#2039 OCPBUGS-37621: Bump k8s api to 1.29.7
  .go-version
  CHANGELOG/CHANGELOG-1.29.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go
  cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go
  hack/lib/golang.sh
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/endpoint/endpoints_controller.go
  pkg/controller/endpoint/endpoints_controller_test.go
  pkg/controller/endpoint/endpoints_tracker.go
  pkg/controller/endpoint/endpoints_tracker_test.go
  pkg/controller/volume/persistentvolume/delete_test.go
  pkg/controller/volume/persistentvolume/pv_controller.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/scheduler/internal/queue/scheduling_queue.go
  pkg/scheduler/internal/queue/scheduling_queue_test.go
  pkg/securitycontext/util.go
  pkg/util/filesystem/defaultfs.go
  pkg/util/filesystem/util_unix.go
  pkg/util/filesystem/util_windows.go
  pkg/util/filesystem/util_windows_test.go
  pkg/volume/git_repo/git_repo.go
  pkg/volume/git_repo/git_repo_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/kubectl/pkg/cmd/create/create_job.go
  staging/src/k8s.io/kubectl/pkg/cmd/create/create_job_test.go
  test/e2e/apimachinery/aggregator.go
  test/e2e/apimachinery/openapiv3.go
  test/images/Makefile
  test/integration/endpoints/endpoints_test.go
  test/integration/scheduler/plugins/plugins_test.go
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2037 OCPBUGS-37622: Bump to Kubernetes v1.28.12
  .go-version
  CHANGELOG/CHANGELOG-1.28.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  build/root/Makefile
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/endpoint/endpoints_controller.go
  pkg/controller/endpoint/endpoints_controller_test.go
  pkg/controller/endpoint/endpoints_tracker.go
  pkg/controller/endpoint/endpoints_tracker_test.go
  pkg/controller/volume/persistentvolume/delete_test.go
  pkg/controller/volume/persistentvolume/pv_controller.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/scheduler/internal/queue/scheduling_queue.go
  pkg/scheduler/internal/queue/scheduling_queue_test.go
  pkg/securitycontext/util.go
  pkg/util/filesystem/defaultfs.go
  pkg/util/filesystem/util_unix.go
  pkg/util/filesystem/util_windows.go
  pkg/util/filesystem/util_windows_test.go
  pkg/volume/git_repo/git_repo.go
  pkg/volume/git_repo/git_repo_test.go
  staging/publishing/rules.yaml
  test/e2e/apimachinery/aggregator.go
  test/e2e/apimachinery/openapiv3.go
  test/images/Makefile
  test/integration/endpoints/endpoints_test.go
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2043 OCPBUGS-37623: Bump to Kubernetes v1.27.16
  .go-version
  CHANGELOG/CHANGELOG-1.27.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/kubelet/kubelet.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/util/filesystem/defaultfs.go
  pkg/util/filesystem/util_unix.go
  pkg/util/filesystem/util_windows.go
  pkg/util/filesystem/util_windows_test.go
  staging/publishing/rules.yaml
  test/images/Makefile
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2045 [release-4.13] OCPBUGS-37280: UPSTREAM: 126104: Add funcs in pkg/filesystem/util that can actually …
  pkg/kubelet/kubelet.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/util/filesystem/defaultfs.go
  pkg/util/filesystem/util_unix.go
  pkg/util/filesystem/util_windows.go
  pkg/util/filesystem/util_windows_test.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2050 NO-JIRA: update downstream owners
  DOWNSTREAM_OWNERS
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2049 NO-JIRA: update downstream owners
  DOWNSTREAM_OWNERS
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2046 [release-4.12] OCPBUGS-37282: UPSTREAM: 126104: Add funcs in pkg/filesystem/util that can actually …
  pkg/kubelet/kubelet.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/util/filesystem/defaultfs.go
  pkg/util/filesystem/util_unix.go
  pkg/util/filesystem/util_windows.go
  pkg/util/filesystem/util_windows_test.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2047 NO-JIRA: update downstream owners
  DOWNSTREAM_OWNERS
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2048 NO-JIRA: update downstream owners
  DOWNSTREAM_OWNERS
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2051 NO-JIRA: update downstream owners
  DOWNSTREAM_OWNERS
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2054 OCPBUGS-38336: UPSTREAM: 126641: e2e/storage: update block device test to always specify a valid path
  test/e2e/storage/volume_metrics.go
Labels: kind/failing-test, approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2058 [release-4.15]: OCPBUGS-38861: Upstream: 115702 kubelet: output log even file is rotated
  pkg/kubelet/kuberuntime/logs/logs.go
  pkg/kubelet/kuberuntime/logs/logs_test.go
Labels: kind/bug, approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#2068 NO-JIRA: UPSTREAM:<drop>: bump openshift/library-go@4d55b6d
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sysctl/mustmatchpatterns.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference

#2069 OCPBUGS-39004: UPSTREAM: 126994: Add required FieldManager for validatingadmissionpolicy e2e
  test/e2e/apimachinery/validatingadmissionpolicy.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-low, jira/valid-bug, jira/valid-reference
