Repository openshift/kubernetes, pull requests merged in 2024-11, with the labels that each got.

#2082 SDN-5457: Add Dockerfile for standalone kube-proxy image
  openshift-hack/images/kube-proxy/Dockerfile.rhel
  openshift-hack/images/kube-proxy/OWNERS
  openshift-hack/images/kube-proxy/test-kube-proxy.sh
  openshift-hack/images/tests/Dockerfile.rhel
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_test.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2127 SDN-5457: Bump kube-proxy image to 4.18 base images
  openshift-hack/images/kube-proxy/Dockerfile.rhel
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2057 NO-JIRA: drop openshift-sdn references
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
  openshift-hack/test-kubernetes-e2e.sh
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2129 OCPBUGS-34373: Bump library-go to fix routes/custom-host permission for externalCertificate
  go.mod
  go.sum
  openshift-kube-apiserver/admission/route/hostassignment/admission.go
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cloud-provider/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/controller-manager/go.sum
  staging/src/k8s.io/dynamic-resource-allocation/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/kube-controller-manager/go.sum
  staging/src/k8s.io/kubelet/go.sum
  staging/src/k8s.io/pod-security-admission/go.mod
  staging/src/k8s.io/pod-security-admission/go.sum
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-apiserver/go.sum
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/route/common.go
  vendor/github.com/openshift/library-go/pkg/route/hostassignment/assignment.go
  vendor/github.com/openshift/library-go/pkg/route/hostassignment/externalcertificate.go
  vendor/github.com/openshift/library-go/pkg/route/validation/validation.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, vendor-update, backports/validated-commits, jira/severity-important, jira/valid-bug, jira/valid-reference

#2099 OCPBUGS-42555: Allow pod to be scheduled if node's name and hostname mismatch
  pkg/scheduler/framework/plugins/volumebinding/binder.go
  pkg/scheduler/framework/plugins/volumebinding/binder_test.go
  pkg/scheduler/framework/plugins/volumebinding/fake_binder.go
  pkg/scheduler/framework/plugins/volumebinding/volume_binding.go
  pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go
  pkg/scheduler/framework/runtime/framework.go
  pkg/scheduler/framework/types.go
  pkg/scheduler/schedule_one.go
  pkg/scheduler/schedule_one_test.go
  pkg/volume/util/util.go
  pkg/volume/util/util_test.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#2134 OCPBUGS-44512: Bump k8s api to 1.30.6
  .go-version
  CHANGELOG/CHANGELOG-1.30.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cmd/kubeadm/app/phases/upgrade/health.go
  cmd/kubeadm/app/preflight/checks_linux.go
  cmd/kubeadm/app/util/etcd/etcd.go
  cmd/kubelet/app/server.go
  go.mod
  hack/verify-vendor.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/daemon/update.go
  pkg/controller/daemon/update_test.go
  pkg/controller/endpoint/endpoints_controller.go
  pkg/proxy/endpointschangetracker.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/pkg/server/options/tracing.go
  test/images/Makefile
  test/integration/endpoints/endpoints_test.go
  test/integration/framework/controlplane_utils.go
  test/utils/image/manifest.go
  vendor/go.opentelemetry.io/otel/metric/noop/noop.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2133 OCPBUGS-44513: Bump k8s api to 1.29.10
  .go-version
  CHANGELOG/CHANGELOG-1.29.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cmd/kubeadm/app/preflight/checks_linux.go
  cmd/kubeadm/app/util/etcd/etcd.go
  cmd/kubelet/app/server.go
  go.mod
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/daemon/update.go
  pkg/controller/daemon/update_test.go
  pkg/controller/endpoint/endpoints_controller.go
  pkg/proxy/endpoints.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/pkg/server/options/tracing.go
  staging/src/k8s.io/code-generator/examples/go.work.sum
  test/images/Makefile
  test/integration/endpoints/endpoints_test.go
  test/utils/image/manifest.go
  vendor/go.opentelemetry.io/otel/metric/noop/noop.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2132 OCPBUGS-44514: Bump k8s api to 1.28.15
  .go-version
  CHANGELOG/CHANGELOG-1.28.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cmd/kubeadm/app/preflight/checks_linux.go
  cmd/kubeadm/app/util/etcd/etcd.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/daemon/update.go
  pkg/controller/daemon/update_test.go
  pkg/controller/endpoint/endpoints_controller.go
  staging/publishing/rules.yaml
  test/images/Makefile
  test/integration/endpoints/endpoints_test.go
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2139 OCPBUGS-44896: Enable format library for 4.18
  staging/src/k8s.io/apiserver/pkg/cel/environment/base.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2141 WRKLDS-1449: Update to Kubernetes v1.31.3
  CHANGELOG/CHANGELOG-1.31.md
  cmd/kube-controller-manager/app/controllermanager_test.go
  cmd/kube-controller-manager/app/core.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controlplane/controller/leaderelection/run_with_leaderelection.go
  pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go
  pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go
  pkg/scheduler/testing/wrappers.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/config_test.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher_whitebox_test.go
  staging/src/k8s.io/cloud-provider/controllers/service/controller.go
  test/instrumentation/documentation/documentation-list.yaml
  test/instrumentation/documentation/documentation.md
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference

#2144 [release-4.18] OCPBUGS-45117: Update to Kubernetes 1.31.3
  CHANGELOG/CHANGELOG-1.31.md
  cmd/kube-controller-manager/app/controllermanager_test.go
  cmd/kube-controller-manager/app/core.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controlplane/controller/leaderelection/run_with_leaderelection.go
  pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go
  pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go
  pkg/scheduler/testing/wrappers.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/config_test.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher_whitebox_test.go
  staging/src/k8s.io/cloud-provider/controllers/service/controller.go
  test/instrumentation/documentation/documentation-list.yaml
  test/instrumentation/documentation/documentation.md
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference
