Repository openshift/kubernetes, pull requests merged in 2024-01, with the labels that each got.

#1835 OCPBUGS-25214: legacy-cloud-providers: prevent index out-of-range in getNextUnitNumber
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/utils.go
  staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/utils_test.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1836 OCPNODE-1895: temporarily disable reporting e2e text bugs
  test/e2e/framework/internal/unittests/bugs/bugs_test.go
  test/e2e/framework/internal/unittests/list-labels/listlabels_test.go
  test/e2e/framework/internal/unittests/list-tests/listtests_test.go
  test/e2e/framework/test_context.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#1837 OCPBUGS-26005: Update to Kubernetes 1.28.5
  .go-version
  CHANGELOG/CHANGELOG-1.28.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  go.mod
  go.sum
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/job/job_controller.go
  pkg/controller/job/job_controller_test.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/statefulset/stateful_set_control_test.go
  pkg/controller/statefulset/stateful_set_utils.go
  pkg/controlplane/apiserver/config.go
  pkg/features/kube_features.go
  pkg/kubelet/cm/dra/claiminfo.go
  pkg/kubelet/cm/dra/manager.go
  pkg/kubelet/cm/dra/manager_test.go
  pkg/scheduler/framework/runtime/framework.go
  pkg/scheduler/framework/runtime/framework_test.go
  pkg/scheduler/framework/types.go
  pkg/scheduler/internal/queue/scheduling_queue_test.go
  pkg/scheduler/schedule_one.go
  pkg/scheduler/schedule_one_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/apiserver/pkg/endpoints/discovery/aggregated/handler.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go
  staging/src/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go
  staging/src/k8s.io/apiserver/pkg/server/options/recommended.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter_test.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/borrowing_test.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/controller_test.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/interface.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset_test.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/gen_test.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/max_seats_test.go
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/metrics/metrics.go
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/kms/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/mount-utils/mount_helper_unix.go
  test/images/Makefile
  test/integration/apiserver/flowcontrol/fight_test.go
  test/integration/statefulset/statefulset_test.go
  test/utils/image/manifest.go
  vendor/github.com/cyphar/filepath-securejoin/.travis.yml
  vendor/github.com/cyphar/filepath-securejoin/README.md
  vendor/github.com/cyphar/filepath-securejoin/VERSION
  vendor/github.com/cyphar/filepath-securejoin/join.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1839 OCPBUGS-25988: Update to kubernetes 1.26.12
  .go-version
  CHANGELOG/CHANGELOG-1.26.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  go.mod
  go.sum
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/scheduler/framework/runtime/framework.go
  pkg/scheduler/framework/types.go
  pkg/scheduler/schedule_one.go
  pkg/scheduler/schedule_one_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/mount-utils/mount_helper_unix.go
  test/images/Makefile
  test/utils/image/manifest.go
  vendor/github.com/cyphar/filepath-securejoin/.travis.yml
  vendor/github.com/cyphar/filepath-securejoin/README.md
  vendor/github.com/cyphar/filepath-securejoin/VERSION
  vendor/github.com/cyphar/filepath-securejoin/join.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1840 OCPNODE-1892: Bump k8s api to 1.29.0
  CHANGELOG/CHANGELOG-1.29.md
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/features/kube_features.go
  pkg/scheduler/internal/queue/scheduling_queue_test.go
  test/integration/scheduler/queue_test.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#1828 OCPBUGS-26067: Backport CEL IP and CIDR validations
  staging/src/k8s.io/apiserver/pkg/cel/cidr.go
  staging/src/k8s.io/apiserver/pkg/cel/environment/base.go
  staging/src/k8s.io/apiserver/pkg/cel/ip.go
  staging/src/k8s.io/apiserver/pkg/cel/library/cidr.go
  staging/src/k8s.io/apiserver/pkg/cel/library/cidr_test.go
  staging/src/k8s.io/apiserver/pkg/cel/library/cost.go
  staging/src/k8s.io/apiserver/pkg/cel/library/cost_test.go
  staging/src/k8s.io/apiserver/pkg/cel/library/ip.go
  staging/src/k8s.io/apiserver/pkg/cel/library/ip_test.go
  staging/src/k8s.io/apiserver/pkg/cel/library/library_compatibility_test.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1846 OCPNODE-1892: UPSTREAM: 122643: Add a new neverTerminate job behavior just for upgrade
  test/e2e/framework/job/fixtures.go
  test/e2e/upgrades/apps/job.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#1824 OCPBUGS-24404: add ignore for SAST scan
  .synk
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1829 OCPBUGS-23896: Fix device uncertain errors on reboot
  pkg/kubelet/volumemanager/cache/actual_state_of_world.go
  pkg/kubelet/volumemanager/reconciler/reconciler_test.go
  pkg/kubelet/volumemanager/reconciler/reconstruct_new_test.go
  pkg/volume/testing/testing.go
  pkg/volume/util/operationexecutor/operation_executor.go
  pkg/volume/util/operationexecutor/operation_generator.go
Labels: approved, lgtm, backports/validated-commits, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1848 OCPNODE-1892: UPSTREAM: 122683: Use v1beta1 endpoints when cleaning up ValidatingAdmissionPolicies
  test/e2e/apimachinery/validatingadmissionpolicy.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#1832 OCPBUGS-25812: Fix device uncertain errors on reboot - 4.15
  pkg/kubelet/volumemanager/cache/actual_state_of_world.go
  pkg/kubelet/volumemanager/reconciler/reconciler_test.go
  pkg/kubelet/volumemanager/reconciler/reconstruct_new_test.go
  pkg/volume/testing/testing.go
  pkg/volume/util/operationexecutor/operation_executor.go
  pkg/volume/util/operationexecutor/operation_generator.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1787 OCPBUGS-17249: UPSTREAM: <carry>: openshift-kube-apiserver: pod .spec.nodeName should not override project node selector in podNodeEnvironment admission plugin
  openshift-kube-apiserver/admission/scheduler/nodeenv/admission.go
  openshift-kube-apiserver/admission/scheduler/nodeenv/admission_test.go
Labels: approved, lgtm, backports/validated-commits, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1849 OCPNODE-1892: UPSTREAM: <carry>: update test rules
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#1830 OCPBUGS-25813: Fix uncertain device in 4.14
  pkg/kubelet/volumemanager/cache/actual_state_of_world.go
  pkg/kubelet/volumemanager/reconciler/reconciler_test.go
  pkg/kubelet/volumemanager/reconciler/reconstruct_new_test.go
  pkg/volume/testing/testing.go
  pkg/volume/util/operationexecutor/operation_executor.go
  pkg/volume/util/operationexecutor/operation_generator.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1821 OCPBUGS-24606: UPSTREAM: <carry>: Update management webhook pod admission logic
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission.go
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission_test.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1845 OCPNODE-1892: Switch to golang 1.21
  .ci-operator.yaml
  build/pause/Dockerfile.Rhel
  go.mod
  hack/lib/golang.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  openshift-hack/images/tests/Dockerfile.rhel
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apimachinery/go.mod
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/cli-runtime/go.mod
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/cloud-provider/go.mod
  staging/src/k8s.io/cluster-bootstrap/go.mod
  staging/src/k8s.io/code-generator/examples/go.mod
  staging/src/k8s.io/code-generator/examples/go.sum
  staging/src/k8s.io/code-generator/go.mod
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/controller-manager/go.mod
  staging/src/k8s.io/cri-api/go.mod
  staging/src/k8s.io/csi-translation-lib/go.mod
  staging/src/k8s.io/dynamic-resource-allocation/go.mod
  staging/src/k8s.io/endpointslice/go.mod
  staging/src/k8s.io/kms/go.mod
  staging/src/k8s.io/kms/internal/plugins/_mock/go.mod
  staging/src/k8s.io/kms/internal/plugins/_mock/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-controller-manager/go.mod
  staging/src/k8s.io/kube-proxy/go.mod
  staging/src/k8s.io/kube-scheduler/go.mod
  staging/src/k8s.io/kubectl/go.mod
  staging/src/k8s.io/kubelet/go.mod
  staging/src/k8s.io/legacy-cloud-providers/go.mod
  staging/src/k8s.io/metrics/go.mod
  staging/src/k8s.io/mount-utils/go.mod
  staging/src/k8s.io/pod-security-admission/go.mod
  staging/src/k8s.io/sample-apiserver/go.mod
  staging/src/k8s.io/sample-cli-plugin/go.mod
  staging/src/k8s.io/sample-controller/go.mod
  test/e2e/framework/ginkgowrapper.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference

#1833 OCPBUGS-25815: Fix device uncertain errors on reboot 4.12
  pkg/kubelet/volumemanager/cache/actual_state_of_world.go
  pkg/kubelet/volumemanager/reconciler/reconciler_test.go
  pkg/kubelet/volumemanager/reconciler/reconstruct_new_test.go
  pkg/volume/testing/testing.go
  pkg/volume/util/operationexecutor/operation_executor.go
  pkg/volume/util/operationexecutor/operation_generator.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1859 OCPBUGS-27370: Update to kubernetes 1.26.13
  .go-version
  CHANGELOG/CHANGELOG-1.26.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cluster/gce/manifests/etcd.manifest
  cluster/gce/upgrade-aliases.sh
  cluster/images/etcd/Makefile
  cluster/images/etcd/migrate/options.go
  cmd/kubeadm/app/constants/constants.go
  hack/lib/etcd.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/kubelet/volumemanager/reconciler/reconciler_test.go
  pkg/kubelet/volumemanager/reconciler/reconstruct.go
  pkg/scheduler/framework/runtime/framework.go
  pkg/scheduler/framework/runtime/framework_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go
  staging/src/k8s.io/sample-apiserver/artifacts/example/deployment.yaml
  test/e2e/framework/providers/gcp.go
  test/images/Makefile
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1792 OCPBUGS-16760: permanently disable NodeLogQuery e2e test
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1841 OCPBUGS-26058: UPSTREAM: <carry>: watch-termination: termination.log file with restricted permissions
  cmd/watch-termination/main.go
Labels: approved, lgtm, backports/validated-commits, qe-approved, jira/valid-bug, jira/valid-reference

#1871 OCPBUGS-24404: UPSTREAM <carry>: use snyk file
  .snyk
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1870 NO-JIRA: Revert "OCPBUGS-24404: add ignore for SAST scan"
  .synk
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#1872 CORS-3191: Add Dockerfile to buld kube-apiserver for openshift-install architectures
  openshift-hack/images/installer-kube-apiserver-artifacts/Dockerfile.rhel
  openshift-hack/images/installer-kube-apiserver-artifacts/OWNERS
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference
