Repository openshift/kubernetes, pull requests merged in 2024-06, with the labels that each got.

#1986 OCPBUGS-34544: UPSTREAM: <carry>: Disable e2e tests that need PersistentVolumeLabel
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1985 OCPBUGS-34545: UPSTREAM: <carry>: Disable e2e tests that need PersistentVolumeLabel
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1987 OCPBUGS-34050: Backport 125337
  cmd/kubelet/app/options/options.go
  pkg/kubelet/kubelet_node_status.go
  pkg/kubelet/nodestatus/setters.go
  pkg/kubelet/nodestatus/setters_test.go
  test/integration/cloudprovider/ccm_test.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1989 [release-4.16]OCPBUGS-35291: Backport 125337
  cmd/kubelet/app/options/options.go
  pkg/kubelet/kubelet_node_status.go
  pkg/kubelet/nodestatus/setters.go
  pkg/kubelet/nodestatus/setters_test.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1991 OCPBUGS-34544: UPSTREAM: <carry>: Disable PersistentVolumeLabel by default
  openshift-kube-apiserver/admission/admissionenablement/register.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1995 OCPBUGS-14613: drop carry "don't fail integration due to too many goroutines"
  cmd/kube-apiserver/app/patch_server.go
  cmd/kube-apiserver/app/server.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
  test/integration/framework/etcd.go
  test/integration/scheduler_perf/scheduler_perf.go
  test/integration/scheduler_perf/scheduler_test.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1973 OCPBUGS-33964: UPSTREAM: 123055: Fix race condition between resizer and kubelet
  pkg/kubelet/volumemanager/reconciler/reconciler_test.go
  pkg/volume/csi/expander.go
  pkg/volume/testing/testing.go
  pkg/volume/util/operationexecutor/operation_generator.go
  pkg/volume/util/types/types.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference
