Repository openshift/kubernetes, pull requests merged in 2024-07, with the labels that each got.

#1998 OCPBUGS-34294: OCPBUGS-34309: UPSTREAM: <carry>: update base image
  build/pause/Dockerfile.Rhel
  openshift-hack/images/hyperkube/Dockerfile.rhel
  openshift-hack/images/installer-kube-apiserver-artifacts/Dockerfile.rhel
  openshift-hack/images/tests/Dockerfile.rhel
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1990 OCPBUGS-35551: Bump k8s 1.29.6
  .go-version
  CHANGELOG/CHANGELOG-1.29.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cluster/gce/gci/configure-helper.sh
  cluster/images/etcd/Makefile
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/statefulset/stateful_set.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/statefulset/stateful_set_control_test.go
  pkg/controller/statefulset/stateful_set_test.go
  pkg/printers/internalversion/printers.go
  pkg/printers/internalversion/printers_test.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go
  pkg/scheduler/framework/preemption/preemption.go
  pkg/scheduler/framework/preemption/preemption_test.go
  pkg/scheduler/framework/types.go
  pkg/scheduler/internal/queue/scheduling_queue.go
  pkg/scheduler/internal/queue/scheduling_queue_test.go
  pkg/scheduler/schedule_one.go
  pkg/scheduler/schedule_one_test.go
  pkg/volume/plugins.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509_test.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController_test.go
  test/conformance/image/Makefile
  test/e2e/framework/statefulset/rest.go
  test/e2e/storage/drivers/in_tree.go
  test/images/Makefile
  test/images/nonroot/BASEIMAGE
  test/images/pets/peer-finder/BASEIMAGE
  test/images/pets/redis-installer/BASEIMAGE
  test/images/pets/zookeeper-installer/BASEIMAGE
  test/images/regression-issue-74839/BASEIMAGE
  test/images/resource-consumer/BASEIMAGE
  test/integration/scheduler/plugins/plugins_test.go
  test/integration/scheduler/queue_test.go
  test/integration/scheduler/scheduler_test.go
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1994 OCPBUGS-35552: Bump to Kubernetes v1.28.11
  .go-version
  CHANGELOG/CHANGELOG-1.28.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cluster/images/etcd/Makefile
  hack/make-rules/verify.sh
  hack/verify-govulncheck.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/statefulset/stateful_set.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/statefulset/stateful_set_control_test.go
  pkg/controller/statefulset/stateful_set_test.go
  pkg/printers/internalversion/printers.go
  pkg/printers/internalversion/printers_test.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go
  pkg/scheduler/framework/preemption/preemption.go
  pkg/scheduler/framework/preemption/preemption_test.go
  pkg/scheduler/framework/types.go
  pkg/scheduler/internal/queue/scheduling_queue.go
  pkg/scheduler/internal/queue/scheduling_queue_test.go
  pkg/scheduler/schedule_one.go
  pkg/scheduler/schedule_one_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509_test.go
  staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  test/conformance/image/Makefile
  test/e2e/framework/statefulset/rest.go
  test/e2e/storage/drivers/in_tree.go
  test/images/Makefile
  test/integration/scheduler/queue_test.go
  test/integration/scheduler/scheduler_test.go
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1992 OCPBUGS-35553: Bump k8s 1.27.15
  .go-version
  CHANGELOG/CHANGELOG-1.27.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  hack/verify-govulncheck.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go
  pkg/scheduler/framework/preemption/preemption.go
  pkg/scheduler/framework/preemption/preemption_test.go
  pkg/scheduler/framework/types.go
  pkg/scheduler/internal/queue/scheduling_queue.go
  pkg/scheduler/schedule_one.go
  pkg/scheduler/schedule_one_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509_test.go
  test/e2e/storage/drivers/in_tree.go
  test/images/Makefile
  test/integration/scheduler/queue_test.go
  test/integration/scheduler/scheduler_test.go
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2010 OCPBUGS-35553: Disable vulncheck
  hack/make-rules/verify.sh
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2018 OCPBUGS-36743: UPSTREAM: <carry>: inject k8s version from hyperkube Dockerfile
  hack/lib/version.sh
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2012 MULTIARCH-4229: UPSTREAM:<carry>:bump cadvisor for 3516 upstream patches
  go.mod
  go.sum
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  vendor/github.com/google/cadvisor/info/v1/machine.go
  vendor/github.com/google/cadvisor/machine/machine.go
  vendor/github.com/google/cadvisor/utils/sysfs/sysfs.go
  vendor/github.com/google/cadvisor/utils/sysinfo/sysinfo.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, vendor-update, jira/valid-reference, acknowledge-critical-fixes-only

#2023 NO-JIRA: UPSTREAM: <drop>: bump(github.com/openshift/apiserver-library-go)
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/patched_sc_accessors.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccmatching/provider.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference, acknowledge-critical-fixes-only

#2025 OCPBUGS-37111: UPSTREAM: 125404: Fix that PodIP field is temporarily removed for a terminal pod
  pkg/kubelet/kubelet.go
  test/e2e_node/pod_ips.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2017 OCPBUGS-36742: UPSTREAM: <carry>: sync imports
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
  openshift-hack/e2e/include.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2024 NO-JIRA: add tool to validate test packages imported
  openshift-hack/cmd/go-imports-diff/main.go
  openshift-hack/verify-test-annotations.sh
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference, acknowledge-critical-fixes-only

#2033 OCPEDGE-1181: UPSTREAM: <carry>: update test annotations for sno
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2034 OCPBUGS-37281: UPSTREAM: 126104: Add funcs in pkg/filesystem/util to set file permissions on Windows and update container log dir perms
  pkg/kubelet/kubelet.go
  pkg/util/filesystem/defaultfs.go
  pkg/util/filesystem/util_unix.go
  pkg/util/filesystem/util_windows.go
  pkg/util/filesystem/util_windows_test.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference
