Repository openshift/kubernetes, pull requests merged in 2024-10, with the labels that each got.

#2100 OCPBUGS-42640: Revert #2089 "OCPBUGS-42167: Bump k8s api to 1.30.5"
  .go-version
  CHANGELOG/CHANGELOG-1.30.md
  api/openapi-spec/swagger.json
  api/openapi-spec/v3/api__v1_openapi.json
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cluster/addons/dns/coredns/coredns.yaml.base
  cluster/addons/dns/coredns/coredns.yaml.in
  cluster/addons/dns/coredns/coredns.yaml.sed
  cluster/gce/manifests/etcd.manifest
  cluster/gce/upgrade-aliases.sh
  cluster/images/etcd/Makefile
  cluster/images/etcd/migrate/options.go
  cmd/kubeadm/app/constants/constants.go
  cmd/kubeadm/app/images/images_test.go
  cmd/kubeadm/app/phases/addons/dns/dns_test.go
  go.mod
  go.sum
  go.work.sum
  hack/lib/etcd.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/endpointslice/endpointslice_controller.go
  pkg/controller/endpointslice/endpointslice_controller_test.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kuberuntime/kuberuntime_container.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
  pkg/kubelet/types/pod_update.go
  pkg/proxy/config/config.go
  pkg/scheduler/framework/preemption/preemption.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/api/core/v1/generated.proto
  staging/src/k8s.io/api/core/v1/types.go
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/client-go/applyconfigurations/internal/internal.go
  staging/src/k8s.io/code-generator/go.mod
  staging/src/k8s.io/code-generator/go.sum
  staging/src/k8s.io/code-generator/tools.go
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/sample-apiserver/artifacts/example/deployment.yaml
  test/e2e_node/device_plugin_test.go
  test/images/Makefile
  test/utils/image/manifest.go
  vendor/github.com/coredns/corefile-migration/migration/versions.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, staff-eng-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2102 WRKLDS-1449: Update Hyperkube Dockerfile with the right Kubernetes version
  openshift-hack/images/hyperkube/Dockerfile.rhel
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2067 OCPBUGS-39305: log only deprecated api requests
  openshift-kube-apiserver/filters/apirequestcount/apiaccess_count_controller.go
  openshift-kube-apiserver/filters/apirequestcount/apiaccess_count_controller_test.go
  openshift-kube-apiserver/filters/apirequestcount/deprecated.go
  openshift-kube-apiserver/filters/apirequestcount_filter.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#2112 TRT-1867: Revert #2067 "OCPBUGS-39305: log only deprecated api requests"
  openshift-kube-apiserver/filters/apirequestcount/apiaccess_count_controller.go
  openshift-kube-apiserver/filters/apirequestcount/apiaccess_count_controller_test.go
  openshift-kube-apiserver/filters/apirequestcount/deprecated.go
  openshift-kube-apiserver/filters/apirequestcount_filter.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2107 OCPBUGS-42640: Unrevert Bump k8s api to 1.30.5"
  .go-version
  CHANGELOG/CHANGELOG-1.30.md
  api/openapi-spec/swagger.json
  api/openapi-spec/v3/api__v1_openapi.json
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cluster/addons/dns/coredns/coredns.yaml.base
  cluster/addons/dns/coredns/coredns.yaml.in
  cluster/addons/dns/coredns/coredns.yaml.sed
  cluster/gce/manifests/etcd.manifest
  cluster/gce/upgrade-aliases.sh
  cluster/images/etcd/Makefile
  cluster/images/etcd/migrate/options.go
  cmd/kubeadm/app/constants/constants.go
  cmd/kubeadm/app/images/images_test.go
  cmd/kubeadm/app/phases/addons/dns/dns_test.go
  go.mod
  go.sum
  go.work.sum
  hack/lib/etcd.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/endpointslice/endpointslice_controller.go
  pkg/controller/endpointslice/endpointslice_controller_test.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kuberuntime/kuberuntime_container.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
  pkg/kubelet/types/pod_update.go
  pkg/proxy/config/config.go
  pkg/scheduler/framework/preemption/preemption.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/api/core/v1/generated.proto
  staging/src/k8s.io/api/core/v1/types.go
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/client-go/applyconfigurations/internal/internal.go
  staging/src/k8s.io/code-generator/go.mod
  staging/src/k8s.io/code-generator/go.sum
  staging/src/k8s.io/code-generator/tools.go
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  staging/src/k8s.io/sample-apiserver/artifacts/example/deployment.yaml
  test/e2e_node/device_plugin_test.go
  test/images/Makefile
  test/utils/image/manifest.go
  vendor/github.com/coredns/corefile-migration/migration/versions.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2114 OCPBUGS-38838: Re-enable 1.31 kubectl tests
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2116 OCPBUGS-39004: CRD type check test fix
  test/e2e/apimachinery/validatingadmissionpolicy.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-low, jira/valid-bug, jira/valid-reference

#2090 OCPBUGS-42168: Bump k8s api to 1.29.9
  .go-version
  CHANGELOG/CHANGELOG-1.29.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cluster/gce/manifests/etcd.manifest
  cluster/gce/upgrade-aliases.sh
  cluster/images/etcd/Makefile
  cluster/images/etcd/migrate/options.go
  cmd/kubeadm/app/constants/constants.go
  hack/lib/etcd.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/endpointslice/endpointslice_controller.go
  pkg/controller/endpointslice/endpointslice_controller_test.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kuberuntime/kuberuntime_container.go
  pkg/kubelet/kuberuntime/kuberuntime_manager.go
  pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
  pkg/kubelet/types/pod_update.go
  pkg/proxy/config/config.go
  pkg/scheduler/framework/preemption/preemption.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/sample-apiserver/artifacts/example/deployment.yaml
  test/e2e/framework/providers/gcp.go
  test/e2e_node/device_plugin_test.go
  test/images/Makefile
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2031 OCPBUGS-28812: UPSTREAM: <carry>: kubelet/cm: fix bug where kubelet restarts from missing cpuset cgroup
  pkg/kubelet/cm/cgroup_manager_linux.go
  pkg/kubelet/cm/cpumanager/cpu_manager.go
  pkg/kubelet/cm/cpumanager/cpu_manager_test.go
  pkg/kubelet/cm/cpumanager/fake_cpu_manager.go
  pkg/kubelet/cm/node_container_manager_linux.go
  pkg/kubelet/cm/types.go
  test/e2e_node/node_container_manager_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#2122 WRKLDS-1449: Bump k8s api to 1.31.2
  .go-version
  CHANGELOG/CHANGELOG-1.31.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cmd/kubeadm/app/phases/upgrade/health.go
  cmd/kubeadm/app/preflight/checks_linux.go
  cmd/kubeadm/app/util/etcd/etcd.go
  cmd/kubelet/app/server.go
  go.mod
  go.work.sum
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/endpoint/endpoints_controller.go
  pkg/proxy/endpointschangetracker.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/pkg/server/options/tracing.go
  staging/src/k8s.io/apiserver/pkg/server/storage/resource_encoding_config.go
  staging/src/k8s.io/apiserver/pkg/server/storage/storage_factory.go
  test/e2e/node/gpu.go
  test/images/Makefile
  test/integration/endpoints/endpoints_test.go
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference
