Repository openshift/kubernetes, pull requests merged in 2024-04, with the labels that each got.

#1922 OCPBUGS-30767: UPSTREAM: 124110: retry policy creation for CRD type checking E2E test
  test/e2e/apimachinery/validatingadmissionpolicy.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1924 OCPBUGS-31384: UPSTREAM: <carry>: allow type mutation for specific secrets
  pkg/apis/core/validation/validation.go
  pkg/apis/core/validation/validation_patch.go
  pkg/apis/core/validation/validation_patch_test.go
  test/integration/apiserver/openshift_secret_updates_type_mutation_test.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1929 OCPBUGS-31384: UPSTREAM: <carry>: allow type mutation for specific secrets
  pkg/apis/core/validation/validation_patch.go
  test/integration/apiserver/openshift_secret_updates_type_mutation_test.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1932 OCPBUGS-31384: UPSTREAM: <carry>: allow type mutation for specific secrets
  pkg/apis/core/validation/validation_patch.go
  pkg/apis/core/validation/validation_patch_test.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1919 OCPBUGS-30957: Use the right feature gate when updating uncertain …
  pkg/kubelet/volumemanager/cache/actual_state_of_world.go
Labels: approved, lgtm, backports/validated-commits, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1935 OCPBUGS-31740: 4.15: UPSTREAM: 124048: Use the right feature gate when updating uncertain volumes
  pkg/kubelet/volumemanager/cache/actual_state_of_world.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1936 OCPBUGS-31741: 4.14: UPSTREAM: 124048: Use the right feature gate when updating uncertain volumes
  pkg/kubelet/volumemanager/cache/actual_state_of_world.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1928 OCPBUGS-31663: UPSTREAM: <carry>: add management workload check for guaranteed qos
  pkg/kubelet/managed/managed.go
  pkg/kubelet/managed/managed_test.go
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1910 OCPBUGS-11933: UPSTREAM: <drop>: bump apiserver-library-go
  go.mod
  go.sum
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/severity-important, jira/valid-bug, jira/valid-reference

#1898 [release-4.14] OCPBUGS-29924: UPSTREAM: <carry>: openshift-kube-apiserver: add kube-apiserver patches
  openshift-kube-apiserver/admission/scheduler/nodeenv/admission.go
  openshift-kube-apiserver/admission/scheduler/nodeenv/admission_test.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1944 NO-JIRA: UPSTREAM: <carry>: featureset validation moved to CEL
  openshift-kube-apiserver/admission/customresourcevalidation/features/validate_features.go
  openshift-kube-apiserver/admission/customresourcevalidation/features/validate_features_test.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#1902 UPSTREAM: <carry>: OCPEDGE-807: add support for cpu limits into management workloads
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission.go
  openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission_test.go
  pkg/kubelet/managed/managed.go
  pkg/kubelet/managed/managed_test.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#1914 OCPBUGS-26440: UPSTREAM: <carry>: create readyz event for kubeapi server
  staging/src/k8s.io/apiserver/pkg/server/healthz.go
Labels: approved, kind/feature, lgtm, vendor-update, backports/validated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1811 OCPBUGS-22301: UPSTREAM: <carry>: Fix garbage-collection for CRDs.
  cmd/kube-controller-manager/app/patch_gc.go
Labels: approved, lgtm, backports/validated-commits, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1877 Sdn 4.16 kubernetes 1.29.0
  cmd/kube-proxy/app/server_openshift.go
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_openshift.go
  pkg/proxy/iptables/proxier_test.go
Labels: backports/unvalidated-commits

#1954 OCPBUGS-20097: Migrate tools image to RHEL9
  openshift-hack/images/tests/Dockerfile.rhel
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#1956 [4.14] OCPBUGS-32580: allow override of NewVolumeManagerReconstruction
  pkg/features/patch_kube_features.go
Labels: approved, lgtm, cherry-pick-approved, backports/validated-commits, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference
