Repository openshift/kubernetes, pull requests merged in 2024-12, with the labels that each got.

#2140 OCPBUGS-44897: Backport format library to enable usage in 4.18
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/pkg/cel/environment/base.go
  staging/src/k8s.io/apiserver/pkg/cel/format.go
  staging/src/k8s.io/apiserver/pkg/cel/library/cost.go
  staging/src/k8s.io/apiserver/pkg/cel/library/cost_test.go
  staging/src/k8s.io/apiserver/pkg/cel/library/format.go
  staging/src/k8s.io/apiserver/pkg/cel/library/format_test.go
  staging/src/k8s.io/apiserver/pkg/cel/library/quantity_test.go
  staging/src/k8s.io/apiserver/pkg/cel/limits.go
  staging/src/k8s.io/dynamic-resource-allocation/go.mod
  staging/src/k8s.io/dynamic-resource-allocation/go.sum
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2126 [release-4.17] OCPBUGS-43820: UPSTREAM: <carry>: kubelet/cm: fix bug where kubelet restarts from missing cpuset cgroup
  pkg/kubelet/cm/cgroup_manager_linux.go
  pkg/kubelet/cm/cpumanager/cpu_manager.go
  pkg/kubelet/cm/cpumanager/cpu_manager_test.go
  pkg/kubelet/cm/cpumanager/fake_cpu_manager.go
  pkg/kubelet/cm/node_container_manager_linux.go
  pkg/kubelet/cm/types.go
  test/e2e_node/node_container_manager_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#2136 OCPBUGS-44786: add support for the LLC alignment cpumanager policy option
  pkg/kubelet/cm/cpumanager/cpu_assignment.go
  pkg/kubelet/cm/cpumanager/cpu_assignment_test.go
  pkg/kubelet/cm/cpumanager/cpu_manager_test.go
  pkg/kubelet/cm/cpumanager/policy_options.go
  pkg/kubelet/cm/cpumanager/policy_options_test.go
  pkg/kubelet/cm/cpumanager/policy_static.go
  pkg/kubelet/cm/cpumanager/policy_test.go
  pkg/kubelet/cm/cpumanager/topology/topology.go
  pkg/kubelet/cm/cpumanager/topology/topology_test.go
  pkg/kubelet/cm/cpumanager/topology_hints_test.go
  pkg/kubelet/llcalign/llcalign.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2160 OCPBUGS-46002: Bump k8s api to 1.30.7
  CHANGELOG/CHANGELOG-1.30.md
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go
  pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go
  pkg/scheduler/schedule_one_test.go
  pkg/scheduler/testing/wrappers.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/config_test.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2164 [release-4.17]: OCPBUGS-46364: Fix grace period used for immediate evictions
  pkg/kubelet/eviction/eviction_manager.go
  pkg/kubelet/eviction/eviction_manager_test.go
  pkg/kubelet/eviction/helpers_test.go
  pkg/kubelet/pod_workers.go
  pkg/kubelet/pod_workers_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
