Repository openshift/kubernetes, pull requests merged in 2024-03, with the labels that each got.

#1900 OCPBUGS-23900: UPSTREAM: 123512: system:kube-scheduler: extend the RBAC with pods/finalizers
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
Labels: approved, lgtm, backports/validated-commits, qe-approved, jira/valid-bug, jira/valid-reference

#1805 MCO-392: openshift-hack/images/os: delete
  REBASE.openshift.md
  openshift-hack/images/os/Dockerfile
  openshift-hack/images/os/install.sh
Labels: approved, lgtm, lifecycle/stale, backports/validated-commits, jira/valid-reference

#1891 OCPBUGS-29661: Bump to 1.28.7
  .go-version
  CHANGELOG/CHANGELOG-1.28.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cluster/images/etcd/Makefile
  cmd/kubeadm/app/cmd/phases/init/uploadconfig.go
  cmd/kubeadm/app/cmd/upgrade/node.go
  cmd/kubeadm/app/phases/kubelet/config.go
  cmd/kubeadm/app/phases/kubelet/config_test.go
  cmd/kubeadm/app/phases/upgrade/postupgrade.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/volume/persistentvolume/pv_controller.go
  pkg/proxy/endpoints.go
  pkg/proxy/endpoints_test.go
  pkg/proxy/endpointslicecache.go
  pkg/proxy/iptables/proxier.go
  pkg/proxy/service.go
  pkg/proxy/service_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/component-base/metrics/prometheus/slis/metrics.go
  staging/src/k8s.io/component-helpers/storage/volume/helpers.go
  staging/src/k8s.io/component-helpers/storage/volume/helpers_test.go
  test/conformance/image/Makefile
  test/images/Makefile
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1890 OCPBUGS-29662: Update to kubernetes 1.27.11
  .go-version
  CHANGELOG/CHANGELOG-1.27.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cmd/kubeadm/app/cmd/phases/init/uploadconfig.go
  cmd/kubeadm/app/phases/kubelet/config.go
  cmd/kubeadm/app/phases/kubelet/config_test.go
  cmd/kubeadm/app/phases/upgrade/postupgrade.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/volume/persistentvolume/pv_controller.go
  pkg/proxy/endpoints.go
  pkg/proxy/endpoints_test.go
  pkg/proxy/endpointslicecache.go
  pkg/proxy/iptables/proxier.go
  pkg/proxy/service.go
  pkg/proxy/service_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/component-base/metrics/prometheus/slis/metrics.go
  staging/src/k8s.io/component-helpers/storage/volume/helpers.go
  staging/src/k8s.io/component-helpers/storage/volume/helpers_test.go
  test/images/Makefile
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1889 OCPBUGS-29663: Update to kubernetes 1.26.14
  .go-version
  CHANGELOG/CHANGELOG-1.26.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/volume/persistentvolume/pv_controller.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/component-base/metrics/prometheus/slis/metrics.go
  staging/src/k8s.io/component-helpers/storage/volume/helpers.go
  staging/src/k8s.io/component-helpers/storage/volume/helpers_test.go
  test/images/Makefile
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1908 OCPBUGS-24481: Enable SELinux tests
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
  openshift-hack/e2e/kube_e2e_test.go
  test/e2e/storage/csi_mock/csi_selinux_mount.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1911 OCPBUGS-30954: Set up CEL IP/CIDR library from 4.14 onwards
  staging/src/k8s.io/apiserver/pkg/cel/environment/base.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1912 OCPBUGS-30963: Set up CEL IP/CIDR library from 4.14 onwards
  staging/src/k8s.io/apiserver/pkg/cel/environment/base.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1913 OCPBUGS-30964: Set up CEL IP/CIDR library from 4.14 onwards
  staging/src/k8s.io/apiserver/pkg/cel/cidr.go
  staging/src/k8s.io/apiserver/pkg/cel/ip.go
  staging/src/k8s.io/apiserver/pkg/cel/library/cidr.go
  staging/src/k8s.io/apiserver/pkg/cel/library/cidr_test.go
  staging/src/k8s.io/apiserver/pkg/cel/library/cost.go
  staging/src/k8s.io/apiserver/pkg/cel/library/cost_test.go
  staging/src/k8s.io/apiserver/pkg/cel/library/ip.go
  staging/src/k8s.io/apiserver/pkg/cel/library/ip_test.go
  staging/src/k8s.io/apiserver/pkg/cel/library/libraries.go
  staging/src/k8s.io/apiserver/pkg/cel/library/library_compatibility_test.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1892 UPSTREAM: <carry>: OCPBUGS-29520: fix cpu manager cpuset check
  pkg/kubelet/cm/cpumanager/policy_static.go
  pkg/kubelet/cm/cpumanager/policy_static_test.go
  pkg/kubelet/managed/managed.go
  pkg/printers/internalversion/printers_test.go
Labels: kind/bug, approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference
