Repository openshift/kubernetes, pull requests merged in 2025-04, with the labels that each got.

#2244 [release-4.15] OCPBUGS-53139: UPSTREAM: 129180: prevent unnecessary resolving of iscsi/fc devices to dm
  pkg/volume/util/device_util_linux.go
  pkg/volume/util/device_util_linux_test.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_blobDiskController_test.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2178 TRT-1836: UPSTREAM: <carry>: remove old k8s-tests external binary
  hack/lib/golang.sh
  openshift-hack/cmd/k8s-tests/k8s-tests.go
  openshift-hack/cmd/k8s-tests/provider.go
  openshift-hack/cmd/k8s-tests/runtest.go
  openshift-hack/cmd/k8s-tests/types.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2257 OCPBUGS-54339: UPSTREAM: 129808: e2e: bump port-forward timeout
  test/e2e/kubectl/portforward.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2254 STOR-2285: Update group snapshot test rules
  openshift-hack/cmd/k8s-tests-ext/disabled_tests.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2256 TRT-1854: fix OVNKubernetes network skips
  openshift-hack/cmd/k8s-tests-ext/environment_selectors.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2216 OCPBUGS-52410: Propagate error when creating CustomResourceStorage instead of panicking
  staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd_test.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2263 OCPBUGS-54426: Fix implementation of ContainsCIDR to allow non-equal addresses
  staging/src/k8s.io/apiserver/pkg/cel/library/cidr.go
  staging/src/k8s.io/apiserver/pkg/cel/library/cidr_test.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2247 OCPBUGS-53249: skip UDP LoadBalancer on external
  openshift-hack/cmd/k8s-tests-ext/environment_selectors.go
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: kind/failing-test, approved, lgtm, kind/cleanup, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2268 [release-4.18]: OCPBUGS-54807: skip tests on platform type External
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: kind/failing-test, approved, lgtm, kind/cleanup, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2135 OCPBUGS-37706: allow TLS1.3 or modern profile to be specified
  openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver.go
  openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver_test.go
Labels: approved, lgtm, backports/validated-commits, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference
