Repository openshift/kubernetes, pull requests merged in 2025-06, with the labels that each got.

#2239 OCPNODE-3010: openshift-hack: enable userns e2e tests
  openshift-hack/cmd/k8s-tests-ext/disabled_tests.go
  test/e2e/common/node/security_context.go
Labels: approved, lgtm, jira/valid-reference

#2322 TRT-2068: Reintroduce removal of non-suite annotation rules, and fix topology selector
  openshift-hack/cmd/k8s-tests-ext/environment_selectors.go
  openshift-hack/cmd/k8s-tests-ext/labels.go
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, jira/valid-reference

#2329 Revert "TRT-2068: Reintroduce removal of non-suite annotation rules, and fix topology selector"
  openshift-hack/cmd/k8s-tests-ext/environment_selectors.go
  openshift-hack/cmd/k8s-tests-ext/labels.go
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2330 TRT-2097: UPSTREAM: <carry>: Fix up kube test suite definitions for OTE
  openshift-hack/cmd/k8s-tests-ext/k8s-tests.go
Labels: approved, lgtm, jira/valid-reference

#2332 OCPBUGS-57070: UPSTREAM: <carry>: Bump cadvisor version to fix container_fs metrics
  go.mod
  go.sum
  staging/src/k8s.io/api/go.mod
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.mod
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/component-base/go.mod
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.mod
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/kube-aggregator/go.mod
  staging/src/k8s.io/kube-aggregator/go.sum
  vendor/github.com/google/cadvisor/utils/sysfs/sysfs.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference
