Repository openshift/kubernetes, pull requests merged in 2025-01, with the labels that each got.

#2163 OCPBUGS-46061: Update to Kubernetes 1.31.4
  .go-version
  CHANGELOG/CHANGELOG-1.31.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/nodeipam/ipam/range_allocator.go
  pkg/controller/nodeipam/ipam/range_allocator_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/mount-utils/mount_linux.go
  staging/src/k8s.io/mount-utils/mount_linux_test.go
  test/images/Makefile
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2142 TRT-1836: Bug fixes for openshift-tests-extension
  go.mod
  go.sum
  go.work.sum
  openshift-hack/cmd/k8s-tests-ext/k8s-tests.go
  staging/src/k8s.io/api/go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  staging/src/k8s.io/apiserver/go.sum
  staging/src/k8s.io/component-base/go.sum
  staging/src/k8s.io/component-helpers/go.sum
  staging/src/k8s.io/kube-aggregator/go.sum
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/cmd/cmdlist/list.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/environment.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/spec.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/types.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/flags/component.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/flags/environment.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/flags/names.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference, acknowledge-critical-fixes-only

#2161 OCPBUGS-46003: Bump k8s api to 1.29.11
  CHANGELOG/CHANGELOG-1.29.md
  build/dependencies.yaml
  cluster/gce/manifests/etcd.manifest
  cluster/gce/upgrade-aliases.sh
  cluster/images/etcd/Makefile
  cluster/images/etcd/migrate/options.go
  cmd/kubeadm/app/constants/constants.go
  hack/lib/etcd.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go
  pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go
  pkg/scheduler/schedule_one_test.go
  pkg/scheduler/testing/wrappers.go
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/config_test.go
  staging/src/k8s.io/legacy-cloud-providers/azure/azure_blobDiskController_test.go
  staging/src/k8s.io/sample-apiserver/artifacts/example/deployment.yaml
  test/e2e/framework/providers/gcp.go
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2179 OCPBUGS-48364: Update to Kubernetes 1.31.4
  .go-version
  CHANGELOG/CHANGELOG-1.31.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/nodeipam/ipam/range_allocator.go
  pkg/controller/nodeipam/ipam/range_allocator_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/mount-utils/mount_linux.go
  staging/src/k8s.io/mount-utils/mount_linux_test.go
  test/images/Makefile
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2185 OCPBUGS-48819: Fix Portworx plugin's CSI translation to copy secret name & namespace
  staging/src/k8s.io/csi-translation-lib/plugins/portworx.go
  staging/src/k8s.io/csi-translation-lib/plugins/portworx_test.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2187 [4.18] OCPBUGS-49437: Fix Portworx plugin's CSI translation to copy secret name & namespace
  staging/src/k8s.io/csi-translation-lib/plugins/portworx.go
  staging/src/k8s.io/csi-translation-lib/plugins/portworx_test.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2167 OCPBUGS-48077,OCPBUGS-48078: Fix status ratcheting 4.19
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/status_strategy.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/validator.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/ratcheting_test.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, qe-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2175 OCPBUGS-48515,OCPBUGS-48079: Fix status ratcheting 4.18
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/status_strategy.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/validator.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/ratcheting_test.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference
