Repository openshift/kubernetes, pull requests merged in 2025-09, with the labels that each got.

#2417 OCPBUGS-60946: UPSTREAM: 133425: Fix SELinux label comparison
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  pkg/controller/volume/selinuxwarning/cache/volumecache_test.go
  pkg/controller/volume/selinuxwarning/translator/selinux_translator.go
  pkg/controller/volume/selinuxwarning/translator/selinux_translator_test.go
  test/e2e/storage/csimock/base.go
  test/e2e/storage/csimock/csi_selinux_mount.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only, verified

#2444 OCPBUGS-61196: UPSTREAM: 133625: Remove patch/update from ServiceCIDR API conformanc…
  test/e2e/network/service_cidrs.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference, verified

#2432 OCPBUGS-60507: Revert "UPSTREAM: <carry>: Revert "OCPBUGS-60507: Bump 1.33.4""
  .go-version
  CHANGELOG/CHANGELOG-1.33.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  plugin/pkg/admission/noderestriction/admission.go
  plugin/pkg/admission/noderestriction/admission_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/component-helpers/resource/helpers.go
  staging/src/k8s.io/component-helpers/resource/helpers_test.go
  test/e2e/common/node/runtime.go
  test/e2e_node/runtime_conformance_test.go
  test/images/.permitted-images
  test/images/Makefile
  test/utils/image/manifest.go
Labels: do-not-merge/hold, vendor-update, backports/unvalidated-commits, jira/invalid-bug, jira/valid-reference

#2440 [release-4.18] OCPBUGS-60511: Bump to v1.31.12
  .go-version
  CHANGELOG/CHANGELOG-1.31.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  openshift-hack/images/hyperkube/Dockerfile.rhel
  plugin/pkg/admission/noderestriction/admission.go
  plugin/pkg/admission/noderestriction/admission_test.go
  staging/publishing/rules.yaml
  test/images/Makefile
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#2426 OCPBUGS-60552: [4.17] podresources: list: use active pods
  pkg/kubelet/apis/podresources/server_v1.go
  pkg/kubelet/apis/podresources/server_v1_test.go
  pkg/kubelet/apis/podresources/testing/provider_mock.go
  pkg/kubelet/apis/podresources/types.go
  pkg/kubelet/kubelet.go
Labels: approved, lgtm, backports/validated-commits, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference, verified, verified-later

#2448 Revert "UPSTREAM: revert<carry>: Mark admissionregistration.k8s.io/v1beta1 as deprecated.""
  openshift-kube-apiserver/filters/apirequestcount/deprecated.go
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#2452 OCPBUGS-61222: Do not remove PVC ClaimRef to fix flaky VAC test
  test/e2e/storage/testsuites/volume_modify.go
Labels: kind/bug, approved, lgtm, kind/flake, jira/valid-bug, jira/valid-reference, verified

#2463 OCPBUGS-61720: Do not remove PVC ClaimRef to fix flaky VAC test
  test/e2e/storage/testsuites/volume_modify.go
Labels: kind/bug, approved, lgtm, kind/flake, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified, verified-later

#2458 OCPBUGS-61584: UPSTREAM: <carry>: Don't retry storage calls with side effects.
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient_test.go
Labels: approved, lgtm, vendor-update, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified, verified-later

#2459 OCPBUGS-61554: Bump 1.33.5
  .go-version
  CHANGELOG/CHANGELOG-1.33.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cmd/kubeadm/app/util/config/initconfiguration.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/securitycontext/util.go
  pkg/securitycontext/util_darwin.go
  pkg/securitycontext/util_linux.go
  pkg/securitycontext/util_test.go
  pkg/securitycontext/util_windows.go
  staging/publishing/rules.yaml
  test/e2e/storage/external/external.go
  test/images/Makefile
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, jira/valid-bug, jira/valid-reference, verified, verified-later
