Repository openshift/kubernetes, pull requests merged in 2025-07, with the labels that each got.

#2339 OCPBUGS-57861: Bump 4.20 1.32.6
  .go-version
  CHANGELOG/CHANGELOG-1.32.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  go.mod
  go.sum
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/apis/core/validation/validation.go
  pkg/apis/core/validation/validation_test.go
  pkg/kubelet/config/common.go
  pkg/kubelet/config/common_test.go
  pkg/kubelet/kubelet_getters.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/userns/types.go
  pkg/kubelet/userns/userns_manager.go
  pkg/kubelet/userns/userns_manager_disabled_test.go
  pkg/kubelet/userns/userns_manager_switch_test.go
  pkg/kubelet/userns/userns_manager_test.go
  pkg/kubelet/userns/userns_manager_windows.go
  pkg/volume/util/operationexecutor/node_expander.go
  pkg/volume/util/operationexecutor/node_expander_test.go
  pkg/volume/util/operationexecutor/operation_generator.go
  plugin/pkg/admission/noderestriction/admission.go
  plugin/pkg/admission/noderestriction/admission_test.go
  staging/publishing/rules.yaml
  test/images/Makefile
  test/utils/image/manifest.go
  vendor/github.com/Microsoft/hnslib/hcn/hcnglobals.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, jira/valid-bug, jira/valid-reference

#2348 OCPBUGS-57887: Update to Kubernetes v1.31.10
  .go-version
  CHANGELOG/CHANGELOG-1.31.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/kubelet/kubelet_getters.go
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/userns/types.go
  pkg/kubelet/userns/userns_manager.go
  pkg/kubelet/userns/userns_manager_disabled_test.go
  pkg/kubelet/userns/userns_manager_switch_test.go
  pkg/kubelet/userns/userns_manager_test.go
  pkg/kubelet/userns/userns_manager_windows.go
  pkg/util/kernel/constants.go
  staging/publishing/rules.yaml
  test/images/Makefile
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2331 TRT-2068: Reintroduce non-suite annotation removal
  openshift-hack/cmd/k8s-tests-ext/environment_selectors.go
  openshift-hack/cmd/k8s-tests-ext/labels.go
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2383 TRT-2068: Skip specific LoadBalancer test for "none" platform
  openshift-hack/cmd/k8s-tests-ext/environment_selectors.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference
