Repository openshift/kubernetes, pull requests merged in 2025-03, with the labels that each got.

#2228 OCPBUGS-45274: UPSTREAM: 130097: Modify how to check the status
  test/e2e/node/pod_admission.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2229 NO-JIRA: Initialize testContext before enumerating tests
  openshift-hack/cmd/k8s-tests-ext/k8s-tests.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2236 OCPBUGS-52477: Revert #2229: Initialize testContext before enumerating tests
  openshift-hack/cmd/k8s-tests-ext/k8s-tests.go
Labels: approved, lgtm, backports/validated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference

#2192 OCPBUGS-44693: Revert "disable ResilientWatchCacheInitialization feature"
  pkg/features/versioned_kube_features.go
  staging/src/k8s.io/apiserver/pkg/features/kube_features.go
  test/featuregates_linter/test_data/versioned_feature_list.yaml
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2232 STOR-2285: UPSTREAM: <carry>: Add volume group snapshot test driver
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
  openshift-hack/test-kubernetes-e2e.sh
  test/e2e/storage/drivers/openshift_group_snapshot_driver.go
  test/e2e/storage/openshift_csi_volumes.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2215 TRT-1854: translate test annotations to use: `include`/`exclude` CEL, labels, filtering
  openshift-hack/cmd/k8s-tests-ext/disabled_tests.go
  openshift-hack/cmd/k8s-tests-ext/environment_selectors.go
  openshift-hack/cmd/k8s-tests-ext/k8s-tests.go
  openshift-hack/cmd/k8s-tests-ext/labels.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference

#2235 OCPBUGS-45273: Properly annotate networking skip according to Jira ticket
  openshift-hack/cmd/k8s-tests-ext/disabled_tests.go
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2248 OCPBUGS-53015: Update to Kubernetes v1.31.7
  .go-version
  CHANGELOG/CHANGELOG-1.31.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cmd/kubeadm/app/util/config/common.go
  cmd/kubeadm/app/util/config/common_test.go
  cmd/kubeadm/app/util/config/upgradeconfiguration.go
  cmd/kubeadm/app/util/config/upgradeconfiguration_test.go
  hack/jenkins/benchmark-dockerized.sh
  hack/jenkins/test-dockerized.sh
  hack/lib/golang.sh
  hack/make-rules/test.sh
  hack/update-mocks.sh
  hack/update-netparse-cve.sh
  hack/update-vanity-imports.sh
  hack/verify-golangci-lint.sh
  hack/verify-spelling.sh
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/namespace/deletion/namespaced_resources_deleter.go
  pkg/features/kube_features.go
  pkg/kubelet/server/auth_test.go
  pkg/kubelet/server/server_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/admission.go
  staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/resource_access.go
  staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/resource_access_test.go
  staging/src/k8s.io/apiserver/pkg/util/proxy/streamtranslator.go
  staging/src/k8s.io/component-base/metrics/prometheus/slis/routes.go
  staging/src/k8s.io/component-base/metrics/prometheus/slis/routes_test.go
  test/e2e/apimachinery/namespace.go
  test/e2e/feature/feature.go
  test/e2e/kubectl/kubectl.go
  test/e2e/windows/gmsa_full.go
  test/images/Makefile
  test/integration/job/job_test.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference
