Repository openshift/kubernetes, pull requests merged in 2025-05, with the labels that each got.

#2255 TRT-2066: Use OTE generated labels for skips in test-kubernetes-e2e.sh
  .openshift-tests-extension/openshift_payload_hyperkube.json
  openshift-hack/cmd/k8s-tests-ext/environment_selectors.go
  openshift-hack/cmd/k8s-tests-ext/k8s-tests.go
  openshift-hack/cmd/k8s-tests-ext/labels.go
  openshift-hack/e2e/kube_e2e_test.go
  openshift-hack/images/tests/Dockerfile.rhel
  openshift-hack/test-kubernetes-e2e.sh
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference, acknowledge-critical-fixes-only

#2275 OCPBUGS-55265: Bump 1.32.4
  CHANGELOG/CHANGELOG-1.32.md
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher_test.go
  staging/src/k8s.io/apiserver/pkg/storage/testing/watcher_tests.go
  test/e2e/storage/csimock/csi_kubelet_restart.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2278 OCPBUGS-55267: Update to Kubernetes v1.31.8
  CHANGELOG/CHANGELOG-1.31.md
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher_test.go
  staging/src/k8s.io/apiserver/pkg/storage/testing/watcher_tests.go
  test/e2e/storage/csimock/csi_kubelet_restart.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2280 OCPBUGS-55269: Bump k8s api to 1.30.12
  CHANGELOG/CHANGELOG-1.30.md
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/include.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/kubelet/server/auth_test.go
  pkg/kubelet/server/server_test.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher_test.go
  staging/src/k8s.io/apiserver/pkg/storage/testing/watcher_tests.go
  staging/src/k8s.io/component-base/metrics/prometheus/slis/routes.go
  staging/src/k8s.io/component-base/metrics/prometheus/slis/routes_test.go
  test/e2e/e2e_test.go
  test/e2e/storage/csimock/base.go
  test/e2e/storage/csimock/csi_attach_volume.go
  test/e2e/storage/csimock/csi_fsgroup_mount.go
  test/e2e/storage/csimock/csi_fsgroup_policy.go
  test/e2e/storage/csimock/csi_kubelet_restart.go
  test/e2e/storage/csimock/csi_node_stage_error_cases.go
  test/e2e/storage/csimock/csi_selinux_mount.go
  test/e2e/storage/csimock/csi_service_account_token.go
  test/e2e/storage/csimock/csi_snapshot.go
  test/e2e/storage/csimock/csi_storage_capacity.go
  test/e2e/storage/csimock/csi_volume_expansion.go
  test/e2e/storage/csimock/csi_volume_limit.go
  test/e2e/storage/csimock/csi_workload.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2227 [release-4.15] OCPBUGS-52183: UPSTREAM: <carry>: kubelet/cm: fix bug where kubelet restarts from missing cpuset cgroup
  pkg/kubelet/cm/cgroup_manager_linux.go
  pkg/kubelet/cm/cpumanager/cpu_manager.go
  pkg/kubelet/cm/cpumanager/cpu_manager_test.go
  pkg/kubelet/cm/cpumanager/fake_cpu_manager.go
  pkg/kubelet/cm/node_container_manager_linux.go
  pkg/kubelet/cm/types.go
  test/e2e_node/node_container_manager_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#2282 OCPBUGS-55632: Fix node expansion on older kubelets
  pkg/volume/util/operationexecutor/node_expander.go
  pkg/volume/util/operationexecutor/node_expander_test.go
  pkg/volume/util/operationexecutor/operation_generator.go
  pkg/volume/util/operationexecutor/operation_generator_test.go
  pkg/volume/util/resize_util.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2287 NO-JIRA: UPSTREAM: <carry>: Mark admissionregistration.k8s.io/v1beta1 as deprecated.
  openshift-kube-apiserver/filters/apirequestcount/deprecated.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2291 TRT-2103: Revert "NO-JIRA: UPSTREAM: <carry>: Mark admissionregistration.k8s.io/v1beta1 as deprecated."
  openshift-kube-apiserver/filters/apirequestcount/deprecated.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2292 OCPBUGS-55945: Bump main 1.32.4
  CHANGELOG/CHANGELOG-1.32.md
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher_test.go
  staging/src/k8s.io/apiserver/pkg/storage/testing/watcher_tests.go
  test/e2e/storage/csimock/csi_kubelet_restart.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2283 UPSTREAM: 127757 : OCPBUGS-55639: scheduler: Improve CSILimits plugi…
  pkg/scheduler/framework/plugins/nodevolumelimits/csi.go
  pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go
  pkg/scheduler/testing/framework/fake_listers.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
  plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
Labels: kind/bug, approved, lgtm, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#2277 OCPBUGS-54208: UPSTREAM: 130047: adjusting loopback certificate validity in kube-apiserver
  staging/src/k8s.io/apiserver/pkg/server/options/serving_with_loopback.go
  staging/src/k8s.io/client-go/util/cert/cert.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2296 NO-JIRA: Fix generation of test names
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/kube_e2e_test.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-reference

#2288 OCPBUGS-55631: UPSTREAM: 131495: Handle unsupported node expansion for RWX volumes
  pkg/volume/util/operationexecutor/node_expander.go
  pkg/volume/util/operationexecutor/node_expander_test.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2295 OCPBUGS-55944: UPSTREAM: <carry>: unrevert: Mark admissionregistration.k8s.io/v1beta1 as deprecated.
  openshift-kube-apiserver/filters/apirequestcount/deprecated.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2285 CNTRLPLANE-179: apiserver library go bump
  go.mod
  go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/admission.go
  vendor/github.com/openshift/apiserver-library-go/pkg/securitycontextconstraints/sccadmission/scc_authz_check.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference

#2307 OCPBUGS-56438: Update to Kubernetes v1.31.9
  .go-version
  CHANGELOG/CHANGELOG-1.31.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/proxy/winkernel/hns.go
  pkg/proxy/winkernel/hns_test.go
  pkg/proxy/winkernel/proxier.go
  pkg/proxy/winkernel/proxier_test.go
  pkg/volume/util/operationexecutor/node_expander.go
  pkg/volume/util/operationexecutor/node_expander_test.go
  pkg/volume/util/operationexecutor/operation_generator.go
  pkg/volume/util/operationexecutor/operation_generator_test.go
  pkg/volume/util/resize_util.go
  staging/publishing/rules.yaml
  test/images/Makefile
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference
