Repository openshift/kubernetes, pull requests merged in 2025-02, with the labels that each got.

#2109 OCPEDGE-1314: feat: add arbiter node role
  staging/src/k8s.io/kubelet/pkg/apis/well_known_openshift_labels.go
Labels: approved, lgtm, vendor-update, jira/valid-reference, acknowledge-critical-fixes-only

#2174 OCPBUGS-48177: UPSTREAM: <carry>: disable etcd readiness checks by default
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/options/etcd.go
  staging/src/k8s.io/apiserver/pkg/server/options/etcd_test.go
  test/e2e/apimachinery/health_handlers.go
Labels: approved, kind/feature, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2113 OCPBUGS-38121: OCPBUGS-39305: UPSTREAM: <carry>: log only deprecated api requests
  openshift-kube-apiserver/filters/apirequestcount/apiaccess_count_controller.go
  openshift-kube-apiserver/filters/apirequestcount/apiaccess_count_controller_test.go
  openshift-kube-apiserver/filters/apirequestcount/deprecated.go
  openshift-kube-apiserver/filters/apirequestcount_filter.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2182 NO-JIRA: Add benluddy to DOWNSTREAM_OWNERS.
  DOWNSTREAM_OWNERS
Labels: approved, lgtm, backports/validated-commits, backport-risk-assessed, jira/valid-reference, acknowledge-critical-fixes-only

#2191 OCPBUGS-48694: Don't retry storage calls with side effects.
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient_test.go
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/retry_etcdprobemonitor.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2176 OCPBUGS-48552: Update to Kubernetes 1.31.5
  .go-version
  CHANGELOG/CHANGELOG-1.31.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cmd/kubeadm/app/cmd/upgrade/node.go
  go.work.sum
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/statefulset/stateful_set_control_test.go
  pkg/features/kube_features.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/kubelet/apis/config/types.go
  pkg/kubelet/kubelet_server_journal.go
  pkg/kubelet/kubelet_server_journal_linux.go
  pkg/kubelet/kubelet_server_journal_others.go
  pkg/kubelet/kubelet_server_journal_test.go
  pkg/kubelet/kubelet_server_journal_windows.go
  pkg/kubelet/volumemanager/cache/actual_state_of_world.go
  pkg/kubelet/volumemanager/reconciler/reconciler_common.go
  pkg/volume/util/device_util_linux.go
  pkg/volume/util/device_util_linux_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/apiserver/pkg/util/webhook/webhook_test.go
  staging/src/k8s.io/kubelet/config/v1beta1/types.go
  test/e2e/storage/testsuites/volume_expand.go
  test/e2e_node/remote/utils.go
  test/images/Makefile
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2197 OCPBUGS-49841: Don't retry storage calls with side effects.
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
  staging/src/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient_test.go
  staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/retry_etcdprobemonitor.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2200 [release-4.16] OCPBUGS-45931: UPSTREAM: <carry>: kubelet/cm: fix bug where kubelet restarts from missing cpuset cgroup #2158
  pkg/kubelet/cm/cgroup_manager_linux.go
  pkg/kubelet/cm/cpumanager/cpu_manager.go
  pkg/kubelet/cm/cpumanager/cpu_manager_test.go
  pkg/kubelet/cm/cpumanager/fake_cpu_manager.go
  pkg/kubelet/cm/node_container_manager_linux.go
  pkg/kubelet/cm/types.go
  test/e2e_node/node_container_manager_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#2194 TRT-1854: UPSTREAM: <drop>: ./hack/update-vendor.sh for openshift-tests-extension
  go.mod
  go.sum
  staging/src/k8s.io/apimachinery/go.mod
  staging/src/k8s.io/client-go/go.mod
  staging/src/k8s.io/kubectl/go.mod
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/cmd/cmd.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/cmd/cmdimages/cmdimages.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extension.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/environment.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/spec.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/types.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/flags/environment.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference, acknowledge-critical-fixes-only

#2202 OCPBUGS-46477: Disable ServiceAccountNodeAudienceRestriction feature gate and reenable Azure file tests
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
  pkg/features/versioned_kube_features.go
  test/featuregates_linter/test_data/versioned_feature_list.yaml
Labels: kind/bug, kind/failing-test, approved, lgtm, backports/validated-commits, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2177 TRT-1286: List images from external test binary
  openshift-hack/cmd/k8s-tests-ext/k8s-tests.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference, acknowledge-critical-fixes-only

#2198 OCPBUGS-49905: Bump k8s api to 1.30.9
  .go-version
  CHANGELOG/CHANGELOG-1.30.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/statefulset/stateful_set_control_test.go
  pkg/features/kube_features.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/kubelet/apis/config/types.go
  pkg/kubelet/kubelet_server_journal.go
  pkg/kubelet/kubelet_server_journal_linux.go
  pkg/kubelet/kubelet_server_journal_others.go
  pkg/kubelet/kubelet_server_journal_test.go
  pkg/kubelet/kubelet_server_journal_windows.go
  pkg/kubelet/volumemanager/cache/actual_state_of_world.go
  pkg/kubelet/volumemanager/reconciler/reconciler_common.go
  pkg/volume/util/atomic_writer.go
  pkg/volume/util/atomic_writer_linux.go
  pkg/volume/util/atomic_writer_unsupported.go
  pkg/volume/util/device_util_linux.go
  pkg/volume/util/device_util_linux_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/apiserver/pkg/util/webhook/webhook_test.go
  staging/src/k8s.io/kubelet/config/v1beta1/types.go
  staging/src/k8s.io/mount-utils/mount_linux.go
  staging/src/k8s.io/mount-utils/mount_linux_test.go
  test/e2e/storage/testsuites/volume_expand.go
  test/e2e/windows/security_context.go
  test/e2e_node/remote/utils.go
  test/images/Makefile
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, cherry-pick-approved, backports/validated-commits, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2119 NO-JIRA: UPSTREAM: fix request Host storing in openshift.io/during-graceful audit log annotation
  staging/src/k8s.io/apiserver/pkg/server/patch_genericapiserver.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference, acknowledge-critical-fixes-only

#2209 CNTRLPLANE-1: Bump 1.32.2
  .go-version
  CHANGELOG/CHANGELOG-1.32.md
  build/build-image/cross/VERSION
  build/common.sh
  build/dependencies.yaml
  cmd/kubeadm/app/preflight/checks.go
  cmd/kubeadm/app/util/etcd/etcd.go
  hack/apidiff.sh
  openshift-hack/images/hyperkube/Dockerfile.rhel
  pkg/kubelet/server/server.go
  pkg/volume/fc/fc_util_linux_test.go
  pkg/volume/fc/fc_util_test.go
  staging/publishing/rules.yaml
  staging/src/k8s.io/code-generator/kube_codegen.sh
  test/e2e/storage/csimock/csi_volume_expansion.go
  test/e2e/testing-manifests/storage-csi/gce-pd/controller_ss.yaml
  test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  test/images/Makefile
  test/integration/job/job_test.go
  test/utils/image/manifest.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference

#2104 OCPNODE-2940: add minimumkubeletversion package
  openshift-kube-apiserver/authorization/minimumkubeletversion/minimum_kubelet_version.go
  openshift-kube-apiserver/authorization/minimumkubeletversion/minimum_kubelet_version_test.go
  openshift-kube-apiserver/enablement/intialization.go
  pkg/features/openshift_features.go
  pkg/kubeapiserver/authorizer/modes/patch.go
  pkg/kubeapiserver/authorizer/patch.go
  pkg/kubeapiserver/authorizer/reload.go
  vendor/github.com/openshift/library-go/pkg/apiserver/node/minimum_kubelet_version.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, vendor-update, backports/validated-commits, jira/valid-reference

#2217 OAPE-96: UPSTREAM: <drop>: bump openshift/api@107848b719c5
  go.mod
  go.sum
  staging/src/k8s.io/apiextensions-apiserver/go.mod
  staging/src/k8s.io/apiextensions-apiserver/go.sum
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference

#2213 OCPBUGS-45241: UPSTREAM: <carry>: Re-enable temporarily disabled port-forward test
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2218 OCPBUGS-45359: Unskip recover volume expansion failure tests
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference

#2214 TRT-1854: Update openshift-tests-extension version
  go.mod
  go.sum
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extension.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/environment.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/spec.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/types.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/types.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/ginkgo/util.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/LICENSE
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/README.md
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/byte.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/doc.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/empty.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/int.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/int32.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/int64.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/set.go
  vendor/github.com/openshift-eng/openshift-tests-extension/pkg/util/sets/string.go
  vendor/modules.txt
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference

#2201 OCPNODE-2940: add minimumkubeletversion admission package
  openshift-kube-apiserver/admission/customresourcevalidation/node/restrict_extreme_worker_latency_profile.go
  openshift-kube-apiserver/admission/customresourcevalidation/node/restrict_extreme_worker_latency_profile_test.go
  openshift-kube-apiserver/admission/customresourcevalidation/node/validate_node_config.go
  openshift-kube-apiserver/admission/customresourcevalidation/node/validate_node_config_test.go
Labels: approved, lgtm, vendor-update, backports/validated-commits, jira/valid-reference

#2155 OCPBUGS-45214: Add groupsnapshot tests
  openshift-hack/e2e/annotate/generated/zz_generated.annotations.go
  openshift-hack/e2e/annotate/rules.go
  test/e2e/storage/framework/volume_group_snapshot_resource.go
  test/e2e/storage/testsuites/volume_group_snapshottable.go
  test/e2e/storage/utils/volume_group_snapshot.go
  test/e2e/testing-manifests/storage-csi/external-snapshotter/groupsnapshot.storage.k8s.io_volumegroupsnapshotclasses.yaml
  test/e2e/testing-manifests/storage-csi/external-snapshotter/groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml
  test/e2e/testing-manifests/storage-csi/external-snapshotter/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml
  test/e2e/testing-manifests/storage-csi/external-snapshotter/volume-group-snapshots/csi-hostpath-plugin.yaml
  test/e2e/testing-manifests/storage-csi/external-snapshotter/volume-group-snapshots/run_group_snapshot_e2e.sh
  test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
Labels: approved, lgtm, backports/validated-commits, jira/valid-bug, jira/valid-reference
